//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.27 at 02:23:06 PM CET 
//

package it.eng.sil.nsr.DataModels.InformationDelivery.xsd.NotificaAppuntamentoEsito._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for NuovoAppuntamentoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NuovoAppuntamentoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdAppuntamentoAR" type="{http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0}IdAppuntamentoARType"/>
 *         &lt;element name="IdDisponibilitaAR" type="{http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0}IdAppuntamentoARType" minOccurs="0"/>
 *         &lt;element name="CodiceIntermediario" type="{http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0}CodiceIntermediarioType"/>
 *         &lt;element name="IdSportello" type="{http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0}IdSportelloType" minOccurs="0"/>
 *         &lt;element name="DescrizioneSportello" type="{http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0}DescrizioneSportelloType" minOccurs="0"/>
 *         &lt;element name="DataOraAppuntamento" type="{http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0}DataOraAppuntamentoType"/>
 *         &lt;element name="NoteSedeRegione" type="{http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0}NoteSedeRegioneType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NuovoAppuntamentoType", propOrder = { "idAppuntamentoAR", "idDisponibilitaAR", "codiceIntermediario",
		"idSportello", "descrizioneSportello", "dataOraAppuntamento", "noteSedeRegione" })
public class NuovoAppuntamentoType {

	@XmlElement(name = "IdAppuntamentoAR", required = true)
	protected String idAppuntamentoAR;
	@XmlElement(name = "IdDisponibilitaAR")
	protected String idDisponibilitaAR;
	@XmlElement(name = "CodiceIntermediario", required = true)
	protected String codiceIntermediario;
	@XmlElement(name = "IdSportello")
	protected String idSportello;
	@XmlElement(name = "DescrizioneSportello")
	protected String descrizioneSportello;
	@XmlElement(name = "DataOraAppuntamento", required = true)
	protected XMLGregorianCalendar dataOraAppuntamento;
	@XmlElement(name = "NoteSedeRegione")
	protected String noteSedeRegione;

	/**
	 * Gets the value of the idAppuntamentoAR property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdAppuntamentoAR() {
		return idAppuntamentoAR;
	}

	/**
	 * Sets the value of the idAppuntamentoAR property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdAppuntamentoAR(String value) {
		this.idAppuntamentoAR = value;
	}

	/**
	 * Gets the value of the idDisponibilitaAR property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdDisponibilitaAR() {
		return idDisponibilitaAR;
	}

	/**
	 * Sets the value of the idDisponibilitaAR property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdDisponibilitaAR(String value) {
		this.idDisponibilitaAR = value;
	}

	/**
	 * Gets the value of the codiceIntermediario property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodiceIntermediario() {
		return codiceIntermediario;
	}

	/**
	 * Sets the value of the codiceIntermediario property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodiceIntermediario(String value) {
		this.codiceIntermediario = value;
	}

	/**
	 * Gets the value of the idSportello property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdSportello() {
		return idSportello;
	}

	/**
	 * Sets the value of the idSportello property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdSportello(String value) {
		this.idSportello = value;
	}

	/**
	 * Gets the value of the descrizioneSportello property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescrizioneSportello() {
		return descrizioneSportello;
	}

	/**
	 * Sets the value of the descrizioneSportello property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescrizioneSportello(String value) {
		this.descrizioneSportello = value;
	}

	/**
	 * Gets the value of the dataOraAppuntamento property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDataOraAppuntamento() {
		return dataOraAppuntamento;
	}

	/**
	 * Sets the value of the dataOraAppuntamento property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDataOraAppuntamento(XMLGregorianCalendar value) {
		this.dataOraAppuntamento = value;
	}

	/**
	 * Gets the value of the noteSedeRegione property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNoteSedeRegione() {
		return noteSedeRegione;
	}

	/**
	 * Sets the value of the noteSedeRegione property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNoteSedeRegione(String value) {
		this.noteSedeRegione = value;
	}

}
