//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.27 at 02:23:06 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.eng.sil.nsr.DataModels.InformationDelivery.xsd.NotificaAppuntamentoEsito._1_0;
