//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.06 at 12:08:29 PM CET 
//


package it.eng.myportal.cliclavoro.vacancy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}DatiAnagrafici"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}DatiContatto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datiAnagrafici",
    "datiContatto"
})
@XmlRootElement(name = "DatoreLavoro")
public class DatoreLavoro {

    @XmlElement(name = "DatiAnagrafici", required = true)
    protected DatiAnagrafici datiAnagrafici;
    @XmlElement(name = "DatiContatto", required = true)
    protected DatiContatto datiContatto;

    /**
     * Gets the value of the datiAnagrafici property.
     * 
     * @return
     *     possible object is
     *     {@link DatiAnagrafici }
     *     
     */
    public DatiAnagrafici getDatiAnagrafici() {
        return datiAnagrafici;
    }

    /**
     * Sets the value of the datiAnagrafici property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiAnagrafici }
     *     
     */
    public void setDatiAnagrafici(DatiAnagrafici value) {
        this.datiAnagrafici = value;
    }

    /**
     * Gets the value of the datiContatto property.
     * 
     * @return
     *     possible object is
     *     {@link DatiContatto }
     *     
     */
    public DatiContatto getDatiContatto() {
        return datiContatto;
    }

    /**
     * Sets the value of the datiContatto property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiContatto }
     *     
     */
    public void setDatiContatto(DatiContatto value) {
        this.datiContatto = value;
    }

}
