//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.08 at 11:13:18 AM CET 
//

package it.eng.sil.module.patto.politicheattive;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * it.eng.sil.module.patto.politicheattive package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _TipoAttivita_QNAME = new QName("", "tipo_attivita");
	private final static QName _Data_QNAME = new QName("", "data");
	private final static QName _DataFine_QNAME = new QName("", "data_fine");
	private final static QName _Durata_QNAME = new QName("", "durata");
	private final static QName _EsitoAzioneSil_QNAME = new QName("", "esito_azione_sil");
	private final static QName _CodiceEntePromotore_QNAME = new QName("", "codice_ente_promotore");
	private final static QName _DescrizioneAzioneSil_QNAME = new QName("", "descrizione_azione_sil");
	private final static QName _DataStimata_QNAME = new QName("", "data_stimata");
	private final static QName _TipologiaDurata_QNAME = new QName("", "tipologia_durata");
	private final static QName _Lavoratore_QNAME = new QName("", "lavoratore");
	private final static QName _Descrizione_QNAME = new QName("", "descrizione");
	private final static QName _TitoloDenominazione_QNAME = new QName("", "titolo_denominazione");
	private final static QName _DataProposta_QNAME = new QName("", "data_proposta");
	private final static QName _TitoloProgetto_QNAME = new QName("", "titolo_progetto");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * it.eng.sil.module.patto.politicheattive
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link LavoratorePoliticheType.PoliticheAttiveLst }
	 * 
	 */
	public LavoratorePoliticheType.PoliticheAttiveLst createLavoratorePoliticheTypePoliticheAttiveLst() {
		return new LavoratorePoliticheType.PoliticheAttiveLst();
	}

	/**
	 * Create an instance of {@link PoliticheAttive }
	 * 
	 */
	public PoliticheAttive createPoliticheAttive() {
		return new PoliticheAttive();
	}

	/**
	 * Create an instance of {@link LavoratorePoliticheType }
	 * 
	 */
	public LavoratorePoliticheType createLavoratorePoliticheType() {
		return new LavoratorePoliticheType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipo_attivita")
	public JAXBElement<String> createTipoAttivita(String value) {
		return new JAXBElement<String>(_TipoAttivita_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "data")
	public JAXBElement<XMLGregorianCalendar> createData(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Data_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "data_fine")
	public JAXBElement<XMLGregorianCalendar> createDataFine(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_DataFine_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "durata")
	public JAXBElement<Integer> createDurata(Integer value) {
		return new JAXBElement<Integer>(_Durata_QNAME, Integer.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "esito_azione_sil")
	public JAXBElement<String> createEsitoAzioneSil(String value) {
		return new JAXBElement<String>(_EsitoAzioneSil_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codice_ente_promotore")
	public JAXBElement<String> createCodiceEntePromotore(String value) {
		return new JAXBElement<String>(_CodiceEntePromotore_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "descrizione_azione_sil")
	public JAXBElement<String> createDescrizioneAzioneSil(String value) {
		return new JAXBElement<String>(_DescrizioneAzioneSil_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "data_stimata")
	public JAXBElement<XMLGregorianCalendar> createDataStimata(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_DataStimata_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipologia_durata")
	public JAXBElement<String> createTipologiaDurata(String value) {
		return new JAXBElement<String>(_TipologiaDurata_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link LavoratorePoliticheType }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "lavoratore")
	public JAXBElement<LavoratorePoliticheType> createLavoratore(LavoratorePoliticheType value) {
		return new JAXBElement<LavoratorePoliticheType>(_Lavoratore_QNAME, LavoratorePoliticheType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "descrizione")
	public JAXBElement<String> createDescrizione(String value) {
		return new JAXBElement<String>(_Descrizione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "titolo_denominazione")
	public JAXBElement<String> createTitoloDenominazione(String value) {
		return new JAXBElement<String>(_TitoloDenominazione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "data_proposta")
	public JAXBElement<XMLGregorianCalendar> createDataProposta(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_DataProposta_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "titolo_progetto")
	public JAXBElement<String> createTitoloProgetto(String value) {
		return new JAXBElement<String>(_TitoloProgetto_QNAME, String.class, null, value);
	}

}
