//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.08 at 11:13:18 AM CET 
//

package it.eng.sil.module.patto.politicheattive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}tipo_attivita"/>
 *         &lt;element ref="{}titolo_denominazione" minOccurs="0"/>
 *         &lt;element ref="{}data_proposta"/>
 *         &lt;element ref="{}data" minOccurs="0"/>
 *         &lt;element ref="{}data_fine" minOccurs="0"/>
 *         &lt;element ref="{}durata" minOccurs="0"/>
 *         &lt;element ref="{}tipologia_durata" minOccurs="0"/>
 *         &lt;element ref="{}descrizione"/>
 *         &lt;element ref="{}titolo_progetto"/>
 *         &lt;element ref="{}codice_ente_promotore"/>
 *         &lt;element ref="{}descrizione_azione_sil" minOccurs="0"/>
 *         &lt;element ref="{}esito_azione_sil" minOccurs="0"/>
 *         &lt;element ref="{}data_stimata" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "tipoAttivita", "titoloDenominazione", "dataProposta", "data", "dataFine", "durata",
		"tipologiaDurata", "descrizione", "titoloProgetto", "codiceEntePromotore", "descrizioneAzioneSil",
		"esitoAzioneSil", "dataStimata" })
@XmlRootElement(name = "politiche_attive")
public class PoliticheAttive {

	@XmlElement(name = "tipo_attivita", required = true)
	protected String tipoAttivita;
	@XmlElement(name = "titolo_denominazione")
	protected String titoloDenominazione;
	@XmlElement(name = "data_proposta", required = true)
	protected XMLGregorianCalendar dataProposta;
	protected XMLGregorianCalendar data;
	@XmlElement(name = "data_fine")
	protected XMLGregorianCalendar dataFine;
	protected Integer durata;
	@XmlElement(name = "tipologia_durata")
	protected String tipologiaDurata;
	@XmlElement(required = true)
	protected String descrizione;
	@XmlElement(name = "titolo_progetto", required = true)
	protected String titoloProgetto;
	@XmlElement(name = "codice_ente_promotore", required = true)
	protected String codiceEntePromotore;
	@XmlElement(name = "descrizione_azione_sil")
	protected String descrizioneAzioneSil;
	@XmlElement(name = "esito_azione_sil")
	protected String esitoAzioneSil;
	@XmlElement(name = "data_stimata")
	protected XMLGregorianCalendar dataStimata;

	/**
	 * Gets the value of the tipoAttivita property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTipoAttivita() {
		return tipoAttivita;
	}

	/**
	 * Sets the value of the tipoAttivita property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTipoAttivita(String value) {
		this.tipoAttivita = value;
	}

	/**
	 * Gets the value of the titoloDenominazione property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitoloDenominazione() {
		return titoloDenominazione;
	}

	/**
	 * Sets the value of the titoloDenominazione property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitoloDenominazione(String value) {
		this.titoloDenominazione = value;
	}

	/**
	 * Gets the value of the dataProposta property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDataProposta() {
		return dataProposta;
	}

	/**
	 * Sets the value of the dataProposta property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDataProposta(XMLGregorianCalendar value) {
		this.dataProposta = value;
	}

	/**
	 * Gets the value of the data property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getData() {
		return data;
	}

	/**
	 * Sets the value of the data property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setData(XMLGregorianCalendar value) {
		this.data = value;
	}

	/**
	 * Gets the value of the dataFine property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDataFine() {
		return dataFine;
	}

	/**
	 * Sets the value of the dataFine property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDataFine(XMLGregorianCalendar value) {
		this.dataFine = value;
	}

	/**
	 * Gets the value of the durata property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getDurata() {
		return durata;
	}

	/**
	 * Sets the value of the durata property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setDurata(Integer value) {
		this.durata = value;
	}

	/**
	 * Gets the value of the tipologiaDurata property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTipologiaDurata() {
		return tipologiaDurata;
	}

	/**
	 * Sets the value of the tipologiaDurata property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTipologiaDurata(String value) {
		this.tipologiaDurata = value;
	}

	/**
	 * Gets the value of the descrizione property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * Sets the value of the descrizione property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescrizione(String value) {
		this.descrizione = value;
	}

	/**
	 * Gets the value of the titoloProgetto property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitoloProgetto() {
		return titoloProgetto;
	}

	/**
	 * Sets the value of the titoloProgetto property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitoloProgetto(String value) {
		this.titoloProgetto = value;
	}

	/**
	 * Gets the value of the codiceEntePromotore property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodiceEntePromotore() {
		return codiceEntePromotore;
	}

	/**
	 * Sets the value of the codiceEntePromotore property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodiceEntePromotore(String value) {
		this.codiceEntePromotore = value;
	}

	/**
	 * Gets the value of the descrizioneAzioneSil property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescrizioneAzioneSil() {
		return descrizioneAzioneSil;
	}

	/**
	 * Sets the value of the descrizioneAzioneSil property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescrizioneAzioneSil(String value) {
		this.descrizioneAzioneSil = value;
	}

	/**
	 * Gets the value of the esitoAzioneSil property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEsitoAzioneSil() {
		return esitoAzioneSil;
	}

	/**
	 * Sets the value of the esitoAzioneSil property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEsitoAzioneSil(String value) {
		this.esitoAzioneSil = value;
	}

	/**
	 * Gets the value of the dataStimata property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDataStimata() {
		return dataStimata;
	}

	/**
	 * Sets the value of the dataStimata property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDataStimata(XMLGregorianCalendar value) {
		this.dataStimata = value;
	}

}
