set define off
set pagesize 20
set linesize 150
set sqlblanklines on
COL C1 HEADING 'OBJECT_NAME' FORMAT A50
COL C2 HEADING 'OBJECT_TYPE' FORMAT A20
COL C3 HEADING 'OBJECT_STATUS' FORMAT A20


select object_name c1, object_type c2, status c3 from
(select CONSTRAINT_NAME OBJECT_NAME, 'CONSTRAINT' OBJECT_TYPE, STATUS from USER_CONSTRAINTS where STATUS <> 'ENABLED'
union all
select CONSTRAINT_NAME object_name, 'CONSTRAINT' OBJECT_TYPE , VALIDATED STATUS from USER_CONSTRAINTS where VALIDATED <> 'VALIDATED'
union all
select TRIGGER_NAME object_name, 'TRIGGER' OBJECT_TYPE, STATUS from USER_TRIGGERS where STATUS <> 'ENABLED'
union all
select OBJECT_NAME, OBJECT_TYPE, STATUS from USER_OBJECTS where STATUS <> 'VALID'
union all
select INDEX_NAME OBJECT_NAME, 'INDEX' OBJECT_TYPE, STATUS from USER_INDEXES where STATUS <> 'VALID'
);


