package it.eng.sil.module.movimenti.enumeration;

public enum TipoTrasfEnum {

PROGRESSIONE_VERTICALE_PA("PV"),
//
TRASFORMAZIONE_TD_TI("DI"),
//
TRASFORMAZIONE_TPARZIALE_TPIENO("PP"),
//
TRASFORMAZIONE_APPRENDISTATO_TI("AI"),
//
TRASFORMAZIONE_FORMAZIONE_TI("FI"),
//
TRASFORMAZIONE_INSERIMENTO_TI("II"),
//
DISTACCO_COMANDO("DL"),
//
TRASFERIMENTO_DEL_LAVORATORE("TL"),
//
TRASFORMAZIONE_TPIENO_TPARZIALE("TP"),
//
CESSIONE_RAMO("01"),
//
AFFITTO_RAMO("02"),
//
INCORPORAZIONE("03"),
//
FUSIONE("04"),
//
USUSFRUTTO("05"),
//
CESSIONE_DI_CONTRATTO("6"),
//
TRASFORMAZIONI_NON_OBBLIGATORIE("NT"),
//
FINE_ANTICIPATA_PERIODO_FORMATIVO("FF"),
//
PROSECUZIONE_PERIODO_FORMATIVO("ZZ"),
//
TRASFORMAZIONE_APPRENDISTATO_APP_PROFESS("DP");

private String codice;

private TipoTrasfEnum(String codice) {
	this.codice = codice;
}

public String getCodice() {
	return codice;
}
}
