package it.eng.myportal.entity.decodifiche;

// default package
// Generated 11-mar-2013 11.48.19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.CacheConcurrencyStrategy;

import it.eng.myportal.entity.AbstractDecodeEntity;

/**
 * DeAtpAttivitaSvolta generated by hbm2java
 */
@Entity
@Table(name = "de_atp_attivita_svolta", schema = "myportal")
@org.hibernate.annotations.Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class DeAtpAttivitaSvolta extends AbstractDecodeEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6772654255643638697L;
	private String codAtpAttivitaSvolta;
	private String descrizione;
	
	public DeAtpAttivitaSvolta() {
	}


	@Id
	@Column(name = "cod_atp_attivita_svolta", unique = true, nullable = false, length = 8)
	public String getCodAtpAttivitaSvolta() {
		return this.codAtpAttivitaSvolta;
	}

	public void setCodAtpAttivitaSvolta(String codAtpAttivitaSvolta) {
		this.codAtpAttivitaSvolta = codAtpAttivitaSvolta;
	}

	@Column(name = "descrizione", nullable = false, length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}


}
