package it.eng.myportal.entity.decodifiche;

// default package
// Generated 11-mar-2013 11.48.19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.CacheConcurrencyStrategy;

import it.eng.myportal.entity.AbstractDecodeEntity;

/**
 * DeAtpAttivita generated by hbm2java
 */
@Entity
@Table(name = "de_atp_attivita", schema = "myportal")
@org.hibernate.annotations.Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class DeAtpAttivita extends AbstractDecodeEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8790544534830465895L;
	private String codAtpAttivita;
	private String descrizione;
	
	public DeAtpAttivita() {
	}

	
	
	@Id
	@Column(name = "cod_atp_attivita", unique = true, nullable = false, length = 8)
	public String getCodAtpAttivita() {
		return this.codAtpAttivita;
	}

	public void setCodAtpAttivita(String codAtpAttivita) {
		this.codAtpAttivita = codAtpAttivita;
	}

	@Column(name = "descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	
}
