package it.eng.myportal.entity.decodifiche;

// default package
// Generated 11-mar-2013 11.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.CacheConcurrencyStrategy;

import it.eng.myportal.entity.AbstractDecodeEntity;

/**
 * DeAtpContratto generated by hbm2java
 */
@Entity
@Table(name = "de_atp_contratto", schema = "myportal")
@org.hibernate.annotations.Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class DeAtpContratto extends AbstractDecodeEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -119990527370288749L;
	private String codAtpContratto;
	private String descrizione;
	private DeAtpContratto padre;
	private Set<DeAtpContratto> figli = new HashSet<DeAtpContratto>(0);

	public DeAtpContratto() {
	}

	@Id
	@Column(name = "cod_atp_contratto", unique = true, nullable = false, length = 8)
	public String getCodAtpContratto() {
		return this.codAtpContratto;
	}

	public void setCodAtpContratto(String codAtpContratto) {
		this.codAtpContratto = codAtpContratto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_padre")
	public DeAtpContratto getPadre() {
		return this.padre;
	}

	public void setPadre(DeAtpContratto padre) {
		this.padre = padre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "padre")
	public Set<DeAtpContratto> getFigli() {
		return this.figli;
	}

	public void setFigli(Set<DeAtpContratto> figli) {
		this.figli = figli;
	}

	@Column(name = "descrizione")
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

}
