package it.eng.myportal.entity.decodifiche;

// default package
// Generated 20-feb-2013 13.47.02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.CacheConcurrencyStrategy;

import it.eng.myportal.entity.AbstractDecodeEntity;

/**
 * DeStatoPratica generated by hbm2java
 */
@Entity
@Table(name = "de_stato_pratica", schema = "myportal")
@org.hibernate.annotations.Cache(usage=CacheConcurrencyStrategy.READ_ONLY) 
public class DeStatoPratica extends AbstractDecodeEntity implements java.io.Serializable {


	private static final long serialVersionUID = 8619742074328019731L;
	private String codStatoPratica;
	private String descrizione;
	

	public DeStatoPratica() {
	}

	public DeStatoPratica(String codStatoPratica, String descrizione, Date dtInizioVal, Date dtFineVal) {
		this.codStatoPratica = codStatoPratica;
		this.descrizione = descrizione;
		
	}

	
	@Id
	@Column(name = "cod_stato_pratica", unique = true, nullable = false, length = 8)
	public String getCodStatoPratica() {
		return this.codStatoPratica;
	}

	public void setCodStatoPratica(String codStatoPratica) {
		this.codStatoPratica = codStatoPratica;
	}

	@Column(name = "descrizione", nullable = false, length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	
	
}
