package it.eng.myportal.entity.decodifiche;

// default package
// Generated 27-feb-2013 11.42.37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import it.eng.myportal.entity.AbstractDecodeEntity;

/**
 * DeTipoQuesito generated by hbm2java
 */
@Entity
@Table(name = "de_tipo_quesito", schema = "myportal")
public class DeTipoQuesito extends AbstractDecodeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codTipoQuesito;
	private String descrizione;
	
	public DeTipoQuesito() {
	}

	

	@Id
	@Column(name = "cod_tipo_quesito", unique = true, nullable = false, length = 8)
	public String getCodTipoQuesito() {
		return this.codTipoQuesito;
	}

	public void setCodTipoQuesito(String codTipoQuesito) {
		this.codTipoQuesito = codTipoQuesito;
	}

	@Column(name = "descrizione", nullable = false, length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	

}
