package it.eng.myportal.entity.decodifiche;

// default package
// Generated 26-feb-2013 16.56.17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import it.eng.myportal.entity.AbstractDecodeEntity;

/**
 * DeTipoPratica generated by hbm2java
 */
@Entity
@Table(name = "de_tipo_pratica", schema = "mycas")
@NamedQueries({
	@NamedQuery(name = "findDeTipoPratica", query = "select new javax.faces.model.SelectItem(c.codTipoPratica,c.descrizione) from DeTipoPratica c where c.codTipoPratica in (:tipiPratica)")})
public class DeTipoPratica extends AbstractDecodeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3741980168439871912L;
	private String codTipoPratica;
	private String descrizione;
	
	public DeTipoPratica() {
	}


	@Id
	@Column(name = "cod_tipo_pratica", unique = true, nullable = false, length = 8)
	public String getCodTipoPratica() {
		return this.codTipoPratica;
	}

	public void setCodTipoPratica(String codTipoPratica) {
		this.codTipoPratica = codTipoPratica;
	}

	@Column(name = "descrizione", nullable = false, length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}



	

}
