package it.eng.myportal.entity.decodifiche;

// default package
// Generated 26-feb-2013 16.56.17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import it.eng.myportal.entity.AbstractDecodeEntity;

/**
 * DeTipoConsulente generated by hbm2java
 */
@Entity
@Table(name = "de_tipo_consulenza", schema = "myportal")
public class DeTipoConsulenza extends AbstractDecodeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codTipoConsulente;
	private String descrizione;

	public DeTipoConsulenza() {
	}

	@Id
	@Column(name = "cod_tipo_consulenza", unique = true, nullable = false, length = 8)
	public String getCodTipoConsulente() {
		return this.codTipoConsulente;
	}

	public void setCodTipoConsulente(String codTipoConsulente) {
		this.codTipoConsulente = codTipoConsulente;
	}

	@Column(name = "descrizione", nullable = false, length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
}
