//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 10:55:38 AM CET 
//

package it.eng.sil.coop.webservices.rdc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="esito">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="codEsito" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="messaggioErrore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "esito" })
@XmlRootElement(name = "risposta_RDC_InviaNotifica")
public class RispostaRDCInviaNotifica {

	@XmlElement(required = true)
	protected RispostaRDCInviaNotifica.Esito esito;

	/**
	 * Gets the value of the esito property.
	 * 
	 * @return possible object is {@link RispostaRDCInviaNotifica.Esito }
	 * 
	 */
	public RispostaRDCInviaNotifica.Esito getEsito() {
		return esito;
	}

	/**
	 * Sets the value of the esito property.
	 * 
	 * @param value
	 *            allowed object is {@link RispostaRDCInviaNotifica.Esito }
	 * 
	 */
	public void setEsito(RispostaRDCInviaNotifica.Esito value) {
		this.esito = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="codEsito" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="messaggioErrore" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "codEsito", "messaggioErrore" })
	public static class Esito {

		@XmlElement(required = true)
		protected String codEsito;
		@XmlElement(required = true)
		protected String messaggioErrore;

		/**
		 * Gets the value of the codEsito property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCodEsito() {
			return codEsito;
		}

		/**
		 * Sets the value of the codEsito property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCodEsito(String value) {
			this.codEsito = value;
		}

		/**
		 * Gets the value of the messaggioErrore property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMessaggioErrore() {
			return messaggioErrore;
		}

		/**
		 * Sets the value of the messaggioErrore property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setMessaggioErrore(String value) {
			this.messaggioErrore = value;
		}

	}

}
