<tr valign="top">
  <td class="etichetta">Anno</td>
  <td class="campo">
    <af:textBox onKeyUp="fieldChanged();" name="annoProtocollo" title="Anno" type="integer" validateOnPost="true" size="4" maxlength="4"/>
  </td>
</tr>

<tr valign="top">
  <td class="etichetta">Numero</td>
  <td class="campo">
    <af:textBox onKeyUp="fieldChanged();" name="numeroProtocollo" title="Numero protocollo" type="integer" validateOnPost="true" size="10" maxlength="100"/>
  </td>
</tr>

<tr valign="top">
  <td class="etichetta">Data</td>
  <td class="campo">
    <af:textBox onKeyUp="fieldChanged();" name="dataProtocollo" title="Data protocollazione" type="date" validateOnPost="true" size="11" maxlength="10"/>
  </td>
</tr>