//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.13 at 11:45:47 AM CEST 
//

package it.eng.sil.pojo.yg.sap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * it.eng.sil.pojo.yg.sap package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Indiceisee_QNAME = new QName("", "indiceisee");
	private final static QName _Specifiche_QNAME = new QName("", "specifiche");
	private final static QName _Codconoscenzainformatica_QNAME = new QName("", "codconoscenzainformatica");
	private final static QName _Annofrequenza_QNAME = new QName("", "annofrequenza");
	private final static QName _Tipocontratto_QNAME = new QName("", "tipocontratto");
	private final static QName _Corsostudio_QNAME = new QName("", "corsostudio");
	private final static QName _Datafineiscrizione_QNAME = new QName("", "datafineiscrizione");
	private final static QName _Codgrado_QNAME = new QName("", "codgrado");
	private final static QName _Identificativosap_QNAME = new QName("", "identificativosap");
	private final static QName _DataFine_QNAME = new QName("", "data_fine");
	private final static QName _Sesso_QNAME = new QName("", "sesso");
	private final static QName _Tipolista_QNAME = new QName("", "tipolista");
	private final static QName _Codregione_QNAME = new QName("", "codregione");
	private final static QName _Codpatenteguida_QNAME = new QName("", "codpatenteguida");
	private final static QName _Dataingresso_QNAME = new QName("", "dataingresso");
	private final static QName _Categoriainquadramento_QNAME = new QName("", "categoriainquadramento");
	private final static QName _Codpatentino_QNAME = new QName("", "codpatentino");
	private final static QName _Disponibilita_QNAME = new QName("", "disponibilita");
	private final static QName _Fax_QNAME = new QName("", "fax");
	private final static QName _Riconosciutoin_QNAME = new QName("", "riconosciutoin");
	private final static QName _Codmodalitalavoro_QNAME = new QName("", "codmodalitalavoro");
	private final static QName _Indirizzo_QNAME = new QName("", "indirizzo");
	private final static QName _Dataiscrizione_QNAME = new QName("", "dataiscrizione");
	private final static QName _Codcomunefrequenza_QNAME = new QName("", "codcomunefrequenza");
	private final static QName _Codstatus_QNAME = new QName("", "codstatus");
	private final static QName _Cognome_QNAME = new QName("", "cognome");
	private final static QName _Titolocorso_QNAME = new QName("", "titolocorso");
	private final static QName _Obbligoformativo_QNAME = new QName("", "obbligoformativo");
	private final static QName _Dataevento_QNAME = new QName("", "dataevento");
	private final static QName _Codstatooccupazionale_QNAME = new QName("", "codstatooccupazionale");
	private final static QName _Numero_QNAME = new QName("", "numero");
	private final static QName _Datorelavoro_QNAME = new QName("", "datorelavoro");
	private final static QName _Codlivelloistruzione_QNAME = new QName("", "codlivelloistruzione");
	private final static QName _Categorieprotette_QNAME = new QName("", "categorieprotette");
	private final static QName _Codprofessione_QNAME = new QName("", "codprofessione");
	private final static QName _Email_QNAME = new QName("", "email");
	private final static QName _Nome_QNAME = new QName("", "nome");
	private final static QName _TitoloProgetto_QNAME = new QName("", "titolo_progetto");
	private final static QName _Codalbo_QNAME = new QName("", "codalbo");
	private final static QName _Denominazioneaziendastage_QNAME = new QName("", "denominazioneaziendastage");
	private final static QName _Validoal_QNAME = new QName("", "validoal");
	private final static QName _Datainizio_QNAME = new QName("", "datainizio");
	private final static QName _DataFinePeriodoFormativo_QNAME = new QName("", "dataFinePeriodoFormativo");
	private final static QName _Codlivelloscritto_QNAME = new QName("", "codlivelloscritto");
	private final static QName _Cap_QNAME = new QName("", "cap");
	private final static QName _Data_QNAME = new QName("", "data");
	private final static QName _Durata_QNAME = new QName("", "durata");
	private final static QName _CodiceEntePromotore_QNAME = new QName("", "codice_ente_promotore");
	private final static QName _Codprovincia_QNAME = new QName("", "codprovincia");
	private final static QName _TipologiaDurata_QNAME = new QName("", "tipologia_durata");
	private final static QName _Lavoratore_QNAME = new QName("", "lavoratore");
	private final static QName _Stage_QNAME = new QName("", "stage");
	private final static QName _AssunzioneLegge68_QNAME = new QName("", "assunzioneLegge68");
	private final static QName _Datamaxdeferimento_QNAME = new QName("", "datamaxdeferimento");
	private final static QName _Anzianita_QNAME = new QName("", "anzianita");
	private final static QName _Votazione_QNAME = new QName("", "votazione");
	private final static QName _Descrizione_QNAME = new QName("", "descrizione");
	private final static QName _Datadinascita_QNAME = new QName("", "datadinascita");
	private final static QName _Localita_QNAME = new QName("", "localita");
	private final static QName _Codcomune_QNAME = new QName("", "codcomune");
	private final static QName _Tipovariazione_QNAME = new QName("", "tipovariazione");
	private final static QName _Descrizionecorsostudio_QNAME = new QName("", "descrizionecorsostudio");
	private final static QName _TitoloDenominazione_QNAME = new QName("", "titolo_denominazione");
	private final static QName _Cellulare_QNAME = new QName("", "cellulare");
	private final static QName _Compiti_QNAME = new QName("", "compiti");
	private final static QName _Codicefiscale_QNAME = new QName("", "codicefiscale");
	private final static QName _Indirizzoazienda_QNAME = new QName("", "indirizzoazienda");
	private final static QName _Datafine_QNAME = new QName("", "datafine");
	private final static QName _Codcittadinanza_QNAME = new QName("", "codcittadinanza");
	private final static QName _Annotermine_QNAME = new QName("", "annotermine");
	private final static QName _Certificazioniattestati_QNAME = new QName("", "certificazioniattestati");
	private final static QName _TipoAttivita_QNAME = new QName("", "tipo_attivita");
	private final static QName _Telefono_QNAME = new QName("", "telefono");
	private final static QName _Categoria297_QNAME = new QName("", "categoria297");
	private final static QName _Tipoingresso_QNAME = new QName("", "tipoingresso");
	private final static QName _Codlingua_QNAME = new QName("", "codlingua");
	private final static QName _Codtipodocumento_QNAME = new QName("", "codtipodocumento");
	private final static QName _Ente_QNAME = new QName("", "ente");
	private final static QName _Specificheinformatica_QNAME = new QName("", "specificheinformatica");
	private final static QName _Codlivelloparlato_QNAME = new QName("", "codlivelloparlato");
	private final static QName _Dataultimoagg_QNAME = new QName("", "dataultimoagg");
	private final static QName _Annofrequentato_QNAME = new QName("", "annofrequentato");
	private final static QName _Datanascita_QNAME = new QName("", "datanascita");
	private final static QName _Codtipologiadurata_QNAME = new QName("", "codtipologiadurata");
	private final static QName _Codiceentetit_QNAME = new QName("", "codiceentetit");
	private final static QName _DataProposta_QNAME = new QName("", "data_proposta");
	private final static QName _Codlivelloletto_QNAME = new QName("", "codlivelloletto");
	private final static QName _Codateco_QNAME = new QName("", "codateco");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * it.eng.sil.pojo.yg.sap
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Permessodisoggiorno }
	 * 
	 */
	public Permessodisoggiorno createPermessodisoggiorno() {
		return new Permessodisoggiorno();
	}

	/**
	 * Create an instance of {@link Titolostudio }
	 * 
	 */
	public Titolostudio createTitolostudio() {
		return new Titolostudio();
	}

	/**
	 * Create an instance of {@link Altreinformazioni }
	 * 
	 */
	public Altreinformazioni createAltreinformazioni() {
		return new Altreinformazioni();
	}

	/**
	 * Create an instance of {@link Domicilio }
	 * 
	 */
	public Domicilio createDomicilio() {
		return new Domicilio();
	}

	/**
	 * Create an instance of {@link Statoinanagrafe }
	 * 
	 */
	public Statoinanagrafe createStatoinanagrafe() {
		return new Statoinanagrafe();
	}

	/**
	 * Create an instance of {@link Modalitalavoro }
	 * 
	 */
	public Modalitalavoro createModalitalavoro() {
		return new Modalitalavoro();
	}

	/**
	 * Create an instance of {@link PoliticheAttive }
	 * 
	 */
	public PoliticheAttive createPoliticheAttive() {
		return new PoliticheAttive();
	}

	/**
	 * Create an instance of {@link LavoratoreType }
	 * 
	 */
	public LavoratoreType createLavoratoreType() {
		return new LavoratoreType();
	}

	/**
	 * Create an instance of {@link Utilizzatrice }
	 * 
	 */
	public Utilizzatrice createUtilizzatrice() {
		return new Utilizzatrice();
	}

	/**
	 * Create an instance of {@link Allegato }
	 * 
	 */
	public Allegato createAllegato() {
		return new Allegato();
	}

	/**
	 * Create an instance of {@link LivelliistruzioneLst }
	 * 
	 */
	public LivelliistruzioneLst createLivelliistruzioneLst() {
		return new LivelliistruzioneLst();
	}

	/**
	 * Create an instance of {@link Listespeciali }
	 * 
	 */
	public Listespeciali createListespeciali() {
		return new Listespeciali();
	}

	/**
	 * Create an instance of {@link Esperienzalavoro }
	 * 
	 */
	public Esperienzalavoro createEsperienzalavoro() {
		return new Esperienzalavoro();
	}

	/**
	 * Create an instance of {@link ConoscenzeinformaticheLst }
	 * 
	 */
	public ConoscenzeinformaticheLst createConoscenzeinformaticheLst() {
		return new ConoscenzeinformaticheLst();
	}

	/**
	 * Create an instance of {@link TitolistudioLst }
	 * 
	 */
	public TitolistudioLst createTitolistudioLst() {
		return new TitolistudioLst();
	}

	/**
	 * Create an instance of {@link Tiporapporto }
	 * 
	 */
	public Tiporapporto createTiporapporto() {
		return new Tiporapporto();
	}

	/**
	 * Create an instance of {@link Residenza }
	 * 
	 */
	public Residenza createResidenza() {
		return new Residenza();
	}

	/**
	 * Create an instance of {@link Conoscenzeinformatiche }
	 * 
	 */
	public Conoscenzeinformatiche createConoscenzeinformatiche() {
		return new Conoscenzeinformatiche();
	}

	/**
	 * Create an instance of {@link EsperienzelavoroLst }
	 * 
	 */
	public EsperienzelavoroLst createEsperienzelavoroLst() {
		return new EsperienzelavoroLst();
	}

	/**
	 * Create an instance of {@link FormazioneprofessionaleLst }
	 * 
	 */
	public FormazioneprofessionaleLst createFormazioneprofessionaleLst() {
		return new FormazioneprofessionaleLst();
	}

	/**
	 * Create an instance of {@link Periodidisoccupazione }
	 * 
	 */
	public Periodidisoccupazione createPeriodidisoccupazione() {
		return new Periodidisoccupazione();
	}

	/**
	 * Create an instance of {@link Datistranieri }
	 * 
	 */
	public Datistranieri createDatistranieri() {
		return new Datistranieri();
	}

	/**
	 * Create an instance of {@link Datipersonali }
	 * 
	 */
	public Datipersonali createDatipersonali() {
		return new Datipersonali();
	}

	/**
	 * Create an instance of {@link Formazioneprofessionale }
	 * 
	 */
	public Formazioneprofessionale createFormazioneprofessionale() {
		return new Formazioneprofessionale();
	}

	/**
	 * Create an instance of {@link Azienda }
	 * 
	 */
	public Azienda createAzienda() {
		return new Azienda();
	}

	/**
	 * Create an instance of {@link LinguestraniereLst }
	 * 
	 */
	public LinguestraniereLst createLinguestraniereLst() {
		return new LinguestraniereLst();
	}

	/**
	 * Create an instance of {@link Assolvimentoistruzione }
	 * 
	 */
	public Assolvimentoistruzione createAssolvimentoistruzione() {
		return new Assolvimentoistruzione();
	}

	/**
	 * Create an instance of {@link Daticurriculari }
	 * 
	 */
	public Daticurriculari createDaticurriculari() {
		return new Daticurriculari();
	}

	/**
	 * Create an instance of {@link AltreinformazioniLst }
	 * 
	 */
	public AltreinformazioniLst createAltreinformazioniLst() {
		return new AltreinformazioniLst();
	}

	/**
	 * Create an instance of {@link ListespecialiLst }
	 * 
	 */
	public ListespecialiLst createListespecialiLst() {
		return new ListespecialiLst();
	}

	/**
	 * Create an instance of {@link Datiinvio }
	 * 
	 */
	public Datiinvio createDatiinvio() {
		return new Datiinvio();
	}

	/**
	 * Create an instance of {@link Datiamministrativi }
	 * 
	 */
	public Datiamministrativi createDatiamministrativi() {
		return new Datiamministrativi();
	}

	/**
	 * Create an instance of {@link Conoscenzainformatica }
	 * 
	 */
	public Conoscenzainformatica createConoscenzainformatica() {
		return new Conoscenzainformatica();
	}

	/**
	 * Create an instance of {@link Linguastraniera }
	 * 
	 */
	public Linguastraniera createLinguastraniera() {
		return new Linguastraniera();
	}

	/**
	 * Create an instance of {@link Recapiti }
	 * 
	 */
	public Recapiti createRecapiti() {
		return new Recapiti();
	}

	/**
	 * Create an instance of {@link Datianagrafici }
	 * 
	 */
	public Datianagrafici createDatianagrafici() {
		return new Datianagrafici();
	}

	/**
	 * Create an instance of {@link Ulterioriinformazioni }
	 * 
	 */
	public Ulterioriinformazioni createUlterioriinformazioni() {
		return new Ulterioriinformazioni();
	}

	/**
	 * Create an instance of {@link IstruzioneLst }
	 * 
	 */
	public IstruzioneLst createIstruzioneLst() {
		return new IstruzioneLst();
	}

	/**
	 * Create an instance of {@link Luogolavoro }
	 * 
	 */
	public Luogolavoro createLuogolavoro() {
		return new Luogolavoro();
	}

	/**
	 * Create an instance of {@link Altrenotizie }
	 * 
	 */
	public Altrenotizie createAltrenotizie() {
		return new Altrenotizie();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "indiceisee")
	public JAXBElement<String> createIndiceisee(String value) {
		return new JAXBElement<String>(_Indiceisee_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "specifiche")
	public JAXBElement<String> createSpecifiche(String value) {
		return new JAXBElement<String>(_Specifiche_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codconoscenzainformatica")
	public JAXBElement<String> createCodconoscenzainformatica(String value) {
		return new JAXBElement<String>(_Codconoscenzainformatica_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "annofrequenza")
	public JAXBElement<String> createAnnofrequenza(String value) {
		return new JAXBElement<String>(_Annofrequenza_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipocontratto")
	public JAXBElement<String> createTipocontratto(String value) {
		return new JAXBElement<String>(_Tipocontratto_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "corsostudio")
	public JAXBElement<String> createCorsostudio(String value) {
		return new JAXBElement<String>(_Corsostudio_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "datafineiscrizione")
	public JAXBElement<XMLGregorianCalendar> createDatafineiscrizione(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Datafineiscrizione_QNAME, XMLGregorianCalendar.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codgrado")
	public JAXBElement<String> createCodgrado(String value) {
		return new JAXBElement<String>(_Codgrado_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "identificativosap")
	public JAXBElement<String> createIdentificativosap(String value) {
		return new JAXBElement<String>(_Identificativosap_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "data_fine")
	public JAXBElement<XMLGregorianCalendar> createDataFine(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_DataFine_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "sesso")
	public JAXBElement<String> createSesso(String value) {
		return new JAXBElement<String>(_Sesso_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipolista")
	public JAXBElement<String> createTipolista(String value) {
		return new JAXBElement<String>(_Tipolista_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codregione")
	public JAXBElement<String> createCodregione(String value) {
		return new JAXBElement<String>(_Codregione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codpatenteguida")
	public JAXBElement<String> createCodpatenteguida(String value) {
		return new JAXBElement<String>(_Codpatenteguida_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "dataingresso")
	public JAXBElement<XMLGregorianCalendar> createDataingresso(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Dataingresso_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "categoriainquadramento")
	public JAXBElement<String> createCategoriainquadramento(String value) {
		return new JAXBElement<String>(_Categoriainquadramento_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codpatentino")
	public JAXBElement<String> createCodpatentino(String value) {
		return new JAXBElement<String>(_Codpatentino_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "disponibilita")
	public JAXBElement<XMLGregorianCalendar> createDisponibilita(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Disponibilita_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "fax")
	public JAXBElement<String> createFax(String value) {
		return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "riconosciutoin")
	public JAXBElement<String> createRiconosciutoin(String value) {
		return new JAXBElement<String>(_Riconosciutoin_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codmodalitalavoro")
	public JAXBElement<String> createCodmodalitalavoro(String value) {
		return new JAXBElement<String>(_Codmodalitalavoro_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "indirizzo")
	public JAXBElement<String> createIndirizzo(String value) {
		return new JAXBElement<String>(_Indirizzo_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "dataiscrizione")
	public JAXBElement<XMLGregorianCalendar> createDataiscrizione(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Dataiscrizione_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codcomunefrequenza")
	public JAXBElement<String> createCodcomunefrequenza(String value) {
		return new JAXBElement<String>(_Codcomunefrequenza_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codstatus")
	public JAXBElement<String> createCodstatus(String value) {
		return new JAXBElement<String>(_Codstatus_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "cognome")
	public JAXBElement<String> createCognome(String value) {
		return new JAXBElement<String>(_Cognome_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "titolocorso")
	public JAXBElement<String> createTitolocorso(String value) {
		return new JAXBElement<String>(_Titolocorso_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "obbligoformativo")
	public JAXBElement<String> createObbligoformativo(String value) {
		return new JAXBElement<String>(_Obbligoformativo_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "dataevento")
	public JAXBElement<XMLGregorianCalendar> createDataevento(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Dataevento_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codstatooccupazionale")
	public JAXBElement<String> createCodstatooccupazionale(String value) {
		return new JAXBElement<String>(_Codstatooccupazionale_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "numero")
	public JAXBElement<String> createNumero(String value) {
		return new JAXBElement<String>(_Numero_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "datorelavoro")
	public JAXBElement<String> createDatorelavoro(String value) {
		return new JAXBElement<String>(_Datorelavoro_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codlivelloistruzione")
	public JAXBElement<String> createCodlivelloistruzione(String value) {
		return new JAXBElement<String>(_Codlivelloistruzione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "categorieprotette")
	public JAXBElement<String> createCategorieprotette(String value) {
		return new JAXBElement<String>(_Categorieprotette_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codprofessione")
	public JAXBElement<String> createCodprofessione(String value) {
		return new JAXBElement<String>(_Codprofessione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "email")
	public JAXBElement<String> createEmail(String value) {
		return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "nome")
	public JAXBElement<String> createNome(String value) {
		return new JAXBElement<String>(_Nome_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "titolo_progetto")
	public JAXBElement<String> createTitoloProgetto(String value) {
		return new JAXBElement<String>(_TitoloProgetto_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codalbo")
	public JAXBElement<String> createCodalbo(String value) {
		return new JAXBElement<String>(_Codalbo_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "denominazioneaziendastage")
	public JAXBElement<String> createDenominazioneaziendastage(String value) {
		return new JAXBElement<String>(_Denominazioneaziendastage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "validoal")
	public JAXBElement<XMLGregorianCalendar> createValidoal(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Validoal_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "datainizio")
	public JAXBElement<XMLGregorianCalendar> createDatainizio(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Datainizio_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "dataFinePeriodoFormativo")
	public JAXBElement<XMLGregorianCalendar> createDataFinePeriodoFormativo(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_DataFinePeriodoFormativo_QNAME, XMLGregorianCalendar.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codlivelloscritto")
	public JAXBElement<String> createCodlivelloscritto(String value) {
		return new JAXBElement<String>(_Codlivelloscritto_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "cap")
	public JAXBElement<String> createCap(String value) {
		return new JAXBElement<String>(_Cap_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "data")
	public JAXBElement<XMLGregorianCalendar> createData(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Data_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "durata")
	public JAXBElement<Integer> createDurata(Integer value) {
		return new JAXBElement<Integer>(_Durata_QNAME, Integer.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codice_ente_promotore")
	public JAXBElement<String> createCodiceEntePromotore(String value) {
		return new JAXBElement<String>(_CodiceEntePromotore_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codprovincia")
	public JAXBElement<String> createCodprovincia(String value) {
		return new JAXBElement<String>(_Codprovincia_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipologia_durata")
	public JAXBElement<String> createTipologiaDurata(String value) {
		return new JAXBElement<String>(_TipologiaDurata_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link LavoratoreType }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "lavoratore")
	public JAXBElement<LavoratoreType> createLavoratore(LavoratoreType value) {
		return new JAXBElement<LavoratoreType>(_Lavoratore_QNAME, LavoratoreType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "stage")
	public JAXBElement<String> createStage(String value) {
		return new JAXBElement<String>(_Stage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link SiNo }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "assunzioneLegge68")
	public JAXBElement<SiNo> createAssunzioneLegge68(SiNo value) {
		return new JAXBElement<SiNo>(_AssunzioneLegge68_QNAME, SiNo.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "datamaxdeferimento")
	public JAXBElement<XMLGregorianCalendar> createDatamaxdeferimento(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Datamaxdeferimento_QNAME, XMLGregorianCalendar.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "anzianita")
	public JAXBElement<String> createAnzianita(String value) {
		return new JAXBElement<String>(_Anzianita_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "votazione")
	public JAXBElement<String> createVotazione(String value) {
		return new JAXBElement<String>(_Votazione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "descrizione")
	public JAXBElement<String> createDescrizione(String value) {
		return new JAXBElement<String>(_Descrizione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "datadinascita")
	public JAXBElement<XMLGregorianCalendar> createDatadinascita(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Datadinascita_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "localita")
	public JAXBElement<String> createLocalita(String value) {
		return new JAXBElement<String>(_Localita_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codcomune")
	public JAXBElement<String> createCodcomune(String value) {
		return new JAXBElement<String>(_Codcomune_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipovariazione")
	public JAXBElement<String> createTipovariazione(String value) {
		return new JAXBElement<String>(_Tipovariazione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "descrizionecorsostudio")
	public JAXBElement<String> createDescrizionecorsostudio(String value) {
		return new JAXBElement<String>(_Descrizionecorsostudio_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "titolo_denominazione")
	public JAXBElement<String> createTitoloDenominazione(String value) {
		return new JAXBElement<String>(_TitoloDenominazione_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "cellulare")
	public JAXBElement<String> createCellulare(String value) {
		return new JAXBElement<String>(_Cellulare_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "compiti")
	public JAXBElement<String> createCompiti(String value) {
		return new JAXBElement<String>(_Compiti_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codicefiscale")
	public JAXBElement<String> createCodicefiscale(String value) {
		return new JAXBElement<String>(_Codicefiscale_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "indirizzoazienda")
	public JAXBElement<String> createIndirizzoazienda(String value) {
		return new JAXBElement<String>(_Indirizzoazienda_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "datafine")
	public JAXBElement<XMLGregorianCalendar> createDatafine(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Datafine_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codcittadinanza")
	public JAXBElement<String> createCodcittadinanza(String value) {
		return new JAXBElement<String>(_Codcittadinanza_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "annotermine")
	public JAXBElement<String> createAnnotermine(String value) {
		return new JAXBElement<String>(_Annotermine_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "certificazioniattestati")
	public JAXBElement<String> createCertificazioniattestati(String value) {
		return new JAXBElement<String>(_Certificazioniattestati_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipo_attivita")
	public JAXBElement<String> createTipoAttivita(String value) {
		return new JAXBElement<String>(_TipoAttivita_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "telefono")
	public JAXBElement<String> createTelefono(String value) {
		return new JAXBElement<String>(_Telefono_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "categoria297")
	public JAXBElement<String> createCategoria297(String value) {
		return new JAXBElement<String>(_Categoria297_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "tipoingresso")
	public JAXBElement<String> createTipoingresso(String value) {
		return new JAXBElement<String>(_Tipoingresso_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codlingua")
	public JAXBElement<String> createCodlingua(String value) {
		return new JAXBElement<String>(_Codlingua_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codtipodocumento")
	public JAXBElement<String> createCodtipodocumento(String value) {
		return new JAXBElement<String>(_Codtipodocumento_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ente")
	public JAXBElement<String> createEnte(String value) {
		return new JAXBElement<String>(_Ente_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "specificheinformatica")
	public JAXBElement<String> createSpecificheinformatica(String value) {
		return new JAXBElement<String>(_Specificheinformatica_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codlivelloparlato")
	public JAXBElement<String> createCodlivelloparlato(String value) {
		return new JAXBElement<String>(_Codlivelloparlato_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "dataultimoagg")
	public JAXBElement<XMLGregorianCalendar> createDataultimoagg(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Dataultimoagg_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "annofrequentato")
	public JAXBElement<String> createAnnofrequentato(String value) {
		return new JAXBElement<String>(_Annofrequentato_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "datanascita")
	public JAXBElement<XMLGregorianCalendar> createDatanascita(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_Datanascita_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codtipologiadurata")
	public JAXBElement<String> createCodtipologiadurata(String value) {
		return new JAXBElement<String>(_Codtipologiadurata_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codiceentetit")
	public JAXBElement<String> createCodiceentetit(String value) {
		return new JAXBElement<String>(_Codiceentetit_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "data_proposta")
	public JAXBElement<XMLGregorianCalendar> createDataProposta(XMLGregorianCalendar value) {
		return new JAXBElement<XMLGregorianCalendar>(_DataProposta_QNAME, XMLGregorianCalendar.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codlivelloletto")
	public JAXBElement<String> createCodlivelloletto(String value) {
		return new JAXBElement<String>(_Codlivelloletto_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "codateco")
	public JAXBElement<String> createCodateco(String value) {
		return new JAXBElement<String>(_Codateco_QNAME, String.class, null, value);
	}

}
