//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.06 at 04:10:40 PM CEST 
//

package it.eng.sil.coop.webservices.coapadesioneGet.pojo.yg.statoAdesioneYg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodiceFiscale" type="{}CodiceFiscale_Type"/>
 *         &lt;element name="RegioneAdesione" type="{}RegioneAdesione_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "codiceFiscale", "regioneAdesione" })
@XmlRootElement(name = "DatiStatoAdesione")
public class DatiStatoAdesione {

	@XmlElement(name = "CodiceFiscale", required = true)
	protected String codiceFiscale;
	@XmlElement(name = "RegioneAdesione", required = true)
	protected String regioneAdesione;

	/**
	 * Gets the value of the codiceFiscale property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodiceFiscale() {
		return codiceFiscale;
	}

	/**
	 * Sets the value of the codiceFiscale property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodiceFiscale(String value) {
		this.codiceFiscale = value;
	}

	/**
	 * Gets the value of the regioneAdesione property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRegioneAdesione() {
		return regioneAdesione;
	}

	/**
	 * Sets the value of the regioneAdesione property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRegioneAdesione(String value) {
		this.regioneAdesione = value;
	}

}
