<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="InformationDelivery_ConferimentoDID" targetNamespace="http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0" xmlns:db="http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0" xmlns:tns="http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://nsr.sil.eng.it/DataModels/InformationDelivery/NotificaAppuntamentoEsito/1.0" schemaLocation="../../WEB-INF/xsd/agenda/appuntamento/coapAnpal/NotificaEsitoAppuntamento-1.0.xsd"/>
		</schema>
	</wsdl:types>


	
	<wsdl:message name="notificaRequest">
		<wsdl:part element="db:RichiestaNotificaEsito" name="richiesta" />
	</wsdl:message>
	<wsdl:message name="notificaResponse">
		<wsdl:part element="db:RispostaNotificaEsito" name="risposta" />
	</wsdl:message>
	<wsdl:portType name="NotificaEsitoAppuntamentoType">
		<wsdl:operation name="notifica">
			<wsdl:input message="tns:notificaRequest" />
			<wsdl:output message="tns:notificaResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="NotificaEsitoAppuntamentoSOAP"
		type="tns:NotificaEsitoAppuntamentoType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="notifica">
			<soap:operation
				soapAction="http://soap.nsr.sil.eng.it/NotificaEsitoAppuntamento/notifica" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="NotificaEsitoAppuntamentoService">
		<wsdl:port binding="tns:NotificaEsitoAppuntamentoSOAP"
			name="NotificaEsitoAppuntamentoPort">
			<soap:address location="http://soap.nsr.sil.eng.it/NotificaEsitoAppuntamento" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
