//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.10 at 03:35:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pattoonlinenew.webservices.coop.sil.eng.it/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.eng.sil.coop.webservices.xsd.pattoonlinenew;
