<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="pattoonline" targetNamespace="http://pattoonline.ws.myportal.eng.it/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://pattoonline.ws.myportal.eng.it/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types><schema xmlns="http://www.w3.org/2001/XMLSchema"><import namespace="http://pattoonline.ws.myportal.eng.it/" schemaLocation="../xsd/ptonline/ptonline.xsd"/></schema>
	</wsdl:types>
	
	<!--  message -->
	<wsdl:message name="InvioPatto">
		<wsdl:part element="tns:InvioPatto" name="richiesta"/>
	</wsdl:message>
	<wsdl:message name="InvioPattoResponse">
		<wsdl:part element="tns:InvioPattoResponse" name="risposta"/>
	</wsdl:message>
	<wsdl:message name="RichiestaPatto">
		<wsdl:part element="tns:RichiestaPatto" name="richiesta"/>
	</wsdl:message>
	<wsdl:message name="RichiestaPattoResponse">
		<wsdl:part element="tns:RichiestaPattoResponse" name="risposta"/>
	</wsdl:message>
	
	<!-- port -->
	<wsdl:portType name="GestionePattoOnline">
		<wsdl:operation name="InvioPatto">
			<wsdl:input message="tns:InvioPatto" name="InvioPatto"></wsdl:input>
			<wsdl:output message="tns:InvioPattoResponse" name="InvioPattoResponse"></wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="RichiestaPatto">
			<wsdl:input message="tns:RichiestaPatto" name="RichiestaPatto"></wsdl:input>
			<wsdl:output message="tns:RichiestaPattoResponse" name="RichiestaPattoResponse"></wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	
	<!-- Binding -->
	<wsdl:binding name="PattoOnlineSoapBinding" type="tns:GestionePattoOnline">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="InvioPatto">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input name="InvioPatto">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="InvioPattoResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="RichiestaPatto">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input name="RichiestaPatto">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="RichiestaPattoResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<!-- service -->
	<wsdl:service name="PattoOnline">
		<wsdl:port binding="tns:PattoOnlineSoapBinding" name="GestionePattoPort">
			<soap:address location="http://localhost:20000/MyPortal/pattoonline"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>