//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.18 at 03:54:43 PM CET 
//

package it.eng.sil.coop.bean.blen.input.ricerca;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for IstruzioneFormazione element declaration.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="IstruzioneFormazione">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}titolostudio" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}idalbo" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}Lingua" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}conoscenzeinformatiche" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}altrecapacita" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}trasferte" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}idpatenteguida" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}idmezzitrasporto" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}idpatentino" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://servizi.lavoro.gov.it/vacancy}ulteriorirequisiti" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "titolostudio", "idalbo", "lingua", "conoscenzeinformatiche", "altrecapacita",
		"trasferte", "idpatenteguida", "idmezzitrasporto", "idpatentino", "ulteriorirequisiti" })
@XmlRootElement(name = "IstruzioneFormazione")
public class IstruzioneFormazione {

	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy", required = true)
	protected List<Titolostudio> titolostudio;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy")
	protected String idalbo;
	@XmlElement(name = "Lingua", namespace = "http://servizi.lavoro.gov.it/vacancy", required = true)
	protected List<Lingua> lingua;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy")
	protected String conoscenzeinformatiche;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy")
	protected String altrecapacita;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy")
	protected SiNo trasferte;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy", required = true)
	protected List<String> idpatenteguida;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy")
	protected SiNo idmezzitrasporto;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy", required = true)
	protected List<String> idpatentino;
	@XmlElement(namespace = "http://servizi.lavoro.gov.it/vacancy")
	protected String ulteriorirequisiti;

	/**
	 * Gets the value of the titolostudio property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the titolostudio property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTitolostudio().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Titolostudio }
	 * 
	 * 
	 */
	public List<Titolostudio> getTitolostudio() {
		if (titolostudio == null) {
			titolostudio = new ArrayList<Titolostudio>();
		}
		return this.titolostudio;
	}

	/**
	 * Gets the value of the idalbo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdalbo() {
		return idalbo;
	}

	/**
	 * Sets the value of the idalbo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdalbo(String value) {
		this.idalbo = value;
	}

	/**
	 * Gets the value of the lingua property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the lingua property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLingua().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Lingua }
	 * 
	 * 
	 */
	public List<Lingua> getLingua() {
		if (lingua == null) {
			lingua = new ArrayList<Lingua>();
		}
		return this.lingua;
	}

	/**
	 * Gets the value of the conoscenzeinformatiche property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConoscenzeinformatiche() {
		return conoscenzeinformatiche;
	}

	/**
	 * Sets the value of the conoscenzeinformatiche property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConoscenzeinformatiche(String value) {
		this.conoscenzeinformatiche = value;
	}

	/**
	 * Gets the value of the altrecapacita property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAltrecapacita() {
		return altrecapacita;
	}

	/**
	 * Sets the value of the altrecapacita property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAltrecapacita(String value) {
		this.altrecapacita = value;
	}

	/**
	 * Gets the value of the trasferte property.
	 * 
	 * @return possible object is {@link SiNo }
	 * 
	 */
	public SiNo getTrasferte() {
		return trasferte;
	}

	/**
	 * Sets the value of the trasferte property.
	 * 
	 * @param value
	 *            allowed object is {@link SiNo }
	 * 
	 */
	public void setTrasferte(SiNo value) {
		this.trasferte = value;
	}

	/**
	 * Gets the value of the idpatenteguida property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the idpatenteguida property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getIdpatenteguida().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getIdpatenteguida() {
		if (idpatenteguida == null) {
			idpatenteguida = new ArrayList<String>();
		}
		return this.idpatenteguida;
	}

	/**
	 * Gets the value of the idmezzitrasporto property.
	 * 
	 * @return possible object is {@link SiNo }
	 * 
	 */
	public SiNo getIdmezzitrasporto() {
		return idmezzitrasporto;
	}

	/**
	 * Sets the value of the idmezzitrasporto property.
	 * 
	 * @param value
	 *            allowed object is {@link SiNo }
	 * 
	 */
	public void setIdmezzitrasporto(SiNo value) {
		this.idmezzitrasporto = value;
	}

	/**
	 * Gets the value of the idpatentino property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the idpatentino property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getIdpatentino().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getIdpatentino() {
		if (idpatentino == null) {
			idpatentino = new ArrayList<String>();
		}
		return this.idpatentino;
	}

	/**
	 * Gets the value of the ulteriorirequisiti property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUlteriorirequisiti() {
		return ulteriorirequisiti;
	}

	/**
	 * Sets the value of the ulteriorirequisiti property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUlteriorirequisiti(String value) {
		this.ulteriorirequisiti = value;
	}

}
