<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="InformationDelivery_VerificaRapportoLavoroAttivo" targetNamespace="http://mlps.gov.it/Services/InformationDelivery/VerificaRapportoLavoroAttivo/3.0" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://mlps.gov.it/DataModels/InformationDelivery/VerificaRapportoLavoroAttivo/3.0" xmlns:WL5G3N2="http://mlps.gov.it/Services/InformationDelivery/VerificaRapportoLavoroAttivo/3.0" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:db="http://mlps.gov.it/DataModels/InformationDelivery/VerificaRapportoLavoroAttivo/3.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://mlps.gov.it/Services/InformationDelivery/VerificaRapportoLavoroAttivo/3.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
      <import namespace="http://mlps.gov.it/DataModels/InformationDelivery/VerificaRapportoLavoroAttivo/3.0" schemaLocation="XS_ID_VerificaRapportoLavoroAttivo_3.0.xsd"/>
    </schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="GetRapportoLavoroAttivo_Input_msg">
    <WL5G3N0:part name="GetRapportoLavoroAttivo_Input_msg" element="WL5G3N1:GetRapportoLavoroAttivo_Input"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="GetRapportoLavoroAttivo_Output_msg">
    <WL5G3N0:part name="GetRapportoLavoroAttivo_Output_msg" element="WL5G3N1:GetRapportoLavoroAttivo_Output"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="VerificaRapportoLavoroAttivo_PortType">
    <WL5G3N0:operation name="getRapportiAttivi">
      <WL5G3N0:input message="WL5G3N2:GetRapportoLavoroAttivo_Input_msg"/>
      <WL5G3N0:output message="WL5G3N2:GetRapportoLavoroAttivo_Output_msg"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="VerificaRapportoLavoroAttivo_Binding" type="WL5G3N2:VerificaRapportoLavoroAttivo_PortType">
    <WL5G3N3:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <WL5G3N0:operation name="getRapportiAttivi">
      <WL5G3N3:operation soapAction="http://mlps.gov.it/DataModels/InformationDelivery/VerificaRapportoLavoroAttivo/3.0/getRapportiAttivi"/>
      <WL5G3N0:input>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="VerificaRapportoLavoroAttivo_BindingQSService">
    <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
    <WL5G3N0:port name="VerificaRapportoLavoroAttivo_BindingQSPort" binding="WL5G3N2:VerificaRapportoLavoroAttivo_Binding">
      <WL5G3N3:address location="https://pdwstest.lavoro.gov.it/PortaApplicativaWCF/PortaApplicativaSVC.svc"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>