//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.13 at 10:02:25 AM CET 
//


package it.eng.myportal.youthGuarantee.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}codlivelloistruzione"/>
 *         &lt;element ref="{}corsostudio" minOccurs="0"/>
 *         &lt;element ref="{}descrizionecorsostudio" minOccurs="0"/>
 *         &lt;element ref="{}codcomunefrequenza" minOccurs="0"/>
 *         &lt;element ref="{}riconosciutoin" minOccurs="0"/>
 *         &lt;element ref="{}votazione" minOccurs="0"/>
 *         &lt;element ref="{}annotermine" minOccurs="0"/>
 *         &lt;element ref="{}annofrequentato" minOccurs="0"/>
 *         &lt;element ref="{}annofrequenza" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codlivelloistruzione",
    "corsostudio",
    "descrizionecorsostudio",
    "codcomunefrequenza",
    "riconosciutoin",
    "votazione",
    "annotermine",
    "annofrequentato",
    "annofrequenza"
})
@XmlRootElement(name = "titolostudio")
public class Titolostudio {

    @XmlElement(required = true)
    protected String codlivelloistruzione;
    protected String corsostudio;
    protected String descrizionecorsostudio;
    protected String codcomunefrequenza;
    protected String riconosciutoin;
    protected String votazione;
    protected String annotermine;
    protected String annofrequentato;
    protected String annofrequenza;

    /**
     * Gets the value of the codlivelloistruzione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodlivelloistruzione() {
        return codlivelloistruzione;
    }

    /**
     * Sets the value of the codlivelloistruzione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodlivelloistruzione(String value) {
        this.codlivelloistruzione = value;
    }

    /**
     * Gets the value of the corsostudio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorsostudio() {
        return corsostudio;
    }

    /**
     * Sets the value of the corsostudio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorsostudio(String value) {
        this.corsostudio = value;
    }

    /**
     * Gets the value of the descrizionecorsostudio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizionecorsostudio() {
        return descrizionecorsostudio;
    }

    /**
     * Sets the value of the descrizionecorsostudio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizionecorsostudio(String value) {
        this.descrizionecorsostudio = value;
    }

    /**
     * Gets the value of the codcomunefrequenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodcomunefrequenza() {
        return codcomunefrequenza;
    }

    /**
     * Sets the value of the codcomunefrequenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodcomunefrequenza(String value) {
        this.codcomunefrequenza = value;
    }

    /**
     * Gets the value of the riconosciutoin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiconosciutoin() {
        return riconosciutoin;
    }

    /**
     * Sets the value of the riconosciutoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiconosciutoin(String value) {
        this.riconosciutoin = value;
    }

    /**
     * Gets the value of the votazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVotazione() {
        return votazione;
    }

    /**
     * Sets the value of the votazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVotazione(String value) {
        this.votazione = value;
    }

    /**
     * Gets the value of the annotermine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotermine() {
        return annotermine;
    }

    /**
     * Sets the value of the annotermine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotermine(String value) {
        this.annotermine = value;
    }

    /**
     * Gets the value of the annofrequentato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnofrequentato() {
        return annofrequentato;
    }

    /**
     * Sets the value of the annofrequentato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnofrequentato(String value) {
        this.annofrequentato = value;
    }

    /**
     * Gets the value of the annofrequenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnofrequenza() {
        return annofrequenza;
    }

    /**
     * Sets the value of the annofrequenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnofrequenza(String value) {
        this.annofrequenza = value;
    }

}
