//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 03:51:06 PM CET 
//

package it.eng.sil.coop.webservices.siferPartecipanteGG.input;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * https.sifer_regione_emilia_romagna_it.webservice.garanziagiovani.partecipantegaranziagiovani package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * https.sifer_regione_emilia_romagna_it.webservice.garanziagiovani.partecipantegaranziagiovani
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani }
	 * 
	 */
	public PartecipanteGaranziaGiovani createPartecipanteGaranziaGiovani() {
		return new PartecipanteGaranziaGiovani();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.ComunicazioniObbligatorie }
	 * 
	 */
	public PartecipanteGaranziaGiovani.ComunicazioniObbligatorie createPartecipanteGaranziaGiovaniComunicazioniObbligatorie() {
		return new PartecipanteGaranziaGiovani.ComunicazioniObbligatorie();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.Patti }
	 * 
	 */
	public PartecipanteGaranziaGiovani.Patti createPartecipanteGaranziaGiovaniPatti() {
		return new PartecipanteGaranziaGiovani.Patti();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.Patti.ProfilingPatto }
	 * 
	 */
	public PartecipanteGaranziaGiovani.Patti.ProfilingPatto createPartecipanteGaranziaGiovaniPattiProfilingPatto() {
		return new PartecipanteGaranziaGiovani.Patti.ProfilingPatto();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.Patti.ProfilingPatto.PoliticheAttive }
	 * 
	 */
	public PartecipanteGaranziaGiovani.Patti.ProfilingPatto.PoliticheAttive createPartecipanteGaranziaGiovaniPattiProfilingPattoPoliticheAttive() {
		return new PartecipanteGaranziaGiovani.Patti.ProfilingPatto.PoliticheAttive();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.Partecipante }
	 * 
	 */
	public PartecipanteGaranziaGiovani.Partecipante createPartecipanteGaranziaGiovaniPartecipante() {
		return new PartecipanteGaranziaGiovani.Partecipante();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.ComunicazioniObbligatorie.ComunicazioneObbligatoria }
	 * 
	 */
	public PartecipanteGaranziaGiovani.ComunicazioniObbligatorie.ComunicazioneObbligatoria createPartecipanteGaranziaGiovaniComunicazioniObbligatorieComunicazioneObbligatoria() {
		return new PartecipanteGaranziaGiovani.ComunicazioniObbligatorie.ComunicazioneObbligatoria();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.Patti.ProfilingPatto.PoliticheAttive.PoliticaAttiva }
	 * 
	 */
	public PartecipanteGaranziaGiovani.Patti.ProfilingPatto.PoliticheAttive.PoliticaAttiva createPartecipanteGaranziaGiovaniPattiProfilingPattoPoliticheAttivePoliticaAttiva() {
		return new PartecipanteGaranziaGiovani.Patti.ProfilingPatto.PoliticheAttive.PoliticaAttiva();
	}

	/**
	 * Create an instance of {@link PartecipanteGaranziaGiovani.Partecipante.Accorpamento }
	 * 
	 */
	public PartecipanteGaranziaGiovani.Partecipante.Accorpamento createPartecipanteGaranziaGiovaniPartecipanteAccorpamento() {
		return new PartecipanteGaranziaGiovani.Partecipante.Accorpamento();
	}

}
