package it.eng.myportal.entity;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.MappedSuperclass;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcCandidatura generated by hbm2java
 */
@MappedSuperclass
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class AbstractDecodeEntity implements java.io.Serializable, IDecodeEntity {
	private static final long serialVersionUID = 655003L;

	private Date dtInizioVal;
	private Date dtFineVal;

	public AbstractDecodeEntity() {
	}

	public AbstractDecodeEntity(Date dtInizioVal, Date dtFineVal) {
		this.dtInizioVal = dtInizioVal;
		this.dtFineVal = dtFineVal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_inizio_val", nullable = false, length = 13)
	public Date getDtInizioVal() {
		return this.dtInizioVal;
	}

	public void setDtInizioVal(Date dtInizioVal) {
		this.dtInizioVal = dtInizioVal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_fine_val", nullable = false, length = 13)
	public Date getDtFineVal() {
		return this.dtFineVal;
	}

	public void setDtFineVal(Date dtFineVal) {
		this.dtFineVal = dtFineVal;
	}

}
