package it.eng.myportal.entity;

// default package
// Generated 26-feb-2013 16.56.17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import it.eng.myportal.entity.decodifiche.DeTipoConsulenza;
import it.eng.myportal.entity.decodifiche.DeTipoPratica;

/**
 * MsgPraticheConsulenti generated by hbm2java
 */
@Entity
@Table(name = "atp_pratiche_consulenti", schema = "myportal")
public class AtpPraticheConsulenti extends AbstractEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAtpPraticheConsulenti;
	private DeTipoConsulenza deTipoConsulenza;
	private DeTipoPratica deTipoPratica;
	

	public AtpPraticheConsulenti() {
	}

	
	

	@Id
	@Column(name = "id_atp_pratiche_consulenti", unique = true, nullable = false)
	public int getIdAtpPraticheConsulenti() {
		return this.idAtpPraticheConsulenti;
	}

	public void setIdAtpPraticheConsulenti(int idMsgPraticheConsulenti) {
		this.idAtpPraticheConsulenti = idMsgPraticheConsulenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_consulente")
	public DeTipoConsulenza getDeTipoConsulenza() {
		return this.deTipoConsulenza;
	}

	public void setDeTipoConsulenza(DeTipoConsulenza deTipoConsulente) {
		this.deTipoConsulenza = deTipoConsulente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_pratica")
	public DeTipoPratica getDeTipoPratica() {
		return this.deTipoPratica;
	}

	public void setDeTipoPratica(DeTipoPratica deTipoPratica) {
		this.deTipoPratica = deTipoPratica;
	}



	
}
