package it.eng.myportal.entity;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import it.eng.myportal.entity.decodifiche.DeAutorizzazioneSare;
import it.eng.myportal.entity.decodifiche.DeComune;
import it.eng.myportal.entity.decodifiche.DeProvincia;
import it.eng.myportal.entity.decodifiche.DeTipoAbilitato;
import it.eng.myportal.entity.decodifiche.DeTipoDelegato;
import it.eng.myportal.entity.decodifiche.DeTipoUtenteSare;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * AziendaInfo generated by hbm2java
 */
@Entity
@Table(name = "azienda_info_rettifica", schema = "mycas")
public class AziendaInfoRettifica extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 3312L;

	private Integer idPfPrincipal;
	private PfPrincipal pfPrincipal;

	private String capRic;
	private String capSede;
	private String capSedeLegale;
	private String codiceFiscale;
	private String cognomeRic;
	private DeAutorizzazioneSare deAutorizzazioneSare;
	private DeComune deComuneIscrizione;
	private DeComune deComuneNascitaRic;
	private DeComune deComuneRichiedente;
	private DeComune deComuneSede;
	private DeComune deComuneSedeLegale;
	private DeProvincia deProvincia;
	private DeTipoAbilitato deTipoAbilitato;
	private DeTipoDelegato deTipoDelegato;
	private DeTipoUtenteSare deTipoUtenteSare;

	private String domanda;
	private Date dtDataNascitaRic;
	private Date dtIscrData;

	private Date dtIscrProvvedData;
	private String emailReferente;
	private String emailSede;
	private String faxSede;
	private String faxSedeLegale;
	private Boolean flagAgenziaEstera;
	private String indirizzoRic;
	private String indirizzoSede;
	private String indirizzoSedeLegale;
	private String iscrNumero;
	private String iscrOrdine;
	private String iscrProvvedNumero;
	private byte[] logo;
	private String mittenteSare;
	private String nomeRic;

	private String partitaIva;
	private String ragioneSociale;

	private String referenteSare;
	private String risposta;

	private String swCreazioneCo;
	private String telefonoReferente;
	private String telefonoSede;
	private String telefonoSedeLegale;

	private Integer idRichiesta;

	private String cellSedeLegale;
	private String cellReferente;
	private String emailRic;

	public AziendaInfoRettifica() {
	}

	@Id
	@Column(name = "id_pf_principal", unique = true, nullable = false)
	public Integer getIdPfPrincipal() {
		return this.idPfPrincipal;
	}

	public void setIdPfPrincipal(Integer idPfPrincipal) {
		this.idPfPrincipal = idPfPrincipal;
	}

	@PrimaryKeyJoinColumn
	@OneToOne(fetch = FetchType.LAZY)
	public PfPrincipal getPfPrincipal() {
		return this.pfPrincipal;
	}

	public void setPfPrincipal(PfPrincipal pfPrincipal) {
		this.pfPrincipal = pfPrincipal;
	}

	@Column(name = "cap_ric", length = 5)
	public String getCapRic() {
		return this.capRic;
	}

	@Column(name = "cap_sede", length = 5)
	public String getCapSede() {
		return this.capSede;
	}

	@Column(name = "cap_sede_legale", length = 5)
	public String getCapSedeLegale() {
		return this.capSedeLegale;
	}

	@Column(name = "codice_fiscale", length = 99)
	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	@Column(name = "cognome_ric", length = 50)
	public String getCognomeRic() {
		return this.cognomeRic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_autorizzazione_sare")
	public DeAutorizzazioneSare getDeAutorizzazioneSare() {
		return deAutorizzazioneSare;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_com_iscr")
	public DeComune getDeComuneIscrizione() {
		return this.deComuneIscrizione;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_com_nascita_ric")
	public DeComune getDeComuneNascitaRic() {
		return this.deComuneNascitaRic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_com_ric")
	public DeComune getDeComuneRichiedente() {
		return this.deComuneRichiedente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_com_sede")
	public DeComune getDeComuneSede() {
		return this.deComuneSede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_com_sede_legale")
	public DeComune getDeComuneSedeLegale() {
		return this.deComuneSedeLegale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_provincia")
	public DeProvincia getDeProvincia() {
		return this.deProvincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_abilitato")
	public DeTipoAbilitato getDeTipoAbilitato() {
		return this.deTipoAbilitato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_delegato")
	public DeTipoDelegato getDeTipoDelegato() {
		return this.deTipoDelegato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_utente_sare")
	public DeTipoUtenteSare getDeTipoUtenteSare() {
		return this.deTipoUtenteSare;
	}

	@Column(name = "domanda", length = 255)
	public String getDomanda() {
		return domanda;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_data_nascita_ric", length = 29)
	public Date getDtDataNascitaRic() {
		return this.dtDataNascitaRic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_iscr_data", length = 29)
	public Date getDtIscrData() {
		return this.dtIscrData;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_iscr_provved_data", length = 29)
	public Date getDtIscrProvvedData() {
		return this.dtIscrProvvedData;
	}

	@Column(name = "email_ric", length = 255)
	public String getEmailRic() {
		return emailRic;
	}

	@Column(name = "email_referente")
	public String getEmailReferente() {
		return this.emailReferente;
	}

	@Column(name = "email_sede", length = 100)
	public String getEmailSede() {
		return this.emailSede;
	}

	@Column(name = "fax_sede", length = 50)
	public String getFaxSede() {
		return this.faxSede;
	}

	@Column(name = "fax_sede_legale", length = 50)
	public String getFaxSedeLegale() {
		return this.faxSedeLegale;
	}

	@Type(type = "yes_no")
	@Column(name = "flag_agenzia_estera", length = 1)
	public Boolean getFlagAgenziaEstera() {
		return this.flagAgenziaEstera;
	}

	@Column(name = "indirizzo_ric", length = 100)
	public String getIndirizzoRic() {
		return this.indirizzoRic;
	}

	@Column(name = "indirizzo_sede")
	public String getIndirizzoSede() {
		return this.indirizzoSede;
	}

	@Column(name = "indirizzo_sede_legale", length = 100)
	public String getIndirizzoSedeLegale() {
		return this.indirizzoSedeLegale;
	}

	@Column(name = "iscr_numero", length = 50)
	public String getIscrNumero() {
		return this.iscrNumero;
	}

	@Column(name = "iscr_ordine", length = 80)
	public String getIscrOrdine() {
		return this.iscrOrdine;
	}

	@Column(name = "iscr_provved_numero", length = 30)
	public String getIscrProvvedNumero() {
		return this.iscrProvvedNumero;
	}

	@Column(name = "logo")
	public byte[] getLogo() {
		return this.logo;
	}

	@Column(name = "mittente_sare", length = 15)
	public String getMittenteSare() {
		return mittenteSare;
	}

	@Column(name = "nome_ric", length = 30)
	public String getNomeRic() {
		return this.nomeRic;
	}

	@Column(name = "partita_iva", length = 11)
	public String getPartitaIva() {
		return this.partitaIva;
	}

	@Column(name = "ragione_sociale", length = 100)
	public String getRagioneSociale() {
		return this.ragioneSociale;
	}

	@Column(name = "referente_sare", length = 80)
	public String getReferenteSare() {
		return this.referenteSare;
	}

	@Column(name = "risposta", length = 255)
	public String getRisposta() {
		return risposta;
	}

	@Column(name = "sw_creazione_co", length = 2)
	public String getSwCreazioneCo() {
		return swCreazioneCo;
	}

	@Column(name = "telefono_referente", length = 30)
	public String getTelefonoReferente() {
		return this.telefonoReferente;
	}

	@Column(name = "telefono_sede", length = 50)
	public String getTelefonoSede() {
		return this.telefonoSede;
	}

	@Column(name = "telefono_sede_legale", length = 50)
	public String getTelefonoSedeLegale() {
		return this.telefonoSedeLegale;
	}

	public void setCapRic(String capRic) {
		this.capRic = capRic;
	}

	public void setCapSede(String capSede) {
		this.capSede = capSede;
	}

	public void setCapSedeLegale(String capSedeLegale) {
		this.capSedeLegale = capSedeLegale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	public void setCognomeRic(String cognomeRic) {
		this.cognomeRic = cognomeRic;
	}

	public void setDeAutorizzazioneSare(DeAutorizzazioneSare deAutorizzazioneSare) {
		this.deAutorizzazioneSare = deAutorizzazioneSare;
	}

	public void setDeComuneIscrizione(DeComune deComuneIscrizione) {
		this.deComuneIscrizione = deComuneIscrizione;
	}

	public void setDeComuneNascitaRic(DeComune deComuneByCodComNascitaRic) {
		this.deComuneNascitaRic = deComuneByCodComNascitaRic;
	}

	public void setDeComuneRichiedente(DeComune deComuneRichiedente) {
		this.deComuneRichiedente = deComuneRichiedente;
	}

	public void setDeComuneSede(DeComune deComuneByCodComSede) {
		this.deComuneSede = deComuneByCodComSede;
	}

	public void setDeComuneSedeLegale(DeComune deComuneByCodComSedeLegale) {
		this.deComuneSedeLegale = deComuneByCodComSedeLegale;
	}

	public void setDeProvincia(DeProvincia deProvincia) {
		this.deProvincia = deProvincia;
	}

	public void setDeTipoAbilitato(DeTipoAbilitato deTipoAbilitato) {
		this.deTipoAbilitato = deTipoAbilitato;
	}

	public void setDeTipoDelegato(DeTipoDelegato deTipoDelegato) {
		this.deTipoDelegato = deTipoDelegato;
	}

	public void setDeTipoUtenteSare(DeTipoUtenteSare deTipoUtenteSare) {
		this.deTipoUtenteSare = deTipoUtenteSare;
	}

	public void setDomanda(String domanda) {
		this.domanda = domanda;
	}

	public void setDtDataNascitaRic(Date dtRicDataNascita) {
		this.dtDataNascitaRic = dtRicDataNascita;
	}

	public void setDtIscrData(Date dtIscrData) {
		this.dtIscrData = dtIscrData;
	}

	public void setDtIscrProvvedData(Date dtIscrProvvedData) {
		this.dtIscrProvvedData = dtIscrProvvedData;
	}

	public void setEmailRic(String emailRic) {
		this.emailRic = emailRic;
	}

	// @Column(name = "request_status", length = 1)
	// public String getRequestStatus() {
	// return this.requestStatus;
	// }
	//
	// public void setRequestStatus(String requestStatus) {
	// this.requestStatus = requestStatus;
	// }

	public void setEmailReferente(String emailReferente) {
		this.emailReferente = emailReferente;
	}

	public void setEmailSede(String emailSede) {
		this.emailSede = emailSede;
	}

	public void setFaxSede(String faxSede) {
		this.faxSede = faxSede;
	}

	public void setFaxSedeLegale(String faxSedeLegale) {
		this.faxSedeLegale = faxSedeLegale;
	}

	public void setFlagAgenziaEstera(Boolean flagAgenziaEstera) {
		this.flagAgenziaEstera = flagAgenziaEstera;
	}

	public void setIndirizzoRic(String indirizzoRic) {
		this.indirizzoRic = indirizzoRic;
	}

	public void setIndirizzoSede(String indirizzoSede) {
		this.indirizzoSede = indirizzoSede;
	}

	public void setIndirizzoSedeLegale(String indirizzoSedeLegale) {
		this.indirizzoSedeLegale = indirizzoSedeLegale;
	}

	public void setIscrNumero(String iscrNumero) {
		this.iscrNumero = iscrNumero;
	}

	public void setIscrOrdine(String iscrOrdine) {
		this.iscrOrdine = iscrOrdine;
	}

	public void setIscrProvvedNumero(String iscrProvvedNumero) {
		this.iscrProvvedNumero = iscrProvvedNumero;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	public void setMittenteSare(String mittenteSare) {
		this.mittenteSare = mittenteSare;
	}

	public void setNomeRic(String nomeRic) {
		this.nomeRic = nomeRic;
	}

	public void setPartitaIva(String partitaIva) {
		this.partitaIva = partitaIva;
	}

	public void setRagioneSociale(String ragioneSociale) {
		this.ragioneSociale = ragioneSociale;
	}

	public void setReferenteSare(String referenteSare) {
		this.referenteSare = referenteSare;
	}

	public void setRisposta(String risposta) {
		this.risposta = risposta;
	}

	public void setSwCreazioneCo(String swCreazioneCo) {
		this.swCreazioneCo = swCreazioneCo;
	}

	public void setTelefonoReferente(String telefonoReferente) {
		this.telefonoReferente = telefonoReferente;
	}

	public void setTelefonoSede(String telefonoSede) {
		this.telefonoSede = telefonoSede;
	}

	public void setTelefonoSedeLegale(String telefonoSedeLegale) {
		this.telefonoSedeLegale = telefonoSedeLegale;
	}

	@Column(name = "id_richiesta", nullable = false)
	public Integer getIdRichiesta() {
		return idRichiesta;
	}

	public void setIdRichiesta(Integer numrichiesta) {
		this.idRichiesta = numrichiesta;
	}

	@Column(name = "cell_sede_legale", length = 50)
	public String getCellSedeLegale() {
		return this.cellSedeLegale;
	}

	@Column(name = "cell_referente", length = 50)
	public String getCellReferente() {
		return this.cellReferente;
	}

	public void setCellSedeLegale(String cellSedeLegale) {
		this.cellSedeLegale = cellSedeLegale;
	}

	public void setCellReferente(String cellReferente) {
		this.cellReferente = cellReferente;
	}
}
