package it.eng.myportal.entity;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import it.eng.myportal.entity.decodifiche.DeAtpEnteConsulente;
import it.eng.myportal.entity.decodifiche.DeTipoPratica;

/**
 * AziendaInfo generated by hbm2java
 */
@Entity
@Table(name = "consulente_info", schema = "mycas")
public class ConsulenteInfo extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 3312L;

	private PfPrincipal pfPrincipal;
	private Integer idPfPrincipal;
	private DeTipoPratica deTipoPratica;
	private DeAtpEnteConsulente enteConsulente;
	private Integer monteOre;
	private Integer oreSvolte;
	private String opzPrivilegio;
	private String opzAtipicoPIva;

	private Date dtmInizio;
	private Date dtmFine;

	public ConsulenteInfo() {
	}

	@Id
	@Column(name = "id_pf_principal", unique = true, nullable = false)
	public Integer getIdPfPrincipal() {
		return this.idPfPrincipal;
	}

	public void setIdPfPrincipal(Integer idPfPrincipal) {
		this.idPfPrincipal = idPfPrincipal;
	}

	@PrimaryKeyJoinColumn
	@OneToOne(fetch = FetchType.LAZY)
	public PfPrincipal getPfPrincipal() {
		return this.pfPrincipal;
	}

	public void setPfPrincipal(PfPrincipal pfPrincipal) {
		this.pfPrincipal = pfPrincipal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_pratica")
	public DeTipoPratica getDeTipoPratica() {
		return this.deTipoPratica;
	}

	public void setDeTipoPratica(DeTipoPratica deTipoPratica) {
		this.deTipoPratica = deTipoPratica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_ente_consulente")
	public DeAtpEnteConsulente getEnteConsulente() {
		return this.enteConsulente;
	}

	public void setEnteConsulente(DeAtpEnteConsulente sindacato) {
		this.enteConsulente = sindacato;
	}

	@Column(name = "monte_ore")
	public Integer getMonteOre() {
		return this.monteOre;
	}

	public void setMonteOre(Integer monteOre) {
		this.monteOre = monteOre;
	}

	@Column(name = "ore_svolte")
	public Integer getOreSvolte() {
		return this.oreSvolte;
	}

	public void setOreSvolte(Integer oreSvolte) {
		this.oreSvolte = oreSvolte;
	}

	@Column(name = "opz_privilegio", length = 1)
	public String getOpzPrivilegio() {
		return this.opzPrivilegio;
	}

	public void setOpzPrivilegio(String opzPrivilegio) {
		this.opzPrivilegio = opzPrivilegio;
	}

	@Column(name = "opz_atipico_p_iva", length = 1)
	public String getOpzAtipicoPIva() {
		return this.opzAtipicoPIva;
	}

	public void setOpzAtipicoPIva(String opzAtipicoPIva) {
		this.opzAtipicoPIva = opzAtipicoPIva;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtm_inizio", nullable = false, length = 29)
	public Date getDtmInizio() {
		return this.dtmInizio;
	}

	public void setDtmInizio(Date dtmInizio) {
		this.dtmInizio = dtmInizio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtm_fine", nullable = false, length = 29)
	public Date getDtmFine() {
		return this.dtmFine;
	}

	public void setDtmFine(Date dtmFine) {
		this.dtmFine = dtmFine;
	}

	@Transient
	public boolean isPartitaIva() {
		return "P".equals(getOpzAtipicoPIva());
	}

	@Transient
	public boolean isAtipico() {
		return "A".equals(getOpzAtipicoPIva());
	}

}
