package it.eng.myportal.entity;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import it.eng.myportal.entity.decodifiche.DeAgevolazione;

/**
 * CvAgevolazione generated by hbm2java
 */
@Entity
@Table(name = "cv_agevolazione", schema = "myportal")
public class CvAgevolazione extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 961579L;
	private Integer idCvAgevolazione;

	private CvDatiPersonali cvDatiPersonali;
	private DeAgevolazione deAgevolazione;

	public CvAgevolazione() {
	}
	
	public CvAgevolazione(Integer idCvAgevolazione, PfPrincipal pfPrincipalByIdPrincipalMod, PfPrincipal pfPrincipalByIdPrincipalIns, CvDatiPersonali cvDatiPersonali, DeAgevolazione deAgevolazione, Date dtmIns, Date dtmMod) {
		super(pfPrincipalByIdPrincipalIns, pfPrincipalByIdPrincipalMod, dtmIns, dtmMod);
	       this.idCvAgevolazione = idCvAgevolazione;
	       
	       this.cvDatiPersonali = cvDatiPersonali;
	       this.deAgevolazione = deAgevolazione;
	       
	    }

	@Id
	@SequenceGenerator(name = "cv_agevolazione_id_cv_agevolazione_seq", sequenceName = "cv_agevolazione_id_cv_agevolazione_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cv_agevolazione_id_cv_agevolazione_seq")
	@Column(name = "id_cv_agevolazione", unique = true, nullable = false)
	public Integer getIdCvAgevolazione() {
		return this.idCvAgevolazione;
	}

	public void setIdCvAgevolazione(Integer idCvAgevolazione) {
		this.idCvAgevolazione = idCvAgevolazione;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cv_dati_personali", nullable = false)
	public CvDatiPersonali getCvDatiPersonali() {
		return this.cvDatiPersonali;
	}

	public void setCvDatiPersonali(CvDatiPersonali cvDatiPersonali) {
		this.cvDatiPersonali = cvDatiPersonali;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_agevolazione", nullable = false)
	public DeAgevolazione getDeAgevolazione() {
		return this.deAgevolazione;
	}

	public void setDeAgevolazione(DeAgevolazione deAgevolazione) {
		this.deAgevolazione = deAgevolazione;
	}

}
