package it.eng.myportal.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import it.eng.myportal.entity.decodifiche.DeAlbo;
import it.eng.myportal.entity.decodifiche.sil.DeAlboSil;

/**
 * CvAlbo generated by hbm2java
 */
@Entity
@Table(name = "cv_albo", schema = "myportal")
@NamedQueries({
	@NamedQuery(name = "CvAlboFindByCvId", query = "select d from CvAlbo d where d.cvDatiPersonali.idCvDatiPersonali = :cvId")
	})
public class CvAlbo extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 623082L;
	private Integer idCvAlbo;

	private DeAlbo deAlbo;
	private DeAlboSil deAlboSil;
	private CvDatiPersonali cvDatiPersonali;

	public CvAlbo() {
	}

	public CvAlbo(Integer idCvAlbo, PfPrincipal pfPrincipalByIdPrincipalMod, PfPrincipal pfPrincipalByIdPrincipalIns,
			CvDatiPersonali cvDatiPersonali, Date dtmIns, Date dtmMod) {
		super(pfPrincipalByIdPrincipalIns, pfPrincipalByIdPrincipalMod, dtmIns, dtmMod);
		this.idCvAlbo = idCvAlbo;
		this.deAlbo = deAlbo;
		this.cvDatiPersonali = cvDatiPersonali;
	}

	@Id
	@SequenceGenerator(name = "cv_albo_id_cv_albo_seq", sequenceName = "cv_albo_id_cv_albo_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cv_albo_id_cv_albo_seq")
	@Column(name = "id_cv_albo", unique = true, nullable = false)
	public Integer getIdCvAlbo() {
		return this.idCvAlbo;
	}

	public void setIdCvAlbo(Integer idCvAlbo) {
		this.idCvAlbo = idCvAlbo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cv_dati_personali", nullable = false)
	public CvDatiPersonali getCvDatiPersonali() {
		return this.cvDatiPersonali;
	}

	public void setCvDatiPersonali(CvDatiPersonali cvDatiPersonali) {
		this.cvDatiPersonali = cvDatiPersonali;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_albo")
	public DeAlbo getDeAlbo() {
		return this.deAlbo;
	}

	public void setDeAlbo(DeAlbo deAlbo) {
		this.deAlbo = deAlbo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_albo_sil")
	public DeAlboSil getDeAlboSil() {
		return deAlboSil;
	}

	public void setDeAlboSil(DeAlboSil deAlboSil) {
		this.deAlboSil = deAlboSil;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idCvAlbo == null) ? 0 : idCvAlbo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CvAlbo other = (CvAlbo) obj;
		if (idCvAlbo == null) {
			if (other.idCvAlbo != null)
				return false;
		} else if (!idCvAlbo.equals(other.idCvAlbo))
			return false;
		return true;
	}

}
