package it.eng.myportal.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

import it.eng.myportal.entity.decodifiche.DeAmbitoDisciplinare;
import it.eng.myportal.entity.decodifiche.DeAreaFormazione;
import it.eng.myportal.entity.decodifiche.DeComune;
import it.eng.myportal.entity.decodifiche.DeCorso;
import it.eng.myportal.entity.decodifiche.DeTipoCorsoSil;

/**
 * CvFormazione generated by hbm2java
 */
@Entity
@Table(name = "cv_formazione", schema = "myportal")
@NamedQueries({
	@NamedQuery(name = "CvFormazioneFindByCvId", query = "select d from CvFormazione d where d.cvDatiPersonali.idCvDatiPersonali = :cvId ORDER BY d.numAnno DESC")
	})
public class CvFormazione extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 670022L;

	private Integer idCvFormazione;
	private DeCorso deCorso;
	private CvDatiPersonali cvDatiPersonali;
	private String titoloCorso;
	private String principaliTematiche;
	private String nomeIstituto;
	private String livelloClassificazione;
	private Integer numAnno;
	private String durata;
	private String descrizione;
	private DeComune deComuneEnte;
	private Boolean flgCompletato;
	private DeTipoCorsoSil deTipoCorso;
	private DeAmbitoDisciplinare deAmbitoDisciplinare;
	private DeAreaFormazione deAreaFormazione;
	private Boolean flgInCorso;
	private String attestazioneConseguita;

	public CvFormazione() {
	}

	@Id
	@SequenceGenerator(name = "cv_formazione_id_cv_formazione_seq", sequenceName = "cv_formazione_id_cv_formazione_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cv_formazione_id_cv_formazione_seq")
	@Column(name = "id_cv_formazione", unique = true, nullable = false)
	public Integer getIdCvFormazione() {
		return this.idCvFormazione;
	}

	public void setIdCvFormazione(Integer idCvFormazione) {
		this.idCvFormazione = idCvFormazione;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_corso")
	public DeCorso getDeCorso() {
		return this.deCorso;
	}

	public void setDeCorso(DeCorso deCorso) {
		this.deCorso = deCorso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cv_dati_personali", nullable = false)
	public CvDatiPersonali getCvDatiPersonali() {
		return this.cvDatiPersonali;
	}

	public void setCvDatiPersonali(CvDatiPersonali cvDatiPersonali) {
		this.cvDatiPersonali = cvDatiPersonali;
	}

	@Column(name = "titolo_corso", length = 250)
	public String getTitoloCorso() {
		return this.titoloCorso;
	}

	public void setTitoloCorso(String titoloCorso) {
		this.titoloCorso = titoloCorso;
	}

	@Column(name = "principali_tematiche", length = 250)
	public String getPrincipaliTematiche() {
		return this.principaliTematiche;
	}

	public void setPrincipaliTematiche(String principaliTematiche) {
		this.principaliTematiche = principaliTematiche;
	}

	@Column(name = "nome_istituto", length = 250)
	public String getNomeIstituto() {
		return this.nomeIstituto;
	}

	public void setNomeIstituto(String nomeIstituto) {
		this.nomeIstituto = nomeIstituto;
	}

	@Column(name = "livello_classificazione", length = 100)
	public String getLivelloClassificazione() {
		return this.livelloClassificazione;
	}

	public void setLivelloClassificazione(String livelloClassificazione) {
		this.livelloClassificazione = livelloClassificazione;
	}

	@Column(name = "num_anno")
	public Integer getNumAnno() {
		return this.numAnno;
	}

	public void setNumAnno(Integer numAnno) {
		this.numAnno = numAnno;
	}

	@Column(name = "durata", length = 20)
	public String getDurata() {
		return this.durata;
	}

	public void setDurata(String durata) {
		this.durata = durata;
	}

	@Column(name = "descrizione", length = 300)
	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_comune_ente")
	public DeComune getDeComuneEnte() {
		return deComuneEnte;
	}

	public void setDeComuneEnte(DeComune deComuneEnte) {
		this.deComuneEnte = deComuneEnte;
	}

	@Type(type = "yes_no")
	@Column(name = "flg_completato", length = 1)
	public Boolean getFlgCompletato() {
		return flgCompletato;
	}

	public void setFlgCompletato(Boolean flgCompletato) {
		this.flgCompletato = flgCompletato;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_tipo_corso_sil")
	public DeTipoCorsoSil getDeTipoCorso() {
		return deTipoCorso;
	}

	public void setDeTipoCorso(DeTipoCorsoSil deTipoCorso) {
		this.deTipoCorso = deTipoCorso;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_ambito_disciplinare")
	public DeAmbitoDisciplinare getDeAmbitoDisciplinare() {
		return deAmbitoDisciplinare;
	}

	public void setDeAmbitoDisciplinare(DeAmbitoDisciplinare deAmbitoDisciplinare) {
		this.deAmbitoDisciplinare = deAmbitoDisciplinare;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_area_formazione")
	public DeAreaFormazione getDeAreaFormazione() {
		return deAreaFormazione;
	}

	public void setDeAreaFormazione(DeAreaFormazione deAreaFormazione) {
		this.deAreaFormazione = deAreaFormazione;
	}

	@Column(name="flg_incorso")
	public Boolean getFlgInCorso() {
		return flgInCorso;
	}

	public void setFlgInCorso(Boolean flgInCorso) {
		this.flgInCorso = flgInCorso;
	}

	@Column(name="attestazione_conseguita", length=3000)
	public String getAttestazioneConseguita() {
		return attestazioneConseguita;
	}

	public void setAttestazioneConseguita(String attestazioneConseguita) {
		this.attestazioneConseguita = attestazioneConseguita;
	}
	
	

}
