package it.eng.myportal.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import it.eng.myportal.entity.decodifiche.DeAreaTitolo;
// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import it.eng.myportal.entity.decodifiche.DeComune;
import it.eng.myportal.entity.decodifiche.DeStatoTitolo;
import it.eng.myportal.entity.decodifiche.DeTitolo;

/**
 * CvIstruzione generated by hbm2java
 */
@Entity
@Table(name = "cv_istruzione", schema = "myportal")
@NamedQueries({
		@NamedQuery(name = "CvIstruzioneFindByCvId", query = "select d from CvIstruzione d where d.cvDatiPersonali.idCvDatiPersonali = :cvId ORDER BY d.numAnno DESC") })

public class CvIstruzione extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 810502L;
	private Integer idCvIstruzione;

	private CvDatiPersonali cvDatiPersonali;
	private DeTitolo deTitolo;
	private DeComune deComune;
	private String tematicheTrattate;
	private String nomeIstituto;
	private String votazione;
	private Integer numAnno;
	private String specifica;
	private DeStatoTitolo deStatoTitolo;
	private DeAreaTitolo deAreaTitolo;// 2020
	private Boolean flgInCorso;

	public CvIstruzione() {
	}

	@Id
	@SequenceGenerator(name = "cv_istruzione_id_cv_istruzione_seq", sequenceName = "cv_istruzione_id_cv_istruzione_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cv_istruzione_id_cv_istruzione_seq")
	@Column(name = "id_cv_istruzione", unique = true, nullable = false)
	public Integer getIdCvIstruzione() {
		return this.idCvIstruzione;
	}

	public void setIdCvIstruzione(Integer idCvIstruzione) {
		this.idCvIstruzione = idCvIstruzione;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cv_dati_personali", nullable = false)
	public CvDatiPersonali getCvDatiPersonali() {
		return this.cvDatiPersonali;
	}

	public void setCvDatiPersonali(CvDatiPersonali cvDatiPersonali) {
		this.cvDatiPersonali = cvDatiPersonali;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_titolo", nullable = false)
	public DeTitolo getDeTitolo() {
		return this.deTitolo;
	}

	public void setDeTitolo(DeTitolo deTitolo) {
		this.deTitolo = deTitolo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_com_istituto")
	public DeComune getDeComune() {
		return this.deComune;
	}

	public void setDeComune(DeComune deComune) {
		this.deComune = deComune;
	}

	@Column(name = "tematiche_trattate", length = 4000)
	public String getTematicheTrattate() {
		return this.tematicheTrattate;
	}

	public void setTematicheTrattate(String tematicheTrattate) {
		this.tematicheTrattate = tematicheTrattate;
	}

	@Column(name = "nome_istituto")
	public String getNomeIstituto() {
		return this.nomeIstituto;
	}

	public void setNomeIstituto(String nomeIstituto) {
		this.nomeIstituto = nomeIstituto;
	}

	@Column(name = "votazione", length = 30)
	public String getVotazione() {
		return this.votazione;
	}

	public void setVotazione(String votazione) {
		this.votazione = votazione;
	}

	@Column(name = "num_anno")
	public Integer getNumAnno() {
		return this.numAnno;
	}

	public void setNumAnno(Integer numAnno) {
		this.numAnno = numAnno;
	}

	@Column(name = "specifica", length = 250)
	public String getSpecifica() {
		return specifica;
	}

	public void setSpecifica(String specifica) {
		this.specifica = specifica;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_stato_titolo")
	public DeStatoTitolo getDeStatoTitolo() {
		return deStatoTitolo;
	}

	public void setDeStatoTitolo(DeStatoTitolo deStatoTitolo) {
		this.deStatoTitolo = deStatoTitolo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_area_titolo_studio", nullable = true)
	public DeAreaTitolo getDeAreaTitolo() {
		return deAreaTitolo;
	}

	public void setDeAreaTitolo(DeAreaTitolo deAreaTitolo) {
		this.deAreaTitolo = deAreaTitolo;
	}

	@Column(name = "flg_in_corso", nullable=true)
	public Boolean getFlgInCorso() {
		return flgInCorso;
	}

	public void setFlgInCorso(Boolean flgInCorso) {
		this.flgInCorso = flgInCorso;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idCvIstruzione == null) ? 0 : idCvIstruzione.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CvIstruzione other = (CvIstruzione) obj;
		if (idCvIstruzione == null) {
			if (other.idCvIstruzione != null)
				return false;
		} else if (!idCvIstruzione.equals(other.idCvIstruzione))
			return false;
		return true;
	}
}
