package it.eng.myportal.entity;
// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
/**
 * CvLetteraInfo generated by hbm2java
 */
@Entity
@Table(name="cv_lettera_info"
    ,schema="myportal"
)
public class CvLetteraInfo extends AbstractEntity  implements java.io.Serializable {
	private static final long serialVersionUID = 759972L;
     private String codLetteraInfo;
    
     private String titoloInfo;
     private String descrizioneInfo;
    
    public CvLetteraInfo() {
    }
   
     @Id 
    @Column(name="cod_lettera_info", unique=true, nullable=false, length=8)
    public String getCodLetteraInfo() {
        return this.codLetteraInfo;
    }
    public void setCodLetteraInfo(String codLetteraInfo) {
        this.codLetteraInfo = codLetteraInfo;
    }
    @Column(name="titolo_info", length=100)
    public String getTitoloInfo() {
        return this.titoloInfo;
    }
    public void setTitoloInfo(String titoloInfo) {
        this.titoloInfo = titoloInfo;
    }
    @Column(name="descrizione_info", length=5000)
    public String getDescrizioneInfo() {
        return this.descrizioneInfo;
    }
    public void setDescrizioneInfo(String descrizioneInfo) {
        this.descrizioneInfo = descrizioneInfo;
    }
    
}
