package it.eng.myportal.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import it.eng.myportal.entity.decodifiche.DeComune;
import it.eng.myportal.entity.decodifiche.DeCpi;
import it.eng.myportal.entity.decodifiche.DeMansione;
import it.eng.myportal.entity.decodifiche.DeProvincia;
import it.eng.myportal.entity.decodifiche.DeQualificaSrq;
import it.eng.myportal.entity.decodifiche.DeTitolo;
import it.eng.myportal.entity.decodifiche.min.DeMansioneMin;

/**
 * DoTirocini generated by manazza
 * 
 * @author pegoraro
 */
@Entity
@Table(name = "do_tirocini", schema = "myportal")
public class DoTirocini extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 90883L;

	private Integer idDoTirocinio;
	private PfPrincipal pfPrincipal;
	private Integer numFigureProf;

	private Date dataRichiesta;
	private Date dataScadenza;

	private String cognomeRif;
	private String nomeRif;
	private String emailRif;
	private String cfRif;
	private String ragSocRif;

	private DeComune deComune;
	private DeProvincia deProvincia;
	private DeCpi deCpi;
	private DeMansione deMansione;
	private DeMansioneMin deMansioneMin;
	private DeTitolo deTitolo;

	private Integer numAnnoSil;
	private Integer numRichiestaSil;

	private String codProvenienzaVacancySil;
	private DeQualificaSrq deQualificaSrq;
	 	
	private String tipoDelegatoRifAzienda;

	public DoTirocini() {
	}
	
	@Id
	@SequenceGenerator(name = "do_tirocini_id_do_tirocinio_seq", sequenceName = "do_tirocini_id_do_tirocinio_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "do_tirocini_id_do_tirocinio_seq")
	@Column(name = "id_do_tirocinio", unique = true, nullable = false)
	public Integer getIdDoTirocinio() {
		return this.idDoTirocinio;
	}

	public void setIdDoTirocinio(Integer idMsgMessaggio) {
		this.idDoTirocinio = idMsgMessaggio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pf_principal", nullable = false)
	public PfPrincipal getPfPrincipal() {
		return this.pfPrincipal;
	}

	public void setPfPrincipal(PfPrincipal pfPrincipal) {
		this.pfPrincipal = pfPrincipal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_richiesta", length = 13, nullable = false)
	public Date getDataRichiesta() {
		return dataRichiesta;
	}

	public void setDataRichiesta(Date dtNascita) {
		dataRichiesta = dtNascita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_scadenza", length = 13, nullable = false)
	public Date getDataScadenza() {
		return dataScadenza;
	}

	public void setDataScadenza(Date dtNascita) {
		dataScadenza = dtNascita;
	}

	@Column(name = "num_figure_prof", nullable = false)
	public Integer getNumFigureProf() {
		return this.numFigureProf;
	}

	public void setNumFigureProf(Integer numPopolazione) {
		this.numFigureProf = numPopolazione;
	}

	@Column(name = "cognome_rif", nullable = true, length = 100)
	public String getCognomeRif() {
		return this.cognomeRif;
	}

	@Column(name = "nome_rif", nullable = true, length = 100)
	public String getNomeRif() {
		return this.nomeRif;
	}

	@Column(name = "email_rif", nullable = true, length = 100)
	public String getEmailRif() {
		return this.emailRif;
	}

	public void setCognomeRif(String cognomeRif) {
		this.cognomeRif = cognomeRif;
	}

	public void setNomeRif(String nomeRif) {
		this.nomeRif = nomeRif;
	}

	public void setEmailRif(String emailRif) {
		this.emailRif = emailRif;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_com")
	public DeComune getDeComune() {
		return this.deComune;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_provincia")
	public DeProvincia getDeProvincia() {
		return this.deProvincia;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_cpi")
	public DeCpi getDeCpi() {
		return this.deCpi;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_mansione", nullable = true)
	public DeMansione getDeMansione() {
		return this.deMansione;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_mansione_min", nullable = true)
	public DeMansioneMin getDeMansioneMin() {
		return this.deMansioneMin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_titolo", nullable = true)
	public DeTitolo getDeTitolo() {
		return this.deTitolo;
	}

	public void setDeTitolo(DeTitolo deTitolo) {
		this.deTitolo = deTitolo;
	}

	@Column(name = "num_anno_sil")
	public Integer getNumAnnoSil() {
		return this.numAnnoSil;
	}

	@Column(name = "num_richiesta_sil")
	public Integer getNumRichiestaSil() {
		return this.numRichiestaSil;
	}

	@Column(name = "cod_provenienza_vacancy_sil", nullable = true, length = 8)
	public String getCodProvenienzaVacancySil() {
		return this.codProvenienzaVacancySil;
	}

	public void setDeComune(DeComune deComune) {
		this.deComune = deComune;
	}

	public void setDeProvincia(DeProvincia deProvincia) {
		this.deProvincia = deProvincia;
	}

	public void setDeCpi(DeCpi deCpi) {
		this.deCpi = deCpi;
	}

	public void setDeMansione(DeMansione deMansione) {
		this.deMansione = deMansione;
	}

	public void setDeMansioneMin(DeMansioneMin deMansioneMin) {
		this.deMansioneMin = deMansioneMin;
	}

	public void setNumAnnoSil(Integer numAnnoSil) {
		this.numAnnoSil = numAnnoSil;
	}

	public void setNumRichiestaSil(Integer numRichiestaSil) {
		this.numRichiestaSil = numRichiestaSil;
	}

	public void setCodProvenienzaVacancySil(String codProvenienzaVacancySil) {
		this.codProvenienzaVacancySil = codProvenienzaVacancySil;
	}
	
	@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="cod_qualifica_srq")
    public DeQualificaSrq getDeQualificaSrq() {
        return this.deQualificaSrq;
    }
    public void setDeQualificaSrq(DeQualificaSrq deQualificaSrq) {
        this.deQualificaSrq = deQualificaSrq;
    }

    @Column(name = "codice_fiscale_rif")
    public String getCfRif() {
		return cfRif;
	}

	public void setCfRif(String cfRif) {
		this.cfRif = cfRif;
	}

	@Column(name = "ragione_sociale_rif")
	public String getRagSocRif() {
		return ragSocRif;
	}

	@Column(name = "tipo_delegato_rif_azienda")
	public String getTipoDelegatoRifAzienda() {
		return tipoDelegatoRifAzienda;
	}
	
	public void setRagSocRif(String ragSocRif) {
		this.ragSocRif = ragSocRif;
	}

	public void setTipoDelegatoRifAzienda(String tipoDelegatoRifAzienda) {
		this.tipoDelegatoRifAzienda = tipoDelegatoRifAzienda;
	}
    
	@Override
	public String toString() {
		return "DoTirocini [idDoTirocinio=" + idDoTirocinio ;
	}

	public boolean equals(Object obj) {
		if (obj == null || this.getIdDoTirocinio() == null)
			return false;
		if (obj == this)
			return true;
		if (!(obj instanceof DoTirocini)) {
			return false;
		} else {
			return this.getIdDoTirocinio().equals(((DoTirocini) obj).getIdDoTirocinio());
		}
	}

	@Override
	public int hashCode() {
		return getIdDoTirocinio().hashCode();
	}
}
