package it.eng.myportal.entity;

// Generated Oct 18, 2012 12:38:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * MaOrario generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
@Table(name = "ma_orario", schema = "myportal")
public class MaOrario implements java.io.Serializable {

	private String codOrario;
	private String codModalitaLavoro;
	private Date dtInizioVal;
	private Date dtFineVal;

	public MaOrario() {
	}

	public MaOrario(String codOrario, String codModalitaLavoro, Date dtInizioVal, Date dtFineVal) {
		this.codOrario = codOrario;
		this.codModalitaLavoro = codModalitaLavoro;
		this.dtInizioVal = dtInizioVal;
		this.dtFineVal = dtFineVal;
	}

	@Id
	@Column(name = "cod_orario", unique = true, nullable = false, length = 8)
	public String getCodOrario() {
		return this.codOrario;
	}

	public void setCodOrario(String codOrario) {
		this.codOrario = codOrario;
	}

	@Column(name = "cod_modalita_lavoro", nullable = false, length = 8)
	public String getCodModalitaLavoro() {
		return this.codModalitaLavoro;
	}

	public void setCodModalitaLavoro(String codModalitaLavoro) {
		this.codModalitaLavoro = codModalitaLavoro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_inizio_val", nullable = false, length = 13)
	public Date getDtInizioVal() {
		return this.dtInizioVal;
	}

	public void setDtInizioVal(Date dtInizioVal) {
		this.dtInizioVal = dtInizioVal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_fine_val", nullable = false, length = 13)
	public Date getDtFineVal() {
		return this.dtFineVal;
	}

	public void setDtFineVal(Date dtFineVal) {
		this.dtFineVal = dtFineVal;
	}

}
