package it.eng.myportal.entity;

// Generated Oct 19, 2012 3:27:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * MsgContatto generated by hbm2java
 */
@Entity
@Table(name = "msg_contatto", schema = "myportal")
@NamedQueries({ @NamedQuery(name = "findAllByIdAcCandidatura", query = "select m from MsgContatto m where m.acCandidatura.idAcCandidatura = :idAcCandidatura") })
public class MsgContatto extends AbstractEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4136633881289172479L;
	private Integer idMsgMessaggio;
	private MsgMessaggio msgMessaggio;

	private AcCandidatura acCandidatura;
	private CvDatiPersonali cvDatiPersonali;
	private VaDatiVacancy vaDatiVacancy;

	private Boolean flagEsito;

	public MsgContatto() {
		super();
		flagEsito = false;
	}

	@Id
	@Column(name = "id_msg_messaggio", unique = true, nullable = false)
	public Integer getIdMsgMessaggio() {
		return this.idMsgMessaggio;
	}

	public void setIdMsgMessaggio(Integer idMsgMessaggio) {
		this.idMsgMessaggio = idMsgMessaggio;
	}

	@PrimaryKeyJoinColumn
	@OneToOne(fetch = FetchType.LAZY)
	public MsgMessaggio getMsgMessaggio() {
		return msgMessaggio;
	}

	public void setMsgMessaggio(MsgMessaggio msgMessaggio) {
		this.msgMessaggio = msgMessaggio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ac_candidatura")
	public AcCandidatura getAcCandidatura() {
		return acCandidatura;
	}

	public void setAcCandidatura(AcCandidatura acCandidatura) {
		this.acCandidatura = acCandidatura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cv_dati_personali")
	public CvDatiPersonali getCvDatiPersonali() {
		return cvDatiPersonali;
	}

	public void setCvDatiPersonali(CvDatiPersonali cvDatiPersonali) {
		this.cvDatiPersonali = cvDatiPersonali;
	}

	@Type(type = "yes_no")
	@Column(name = "flag_esito", nullable = false, length = 1)
	public Boolean getFlagEsito() {
		return flagEsito;
	}

	public void setFlagEsito(Boolean esito) {
		this.flagEsito = esito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_va_dati_vacancy")
	public VaDatiVacancy getVaDatiVacancy() {
		return this.vaDatiVacancy;
	}

	public void setVaDatiVacancy(VaDatiVacancy vaDatiVacancy) {
		this.vaDatiVacancy = vaDatiVacancy;
	}
}