package it.eng.myportal.entity;
// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import it.eng.myportal.entity.decodifiche.DeComune;
/**
 * OrEnteCorso generated by hbm2java
 */
@Entity
@Table(name="or_ente_corso"
    ,schema="myportal"
)
public class OrEnteCorso extends AbstractEntity  implements java.io.Serializable {
	private static final long serialVersionUID = 339150L;
     private Integer idOrEnteCorso;


     private DeComune deComune;
     private Integer codiceOrganismo;
     private String ragioneSociale;
     private String indirizzo;
     private String cap;
     private String telefono;
     private String fax;
     private String email;


     private Set<OrCorso> orCorsos = new HashSet<OrCorso>(0);
    public OrEnteCorso() {
    }
    
     @Id 
	@SequenceGenerator(name = "or_ente_corso_id_or_ente_corso_seq", sequenceName="or_ente_corso_id_or_ente_corso_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "or_ente_corso_id_or_ente_corso_seq")
    @Column(name="id_or_ente_corso", unique=true, nullable=false)
    public Integer getIdOrEnteCorso() {
        return this.idOrEnteCorso;
    }
    public void setIdOrEnteCorso(Integer idOrEnteCorso) {
        this.idOrEnteCorso = idOrEnteCorso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_com")
    public DeComune getDeComune() {
        return this.deComune;
    }
    public void setDeComune(DeComune deComune) {
        this.deComune = deComune;
    }
    @Column(name="codice_organismo", nullable=false)
    public Integer getCodiceOrganismo() {
        return this.codiceOrganismo;
    }
    public void setCodiceOrganismo(Integer codiceOrganismo) {
        this.codiceOrganismo = codiceOrganismo;
    }
    @Column(name="ragione_sociale", nullable=false, length=200)
    public String getRagioneSociale() {
        return this.ragioneSociale;
    }
    public void setRagioneSociale(String ragioneSociale) {
        this.ragioneSociale = ragioneSociale;
    }
    @Column(name="indirizzo", length=250)
    public String getIndirizzo() {
        return this.indirizzo;
    }
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }
    @Column(name="cap", length=5)
    public String getCap() {
        return this.cap;
    }
    public void setCap(String cap) {
        this.cap = cap;
    }
    @Column(name="telefono", length=150)
    public String getTelefono() {
        return this.telefono;
    }
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    @Column(name="fax", length=150)
    public String getFax() {
        return this.fax;
    }
    public void setFax(String fax) {
        this.fax = fax;
    }
    @Column(name="email", length=150)
    public String getEmail() {
        return this.email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="orEnteCorso")
    public Set<OrCorso> getOrCorsos() {
        return this.orCorsos;
    }
    public void setOrCorsos(Set<OrCorso> orCorsos) {
        this.orCorsos = orCorsos;
    }
}
