package it.eng.myportal.entity;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Utente generated by hbm2java
 */
@NamedQueries({
		@NamedQuery(name = "FIND_BY_UTENTE", query = "select p from PfIdentityDevice p where p.pfPrincipal = :id"),
		@NamedQuery(name = "pfIdentityDevice.findUsersApp", query = "select de from PfIdentityDevice de where upper(de.pfPrincipal.email)=:email and de.pfPrincipal.utenteInfo.deProvincia.codProvincia=:codProvincia and de.pfPrincipal.flagAbilitato = 'Y' order by de.id"),
		@NamedQuery(name = "pfIdentityDevice.getCountUsersApp", query = "select count(de.idPfIdentityDevice) from PfIdentityDevice de where upper(de.pfPrincipal.email)=:email and de.pfPrincipal.utenteInfo.deProvincia.codProvincia=:codProvincia and de.pfPrincipal.flagAbilitato = 'Y'"),
		@NamedQuery(name = "pfIdentityDevice.suggestEmailUsersApp", query = "select de.pfPrincipal.idPfPrincipal, de.pfPrincipal.email from PfIdentityDevice de where upper(de.pfPrincipal.email) like :email and de.pfPrincipal.utenteInfo.deProvincia.codProvincia=:codProvincia and de.pfPrincipal.flagAbilitato = 'Y' order by de.id"),
		@NamedQuery(name = "pfIdentityDevice.findAllIdPfPrincipal", query = "select de.pfPrincipal.idPfPrincipal from PfIdentityDevice de where de.pfPrincipal.flagAbilitato = 'Y' order by de.id") })
@Entity
@Table(name = "pf_identity_device", schema = "mycas")
public class PfIdentityDevice extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 414536L;
	private Integer idPfIdentityDevice;
	private PfPrincipal pfPrincipal;

	public PfIdentityDevice() {
	}

	@Id
	@SequenceGenerator(name = "pf_identity_device_id_pf_identity_device_seq", sequenceName = "mycas.pf_identity_device_id_pf_identity_device_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pf_identity_device_id_pf_identity_device_seq")
	@Column(name = "id_pf_identity_device", unique = true, nullable = false)
	public Integer getIdPfIdentityDevice() {
		return this.idPfIdentityDevice;
	}

	public void setIdPfIdentityDevice(Integer idPfIdentityDevice) {
		this.idPfIdentityDevice = idPfIdentityDevice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pf_principal", nullable = false)
	public PfPrincipal getPfPrincipal() {
		return this.pfPrincipal;
	}

	public void setPfPrincipal(PfPrincipal pfPrincipalByIdPfPrincipal) {
		this.pfPrincipal = pfPrincipalByIdPfPrincipal;
	}
}
