package it.eng.myportal.entity;
// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import it.eng.myportal.entity.decodifiche.DeRegione;
/**
 * Regione generated by hbm2java
 */
@Entity
@Table(name="regione"
    ,schema="mycas"
)
public class Regione extends AbstractEntity  implements java.io.Serializable {
	private static final long serialVersionUID = 257143L;
     private Integer idRegione;


     private PfPrincipal pfPrincipal;
     private DeRegione deRegione;


    public Regione() {
    }
   
     @Id 
	@SequenceGenerator(name = "mycas.regione_id_regione_seq", sequenceName="mycas.regione_id_regione_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "mycas.regione_id_regione_seq")
    @Column(name="id_regione", unique=true, nullable=false)
    public Integer getIdRegione() {
        return this.idRegione;
    }
    public void setIdRegione(Integer idRegione) {
        this.idRegione = idRegione;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pf_principal", nullable=false)
    public PfPrincipal getPfPrincipal() {
        return this.pfPrincipal;
    }
    public void setPfPrincipal(PfPrincipal pfPrincipalByIdPfPrincipal) {
        this.pfPrincipal = pfPrincipalByIdPfPrincipal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_regione", nullable=false)
    public DeRegione getDeRegione() {
        return this.deRegione;
    }
    public void setDeRegione(DeRegione deRegione) {
        this.deRegione = deRegione;
    }
    
}
