package it.eng.myportal.entity;
// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import it.eng.myportal.entity.decodifiche.DeAttivita;
/**
 * RvAttivita generated by hbm2java
 */
@Entity
@Table(name="rv_attivita"
    ,schema="myportal"
)
public class RvAttivita extends AbstractEntity  implements java.io.Serializable {
	private static final long serialVersionUID = 426785L;
     private Integer idRvAttivita;


     private RvTestata rvTestata;
     private DeAttivita deAttivita;


    public RvAttivita() {
    }
   
     @Id 
	@SequenceGenerator(name = "rv_attivita_id_rv_attivita_seq", sequenceName="rv_attivita_id_rv_attivita_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "rv_attivita_id_rv_attivita_seq")
    @Column(name="id_rv_attivita", unique=true, nullable=false)
    public Integer getIdRvAttivita() {
        return this.idRvAttivita;
    }
    public void setIdRvAttivita(Integer idRvAttivita) {
        this.idRvAttivita = idRvAttivita;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rv_testata", nullable=false)
    public RvTestata getRvTestata() {
        return this.rvTestata;
    }
    public void setRvTestata(RvTestata rvTestata) {
        this.rvTestata = rvTestata;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_ateco", nullable=false)
    public DeAttivita getDeAttivita() {
        return this.deAttivita;
    }
    public void setDeAttivita(DeAttivita deAttivita) {
        this.deAttivita = deAttivita;
    }
    
}
