package it.eng.myportal.entity;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import it.eng.myportal.entity.decodifiche.DeAgevolazione;
import it.eng.myportal.entity.decodifiche.sil.DeAgevolazioneSil;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * VaAgevolazione generated by hbm2java
 */

@NamedQuery(name = "prova", query = "select t from VaAgevolazione t")
@Entity
@Table(name = "va_agevolazione", schema = "myportal")
public class VaAgevolazione extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 480928L;
	private Integer idVaAgevolazione;

	private VaDatiVacancy vaDatiVacancy;
	private DeAgevolazione deAgevolazione;
	private DeAgevolazioneSil deAgevolazioneSil;
	private String opzIndispensabile;

	public VaAgevolazione() {
	}

	public VaAgevolazione(Integer idVaAgevolazione, PfPrincipal pfPrincipalByIdPrincipalMod,
			PfPrincipal pfPrincipalByIdPrincipalIns, VaDatiVacancy vaDatiVacancy, DeAgevolazione deAgevolazione,
			Date dtmIns, Date dtmMod) {
		super(pfPrincipalByIdPrincipalIns, pfPrincipalByIdPrincipalMod, dtmIns, dtmMod);
		this.idVaAgevolazione = idVaAgevolazione;

		this.vaDatiVacancy = vaDatiVacancy;
		this.deAgevolazione = deAgevolazione;

	}

	@Id
	@SequenceGenerator(name = "va_agevolazione_id_va_agevolazione_seq", sequenceName = "va_agevolazione_id_va_agevolazione_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "va_agevolazione_id_va_agevolazione_seq")
	@Column(name = "id_va_agevolazione", unique = true, nullable = false)
	public Integer getIdVaAgevolazione() {
		return this.idVaAgevolazione;
	}

	public void setIdVaAgevolazione(Integer idVaAgevolazione) {
		this.idVaAgevolazione = idVaAgevolazione;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_va_dati_vacancy", nullable = false)
	public VaDatiVacancy getVaDatiVacancy() {
		return this.vaDatiVacancy;
	}

	public void setVaDatiVacancy(VaDatiVacancy vaDatiVacancy) {
		this.vaDatiVacancy = vaDatiVacancy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_agevolazione")
	public DeAgevolazione getDeAgevolazione() {
		return this.deAgevolazione;
	}

	public void setDeAgevolazione(DeAgevolazione deAgevolazione) {
		this.deAgevolazione = deAgevolazione;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_agevolazione_sil")
	public DeAgevolazioneSil getDeAgevolazioneSil() {
		return deAgevolazioneSil;
	}

	public void setDeAgevolazioneSil(DeAgevolazioneSil deAgevolazioneSil) {
		this.deAgevolazioneSil = deAgevolazioneSil;
	}

	@Column(name = "opz_indispensabile", length = 1)
	public String getOpzIndispensabile() {
		return opzIndispensabile;
	}

	public void setOpzIndispensabile(String opzIndispensabile) {
		this.opzIndispensabile = opzIndispensabile;
	}

}
