package it.eng.myportal.entity;
// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
/**
 * VaContatto generated by hbm2java
 */
@Entity
@Table(name="va_contatto"
    ,schema="myportal"
)

@NamedQueries({
	@NamedQuery(name = "VaContattoFindByVaId", query = "select d from VaContatto d where d.idVaContatto in (select v.vaContattoAlt.idVaContatto from VaDatiVacancy v where v.idVaDatiVacancy =:parametro) ")
	})


public class VaContatto extends AbstractEntity  implements java.io.Serializable {
	private static final long serialVersionUID = 57415L;
     private Integer idVaContatto;
     
     private String cognomeRiferimentoPub;
     private String nomeRiferimentoPub;
     private String telRiferimentoPub;
     private String faxRiferimentoPub;
     private String mail;
    
     private Set<VaDatiVacancy> vaDatiVacanciesForIdVaContattoPrinc = new HashSet<VaDatiVacancy>(0);
     private Set<VaDatiVacancy> vaDatiVacanciesForIdVaContattoAlt = new HashSet<VaDatiVacancy>(0);
    public VaContatto() {
    }
  
     @Id 
	@SequenceGenerator(name = "va_contatto_id_va_contatto_seq", sequenceName="va_contatto_id_va_contatto_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "va_contatto_id_va_contatto_seq")
    @Column(name="id_va_contatto", unique=true, nullable=false)
    public Integer getIdVaContatto() {
        return this.idVaContatto;
    }
    public void setIdVaContatto(Integer idVaContatto) {
        this.idVaContatto = idVaContatto;
    }
    @Column(name="cognome_riferimento_pub", length=100)
    public String getCognomeRiferimentoPub() {
        return this.cognomeRiferimentoPub;
    }
    public void setCognomeRiferimentoPub(String cognomeRiferimentoPub) {
        this.cognomeRiferimentoPub = cognomeRiferimentoPub;
    }
    @Column(name="nome_riferimento_pub", length=100)
    public String getNomeRiferimentoPub() {
        return this.nomeRiferimentoPub;
    }
    public void setNomeRiferimentoPub(String nomeRiferimentoPub) {
        this.nomeRiferimentoPub = nomeRiferimentoPub;
    }
    @Column(name="tel_riferimento_pub", length=20)
    public String getTelRiferimentoPub() {
        return this.telRiferimentoPub;
    }
    public void setTelRiferimentoPub(String telRiferimentoPub) {
        this.telRiferimentoPub = telRiferimentoPub;
    }
    @Column(name="fax_riferimento_pub", length=20)
    public String getFaxRiferimentoPub() {
        return this.faxRiferimentoPub;
    }
    public void setFaxRiferimentoPub(String faxRiferimentoPub) {
        this.faxRiferimentoPub = faxRiferimentoPub;
    }
    @Column(name="mail")
    public String getMail() {
        return this.mail;
    }
    public void setMail(String mail) {
        this.mail = mail;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="vaContattoPrinc")
    public Set<VaDatiVacancy> getVaDatiVacanciesForIdVaContattoPrinc() {
        return this.vaDatiVacanciesForIdVaContattoPrinc;
    }
    public void setVaDatiVacanciesForIdVaContattoPrinc(Set<VaDatiVacancy> vaDatiVacanciesForIdVaContattoPrinc) {
        this.vaDatiVacanciesForIdVaContattoPrinc = vaDatiVacanciesForIdVaContattoPrinc;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="vaContattoAlt")
    public Set<VaDatiVacancy> getVaDatiVacanciesForIdVaContattoAlt() {
        return this.vaDatiVacanciesForIdVaContattoAlt;
    }
    public void setVaDatiVacanciesForIdVaContattoAlt(Set<VaDatiVacancy> vaDatiVacanciesForIdVaContattoAlt) {
        this.vaDatiVacanciesForIdVaContattoAlt = vaDatiVacanciesForIdVaContattoAlt;
    }
}
