package it.eng.myportal.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import it.eng.myportal.entity.decodifiche.DeOrario;
import it.eng.myportal.entity.decodifiche.sil.DeOrarioSil;

/**
 * VaOrario generated by hbm2java
 */
@Entity
@Table(name = "va_orario", schema = "myportal")

@NamedQueries({
		@NamedQuery(name = "VaOrarioFindByVacancyId", query = "select d from VaOrario d where d.vaDatiVacancy.idVaDatiVacancy = :vaId") })
public class VaOrario extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 615223L;
	private Integer idVaOrario;

	private DeOrario deOrario;
	private DeOrarioSil deOrarioSil;
	private VaDatiVacancy vaDatiVacancy;
	 

	public VaOrario() {
	}

	public VaOrario(Integer idVaOrario, PfPrincipal pfPrincipalByIdPrincipalMod,
			PfPrincipal pfPrincipalByIdPrincipalIns, DeOrario deOrario, VaDatiVacancy vaDatiVacancy, Date dtmIns,
			Date dtmMod) {
		super(pfPrincipalByIdPrincipalIns, pfPrincipalByIdPrincipalMod, dtmIns, dtmMod);
		this.idVaOrario = idVaOrario;

		this.deOrario = deOrario;
		this.vaDatiVacancy = vaDatiVacancy;

	}

	@Id
	@SequenceGenerator(name = "va_orario_id_va_orario_seq", sequenceName = "va_orario_id_va_orario_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "va_orario_id_va_orario_seq")
	@Column(name = "id_va_orario", unique = true, nullable = false)
	public Integer getIdVaOrario() {
		return this.idVaOrario;
	}

	public void setIdVaOrario(Integer idVaOrario) {
		this.idVaOrario = idVaOrario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_orario")
	public DeOrario getDeOrario() {
		return this.deOrario;
	}

	public void setDeOrario(DeOrario deOrario) {
		this.deOrario = deOrario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_orario_sil")
	public DeOrarioSil getDeOrarioSil() {
		return deOrarioSil;
	}

	public void setDeOrarioSil(DeOrarioSil deOrarioSil) {
		this.deOrarioSil = deOrarioSil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_va_dati_vacancy", nullable = false)
	public VaDatiVacancy getVaDatiVacancy() {
		return this.vaDatiVacancy;
	}

	public void setVaDatiVacancy(VaDatiVacancy vaDatiVacancy) {
		this.vaDatiVacancy = vaDatiVacancy;
	}
 


}
