package it.eng.myportal.entity;

// Generated Mar 1, 2012 12:28:41 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import it.eng.myportal.entity.decodifiche.DeRetribuzione;

/**
 * VaRetribuzione generated by hbm2java
 */
@Entity
@Table(name = "va_retribuzione", schema = "myportal")

@NamedQueries({
	@NamedQuery(name = "VaRetribuzioneFindByVacancyId", query = "select d from VaRetribuzione d where d.vaDatiVacancy.idVaDatiVacancy = :vaId") })

public class VaRetribuzione extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 569294L;
	private Integer idVaDatiVacancy;

	private VaDatiVacancy vaDatiVacancy;
	private DeRetribuzione deRetribuzione;
	private String benefit;
	private Integer retribuzione;
	private String ccnl;

	public VaRetribuzione() {
	}

	public VaRetribuzione(PfPrincipal pfPrincipalByIdPrincipalMod, PfPrincipal pfPrincipalByIdPrincipalIns,
			VaDatiVacancy vaDatiVacancy, DeRetribuzione deRetribuzione, Date dtmIns, Date dtmMod) {
		super(pfPrincipalByIdPrincipalIns, pfPrincipalByIdPrincipalMod, dtmIns, dtmMod);

		this.vaDatiVacancy = vaDatiVacancy;
		this.deRetribuzione = deRetribuzione;

	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "vaDatiVacancy"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_va_dati_vacancy", unique = true, nullable = false)
	public Integer getIdVaDatiVacancy() {
		return this.idVaDatiVacancy;
	}

	public void setIdVaDatiVacancy(Integer idVaDatiVacancy) {
		this.idVaDatiVacancy = idVaDatiVacancy;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public VaDatiVacancy getVaDatiVacancy() {
		return this.vaDatiVacancy;
	}

	public void setVaDatiVacancy(VaDatiVacancy vaDatiVacancy) {
		this.vaDatiVacancy = vaDatiVacancy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_retribuzione", nullable = false)
	public DeRetribuzione getDeRetribuzione() {
		return this.deRetribuzione;
	}

	public void setDeRetribuzione(DeRetribuzione deRetribuzione) {
		this.deRetribuzione = deRetribuzione;
	}

	@Column(length=250)
	public String getBenefit() {
		return benefit;
	}

	public void setBenefit(String benefit) {
		this.benefit = benefit;
	}

	@Column
	public Integer getRetribuzione() {
		return retribuzione;
	}

	public void setRetribuzione(Integer retribuzione) {
		this.retribuzione = retribuzione;
	}

	@Column(length=100)
	public String getCcnl() {
		return ccnl;
	}

	public void setCcnl(String ccnl) {
		this.ccnl = ccnl;
	}

}
