package it.eng.myportal.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import it.eng.myportal.entity.decodifiche.DeTurno;
import it.eng.myportal.entity.decodifiche.sil.DeTurnoSil;

/**
 * VaTurno generated by hbm2java
 */
@Entity
@Table(name = "va_turno", schema = "myportal")
@NamedQueries({
	@NamedQuery(name = "VaTurnoFindByVacancyId", query = "select d from VaTurno d where d.vaDatiVacancy.idVaDatiVacancy = :vaId") })

public class VaTurno extends AbstractEntity implements java.io.Serializable {
	private static final long serialVersionUID = 404454L;
	private Integer idVaTurno;

	private DeTurno deTurno;
	private DeTurnoSil deTurnoSil;
	private VaDatiVacancy vaDatiVacancy;

	public VaTurno() {
	}

	public VaTurno(Integer idVaTurno, PfPrincipal pfPrincipalByIdPrincipalMod, PfPrincipal pfPrincipalByIdPrincipalIns,
			DeTurno deTurno, VaDatiVacancy vaDatiVacancy, Date dtmIns, Date dtmMod) {
		super(pfPrincipalByIdPrincipalIns, pfPrincipalByIdPrincipalMod, dtmIns, dtmMod);
		this.idVaTurno = idVaTurno;

		this.deTurno = deTurno;
		this.vaDatiVacancy = vaDatiVacancy;

	}

	@Id
	@SequenceGenerator(name = "va_turno_id_va_turno_seq", sequenceName = "va_turno_id_va_turno_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "va_turno_id_va_turno_seq")
	@Column(name = "id_va_turno", unique = true, nullable = false)
	public Integer getIdVaTurno() {
		return this.idVaTurno;
	}

	public void setIdVaTurno(Integer idVaTurno) {
		this.idVaTurno = idVaTurno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_turno")
	public DeTurno getDeTurno() {
		return this.deTurno;
	}

	public void setDeTurno(DeTurno deTurno) {
		this.deTurno = deTurno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_va_dati_vacancy", nullable = false)
	public VaDatiVacancy getVaDatiVacancy() {
		return this.vaDatiVacancy;
	}

	public void setVaDatiVacancy(VaDatiVacancy vaDatiVacancy) {
		this.vaDatiVacancy = vaDatiVacancy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_turno_sil")
	public DeTurnoSil getDeTurnoSil() {
		return deTurnoSil;
	}

	public void setDeTurnoSil(DeTurnoSil deTurnoSil) {
		this.deTurnoSil = deTurnoSil;
	}


}
