//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.28 at 11:12:54 AM CEST 
//

package it.eng.sil.coop.webservices.dataAdesione.output;

import javax.xml.bind.annotation.XmlRegistry;

import it.eng.sil.coop.webservices.dataAdesione.output.Risposta.Adesioni;
import it.eng.sil.coop.webservices.dataAdesione.output.Risposta.Adesioni.Adesione;
import it.eng.sil.coop.webservices.dataAdesione.output.Risposta.Esito;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * DataAdesione package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * DataAdesione
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Adesione }
	 * 
	 */
	public Adesione createRispostaAdesioniAdesione() {
		return new Adesione();
	}

	/**
	 * Create an instance of {@link Esito }
	 * 
	 */
	public Esito createRispostaEsito() {
		return new Esito();
	}

	/**
	 * Create an instance of {@link Adesioni }
	 * 
	 */
	public Adesioni createRispostaAdesioni() {
		return new Adesioni();
	}

	/**
	 * Create an instance of {@link Risposta }
	 * 
	 */
	public Risposta createRisposta() {
		return new Risposta();
	}

}
