<wsdl:definitions name="InformationDelivery_ConferimentoDID" targetNamespace="http://anpal.gov.it/Services/InformationDelivery/ConferimentoDID/1.0" xmlns:db="http://anpal.gov.it/DataModels/InformationDelivery/ConferimentoDID/1.0" xmlns:tns="http://anpal.gov.it/Services/InformationDelivery/ConferimentoDID/1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://anpal.gov.it/DataModels/InformationDelivery/ConferimentoDID/1.0" schemaLocation="XS_ID_ConferimentoDID_4.0.xsd"/>
		</schema>
	</wsdl:types>
	<!-- Modificato da Stefania Orioli e Simone DellOrto per corretto funzonamento -->
	
        
	<!-- ################################################################################################### -->
  	<!-- ###################### DEFINIZIONE MESSAGGI INPUT/OUTPUT PER OGNI OPERAZIONE ###################### -->
  	<!-- ################################################################################################### -->
  
 	<!-- ############################################## INPUT ############################################## -->
 	
	<wsdl:message name="GestisciDID_Input_msg">
		<wsdl:part name="GestisciDID_Input_msg" element="db:GestisciDID_Input"/>
	</wsdl:message>
	
	
  	<!-- ############################################# OUTPUT ############################################## -->

	<wsdl:message name="GestisciDID_Output_msg">
		<wsdl:part name="GestisciDID_Output_msg" element="db:GestisciDID_Output"/>
	</wsdl:message>
	
        
	<!-- ################################################################################################### -->
  	<!-- ################################### DEFINIZIONE DELLE OPERAZIONI ################################## -->
  	<!-- ################################################################################################### -->
		
	<wsdl:portType name="ConferimentoDID_PortType">
		<wsdl:operation name="gestisciDID">
			<wsdl:input message="tns:GestisciDID_Input_msg"/>
			<wsdl:output message="tns:GestisciDID_Output_msg"/>
		</wsdl:operation>
	</wsdl:portType>



	<!-- ################################################################################################### -->
  	<!-- ######################################### BINDING WSDL-JCA ######################################## -->
  	<!-- ################################################################################################### -->
	
	<wsdl:binding name="ConferimentoDID_Binding" type="tns:ConferimentoDID_PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="gestisciDID">
			<soap:operation soapAction="http://anpal.gov.it/DataModels/InformationDelivery/ConferimentoDID/1.0/gestisciDID"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="ConferimentoDID_BindingService" >
		 <wsdl:port binding="tns:ConferimentoDID_Binding" name="gestisciDID">
 
            <soap:address location="https://pddtest.regione.emilia-romagna.it/pdd/PD/ConferimentoDID/gestisciDID"/>
        </wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>
