//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.31 at 12:20:27 PM CEST 
//


package it.eng.myportal.cliclavoro.messaggio;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}codicefiscale" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}codiceintermediario" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}denominazione" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}indirizzo" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}comune" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}telefono" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}email" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/messaggio}codiceoffertacandidatura" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codicefiscale",
    "codiceintermediario",
    "denominazione",
    "indirizzo",
    "comune",
    "telefono",
    "email",
    "codiceoffertacandidatura"
})
@XmlRootElement(name = "Interlocutore")
public class Interlocutore {

    protected String codicefiscale;
    protected String codiceintermediario;
    protected String denominazione;
    protected String indirizzo;
    protected String comune;
    protected String telefono;
    protected String email;
    protected String codiceoffertacandidatura;

    /**
     * Gets the value of the codicefiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodicefiscale() {
        return codicefiscale;
    }

    /**
     * Sets the value of the codicefiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodicefiscale(String value) {
        this.codicefiscale = value;
    }

    /**
     * Gets the value of the codiceintermediario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceintermediario() {
        return codiceintermediario;
    }

    /**
     * Sets the value of the codiceintermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceintermediario(String value) {
        this.codiceintermediario = value;
    }

    /**
     * Gets the value of the denominazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * Sets the value of the denominazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazione(String value) {
        this.denominazione = value;
    }

    /**
     * Gets the value of the indirizzo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzo() {
        return indirizzo;
    }

    /**
     * Sets the value of the indirizzo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzo(String value) {
        this.indirizzo = value;
    }

    /**
     * Gets the value of the comune property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComune() {
        return comune;
    }

    /**
     * Sets the value of the comune property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComune(String value) {
        this.comune = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefono(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the codiceoffertacandidatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceoffertacandidatura() {
        return codiceoffertacandidatura;
    }

    /**
     * Sets the value of the codiceoffertacandidatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceoffertacandidatura(String value) {
        this.codiceoffertacandidatura = value;
    }

}
