//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.31 at 12:20:27 PM CEST 
//


package it.eng.myportal.cliclavoro.messaggio;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.eng.myportal.cliclavoro.messaggio package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Codicemessaggio_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "codicemessaggio");
    private final static QName _Codicemessaggioprecedente_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "codicemessaggioprecedente");
    private final static QName _Tiposoggetto_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "tiposoggetto");
    private final static QName _Codicefiscale_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "codicefiscale");
    private final static QName _Comune_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "comune");
    private final static QName _Testomessaggio_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "testomessaggio");
    private final static QName _Contattopositivo_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "contattopositivo");
    private final static QName _Email_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "email");
    private final static QName _Tipocomunicazione_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "tipocomunicazione");
    private final static QName _Data_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "data");
    private final static QName _Telefono_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "telefono");
    private final static QName _Denominazione_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "denominazione");
    private final static QName _Codiceoffertacandidatura_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "codiceoffertacandidatura");
    private final static QName _Codiceintermediario_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "codiceintermediario");
    private final static QName _Indirizzo_QNAME = new QName("http://servizi.lavoro.gov.it/messaggio", "indirizzo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.eng.myportal.cliclavoro.messaggio
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Destinatario }
     * 
     */
    public Destinatario createDestinatario() {
        return new Destinatario();
    }

    /**
     * Create an instance of {@link DatiSistema }
     * 
     */
    public DatiSistema createDatiSistema() {
        return new DatiSistema();
    }

    /**
     * Create an instance of {@link Interlocutore }
     * 
     */
    public Interlocutore createInterlocutore() {
        return new Interlocutore();
    }

    /**
     * Create an instance of {@link Mittente }
     * 
     */
    public Mittente createMittente() {
        return new Mittente();
    }

    /**
     * Create an instance of {@link Messaggio }
     * 
     */
    public Messaggio createMessaggio() {
        return new Messaggio();
    }

    /**
     * Create an instance of {@link Corpo }
     * 
     */
    public Corpo createCorpo() {
        return new Corpo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "codicemessaggio")
    public JAXBElement<String> createCodicemessaggio(String value) {
        return new JAXBElement<String>(_Codicemessaggio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "codicemessaggioprecedente")
    public JAXBElement<String> createCodicemessaggioprecedente(String value) {
        return new JAXBElement<String>(_Codicemessaggioprecedente_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "tiposoggetto")
    public JAXBElement<String> createTiposoggetto(String value) {
        return new JAXBElement<String>(_Tiposoggetto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "codicefiscale")
    public JAXBElement<String> createCodicefiscale(String value) {
        return new JAXBElement<String>(_Codicefiscale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "comune")
    public JAXBElement<String> createComune(String value) {
        return new JAXBElement<String>(_Comune_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "testomessaggio")
    public JAXBElement<String> createTestomessaggio(String value) {
        return new JAXBElement<String>(_Testomessaggio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SiNo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "contattopositivo")
    public JAXBElement<SiNo> createContattopositivo(SiNo value) {
        return new JAXBElement<SiNo>(_Contattopositivo_QNAME, SiNo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "tipocomunicazione")
    public JAXBElement<String> createTipocomunicazione(String value) {
        return new JAXBElement<String>(_Tipocomunicazione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "data")
    public JAXBElement<XMLGregorianCalendar> createData(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Data_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "telefono")
    public JAXBElement<String> createTelefono(String value) {
        return new JAXBElement<String>(_Telefono_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "denominazione")
    public JAXBElement<String> createDenominazione(String value) {
        return new JAXBElement<String>(_Denominazione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "codiceoffertacandidatura")
    public JAXBElement<String> createCodiceoffertacandidatura(String value) {
        return new JAXBElement<String>(_Codiceoffertacandidatura_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "codiceintermediario")
    public JAXBElement<String> createCodiceintermediario(String value) {
        return new JAXBElement<String>(_Codiceintermediario_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servizi.lavoro.gov.it/messaggio", name = "indirizzo")
    public JAXBElement<String> createIndirizzo(String value) {
        return new JAXBElement<String>(_Indirizzo_QNAME, String.class, null, value);
    }

}
