//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.31 at 12:20:27 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://servizi.lavoro.gov.it/messaggio", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.eng.myportal.cliclavoro.messaggio;
