package it.eng.sil.module.movimenti;

import java.math.BigDecimal;

import com.engiweb.framework.base.RequestContainer;
import com.engiweb.framework.base.SessionContainer;
import com.engiweb.framework.base.SourceBean;

import it.eng.afExt.utils.StringUtils;
import it.eng.afExt.utils.TransactionQueryExecutor;
import it.eng.sil.Values;
import it.eng.sil.module.AbstractSimpleModule;
import it.eng.sil.security.User;

public class ArchiviaMovimento extends AbstractSimpleModule {
	static org.apache.log4j.Logger _logger = org.apache.log4j.Logger.getLogger(ArchiviaMovimento.class.getName());
	private String className;

	public ArchiviaMovimento() {
		className = this.getClass().getName();
	}

	public void service(SourceBean request, SourceBean response) throws Exception {
		TransactionQueryExecutor txExec = null;
		String cdnLav = null;
		try {
			txExec = new TransactionQueryExecutor(Values.DB_SIL_DATI);
			txExec.initTransaction();
			Object prgMovApp = request.getAttribute("PRGMOVIMENTOAPP");
			Object prgMovAppCVE = StringUtils.getAttributeStrNotNull(request, "PRGMOVIMENTOAPPCVEARCH");

			// gestione cessazione veloce e avviamento da cessazione veloce
			if (prgMovAppCVE != null && !prgMovAppCVE.equals("")) {
				String statementInsertCVE = "insert into AM_MOV_APP_ARCHIVIO (PRGMOVIMENTOAPP, STRAZCODICEFISCALE, STRAZPARTITAIVA, "
						+ " STRAZRAGIONESOCIALE, CODAZATECO, CODAZCCNL, NUMAZDIPENDENTI, STRPATINAIL, STRUAINDIRIZZO, "
						+ " CODUACOM,STRUACAP,STRUATEL,STRUAFAX,STRUAEMAIL,STRUALINDIRIZZO,CODUALCOM,STRCODICEFISCALE, "
						+ " STRCOGNOME,STRNOME,STRSESSO,DATNASC,CODCOMNASC,CODCITTADINANZA,CODCOMDOM,STRINDIRIZZODOM, "
						+ " STRCAPDOM,DATSCADENZA,CODTIPOTITOLO,CODCPI,DATCOMUNICAZ,DATINIZIOMOV,CODTIPOMOV, "
						+ " CODMANSIONE,STRDESATTIVITA,CODCONTRATTO,CODMONOTEMPO,FLGSOCIO,CODCCNL,DECRETRIBUZIONEMEN, "
						+ " NUMLIVELLO,FLGLEGGE68,FLGLAVDOMICILIO,CODAGEVOLAZIONE,CODORARIO,CODMVCESSAZIONE,DATFINEMOV, "
						+ " STRNOTE,CDNUTINS,DTMINS,CDNUTMOD,DTMMOD,STRMATRICOLA,CODTIPOASS,CODNORMATIVA,CODGRADO, "
						+ " FLGARTIGIANA,DATCFL,STRNUMCFL,STRTIPOCFL,NUMMESIAPPRENDISTATO,CODMONOPROV,STRPOSINPS,CODSTATOATTO, "
						+ " FLGASSPROPRIA,STRAZINTCODICEFISCALE,STRAZINTPARTITAIVA,STRAZINTRAGIONESOCIALE,CODAZINTATECO,NUMAZINTDIPENDENTI, "
						+ " CODAZINTTIPOAZIENDA,STRUAINTINDIRIZZO,CODUAINTCOM,STRUAINTCAP,STRAZNUMALBOINTERINALI,STRNUMREGISTROCOMMITT, "
						+ " DATREGISTROCOMMITT,FLGRETRIBUZIONEMENCCNL,STRLUOGODILAVORO,CODCPILAV,DATVISITAMEDICA,STRAPPCODICEFISCALETUTORE, "
						+ " STRAPPCOGNOMETUTORE,STRAPPNOMETUTORE,NUMAPPANNIESPTUTORE,STRAPPLIVELLOTUTORE,CODAPPMANSIONETUTORE,CODAZTIPOAZIENDA, "
						+ " STRAZINTNUMCONTRATTO,DATAZINTINIZIOCONTRATTO,DATAZINTFINECONTRATTO,STRAZINTRAP,NUMAZINTSOGGETTI,NUMGGTRAMOVCOMUNICAZIONE, "
						+ " STRREFERENTE,STRNUMPRTPROVINCIA,NUMGGPREVISTIAGR,NUMGGEFFETTUATIAGR,PRGMOVIMENTOAPPCVE,FLGASSDACESS,FLGTITOLARETUTORE, "
						+ " NUMORESETT,CODCOMNASCDI,DATNASCDI,STRSESSODI,CODLAVORAZIONE,CODLIVELLOAGR,CODCATEGORIA,STRVERSIONETRACCIATO, "
						+ " CODQUALIFICASRQ,CODTIPOCOMUNIC,CODCOMUNICAZIONE,CODTIPODOCEX,STRNUMDOCEX,CODMOTIVOPERMSOGGEX,CODTIPOENTEPREV, "
						+ " STRCODICEENTEPREV,CODTIPOTRASF,CODTIPOCONTRATTO,STRCODICEFISCALEAZPREC,STRRAGIONESOCIALEAZPREC,CODCOMAZPREC,STRINDIRIZZOAZPREC, "
						+ " STRCAPAZPREC,CODATECOAZPREC,STRPATAZPREC,STRTELAZPREC,STRFAXAZPREC,STREMAILAZPREC, "
						+ " DATINIZIORAPLAV,DATFINERAPLAV,CODSOGGETTO, "
						+ " CODCOMUNICAZIONEPREC,DATFINEPRORAPLAV,DATCESSRAPLAV,CODTIPOSOMM, NUMPROTESTERNO, NUMANNOPROTESTERNO, NUMCONVENZIONE, DATCONVENZIONE, "
						+ "	CODTIPOMIS, FLGLAVOROAGR, FLGDISTPARZIALE, FLGDISTAZESTERA, FLGPA, FLGSISTEMAZIONEALLOGGIATIVA, FLGPAGAMENTORIMPATRIO, "
						+ " FLGAZUTILIZESTERA, DATFINEAFFITTORAMO, STRNUMAGSOMMINISTRAZIONE, "
						+ " CODQUESTURA, STRCOGNOMELEGRAPP, STRNOMELEGRAPP, CODCITTADINANZALEGRAPP, STRSESSOLEGRAPP, DATNASCLEGRAPP, "
						+ " CODCOMNASCLEGRAPP, DATSCADENZALEGRAPP, CODTIPODOCEXLEGRAPP, STRNUMDOCEXLEGRAPP, CODMOTIVOPERMSOGGEXLEGRAPP, CODQUESTURALEGRAPP, "
						+ " FLGAZESTERA, STRCFAZESTERA, STRRAGSOCAZESTERA, CODTIPOENTEPROMOTORE, STRDENOMINAZIONETIR, CODCATEGORIATIR, CODTIPOLOGIATIR, CODSOGGPROMOTOREMIN, "
						+ " FLGASSOBBL, CODCATASSOBBL) "
						+ " SELECT PRGMOVIMENTOAPP, STRAZCODICEFISCALE, STRAZPARTITAIVA,STRAZRAGIONESOCIALE,CODAZATECO, "
						+ " CODAZCCNL,NUMAZDIPENDENTI,STRPATINAIL,STRUAINDIRIZZO,CODUACOM,STRUACAP,STRUATEL,STRUAFAX,STRUAEMAIL, "
						+ " STRUALINDIRIZZO,CODUALCOM,STRCODICEFISCALE,STRCOGNOME,STRNOME,STRSESSO,DATNASC,CODCOMNASC,CODCITTADINANZA, "
						+ " CODCOMDOM,STRINDIRIZZODOM,STRCAPDOM,DATSCADENZA,CODTIPOTITOLO,CODCPI,DATCOMUNICAZ,DATINIZIOMOV,CODTIPOMOV, "
						+ " CODMANSIONE,STRDESATTIVITA,CODCONTRATTO,CODMONOTEMPO,FLGSOCIO,CODCCNL,DECRETRIBUZIONEMEN,NUMLIVELLO,FLGLEGGE68, "
						+ " FLGLAVDOMICILIO,CODAGEVOLAZIONE,CODORARIO,CODMVCESSAZIONE,DATFINEMOV,STRNOTE,CDNUTINS,DTMINS,CDNUTMOD,DTMMOD, "
						+ " STRMATRICOLA,CODTIPOASS,CODNORMATIVA,CODGRADO,FLGARTIGIANA,DATCFL,STRNUMCFL,STRTIPOCFL,NUMMESIAPPRENDISTATO, "
						+ " CODMONOPROV,STRPOSINPS,CODSTATOATTO,FLGASSPROPRIA,STRAZINTCODICEFISCALE,STRAZINTPARTITAIVA,STRAZINTRAGIONESOCIALE, "
						+ " CODAZINTATECO,NUMAZINTDIPENDENTI,CODAZINTTIPOAZIENDA,STRUAINTINDIRIZZO,CODUAINTCOM,STRUAINTCAP,STRAZNUMALBOINTERINALI, "
						+ " STRNUMREGISTROCOMMITT,DATREGISTROCOMMITT,FLGRETRIBUZIONEMENCCNL,STRLUOGODILAVORO,CODCPILAV,DATVISITAMEDICA,STRAPPCODICEFISCALETUTORE, "
						+ " STRAPPCOGNOMETUTORE,STRAPPNOMETUTORE,NUMAPPANNIESPTUTORE,STRAPPLIVELLOTUTORE,CODAPPMANSIONETUTORE,CODAZTIPOAZIENDA,STRAZINTNUMCONTRATTO,DATAZINTINIZIOCONTRATTO, "
						+ " DATAZINTFINECONTRATTO,STRAZINTRAP,NUMAZINTSOGGETTI,NUMGGTRAMOVCOMUNICAZIONE,STRREFERENTE,STRNUMPRTPROVINCIA,NUMGGPREVISTIAGR,NUMGGEFFETTUATIAGR,PRGMOVIMENTOAPPCVE, "
						+ " FLGASSDACESS,FLGTITOLARETUTORE,NUMORESETT,CODCOMNASCDI,DATNASCDI,STRSESSODI,CODLAVORAZIONE,CODLIVELLOAGR,CODCATEGORIA,STRVERSIONETRACCIATO,CODQUALIFICASRQ, "
						+ " CODTIPOCOMUNIC,CODCOMUNICAZIONE,CODTIPODOCEX,STRNUMDOCEX,CODMOTIVOPERMSOGGEX,CODTIPOENTEPREV,STRCODICEENTEPREV,CODTIPOTRASF,CODTIPOCONTRATTO,STRCODICEFISCALEAZPREC, "
						+ " STRRAGIONESOCIALEAZPREC,CODCOMAZPREC,STRINDIRIZZOAZPREC,STRCAPAZPREC,CODATECOAZPREC,STRPATAZPREC,STRTELAZPREC,STRFAXAZPREC,STREMAILAZPREC, "
						+ " DATINIZIORAPLAV,DATFINERAPLAV,CODSOGGETTO,CODCOMUNICAZIONEPREC,DATFINEPRORAPLAV,DATCESSRAPLAV,CODTIPOSOMM, "
						+ " NUMPROTESTERNO, NUMANNOPROTESTERNO, NUMCONVENZIONE, DATCONVENZIONE, CODTIPOMIS, FLGLAVOROAGR, FLGDISTPARZIALE, FLGDISTAZESTERA, FLGPA, "
						+ " FLGSISTEMAZIONEALLOGGIATIVA, FLGPAGAMENTORIMPATRIO, FLGAZUTILIZESTERA, DATFINEAFFITTORAMO, STRNUMAGSOMMINISTRAZIONE, "
						+ " CODQUESTURA, STRCOGNOMELEGRAPP, STRNOMELEGRAPP, CODCITTADINANZALEGRAPP, STRSESSOLEGRAPP, DATNASCLEGRAPP, "
						+ " CODCOMNASCLEGRAPP, DATSCADENZALEGRAPP, CODTIPODOCEXLEGRAPP, STRNUMDOCEXLEGRAPP, CODMOTIVOPERMSOGGEXLEGRAPP, CODQUESTURALEGRAPP, "
						+ " FLGAZESTERA, STRCFAZESTERA, STRRAGSOCAZESTERA, CODTIPOENTEPROMOTORE, STRDENOMINAZIONETIR, CODCATEGORIATIR, CODTIPOLOGIATIR, CODSOGGPROMOTOREMIN, "
						+ " FLGASSOBBL, CODCATASSOBBL " + " from AM_MOVIMENTO_APPOGGIO WHERE PRGMOVIMENTOAPP = "
						+ prgMovAppCVE;
				// inserimento sulla tabella di archivio
				txExec.executeQueryByStringStatement(statementInsertCVE, null, TransactionQueryExecutor.INSERT);
			}

			String statementInsert = "insert into AM_MOV_APP_ARCHIVIO (PRGMOVIMENTOAPP, STRAZCODICEFISCALE, STRAZPARTITAIVA, "
					+ " STRAZRAGIONESOCIALE, CODAZATECO, CODAZCCNL, NUMAZDIPENDENTI, STRPATINAIL, STRUAINDIRIZZO, "
					+ " CODUACOM,STRUACAP,STRUATEL,STRUAFAX,STRUAEMAIL,STRUALINDIRIZZO,CODUALCOM,STRCODICEFISCALE, "
					+ " STRCOGNOME,STRNOME,STRSESSO,DATNASC,CODCOMNASC,CODCITTADINANZA,CODCOMDOM,STRINDIRIZZODOM, "
					+ " STRCAPDOM,DATSCADENZA,CODTIPOTITOLO,CODCPI,DATCOMUNICAZ,DATINIZIOMOV,CODTIPOMOV, "
					+ " CODMANSIONE,STRDESATTIVITA,CODCONTRATTO,CODMONOTEMPO,FLGSOCIO,CODCCNL,DECRETRIBUZIONEMEN, "
					+ " NUMLIVELLO,FLGLEGGE68,FLGLAVDOMICILIO,CODAGEVOLAZIONE,CODORARIO,CODMVCESSAZIONE,DATFINEMOV, "
					+ " STRNOTE,CDNUTINS,DTMINS,CDNUTMOD,DTMMOD,STRMATRICOLA,CODTIPOASS,CODNORMATIVA,CODGRADO, "
					+ " FLGARTIGIANA,DATCFL,STRNUMCFL,STRTIPOCFL,NUMMESIAPPRENDISTATO,CODMONOPROV,STRPOSINPS,CODSTATOATTO, "
					+ " FLGASSPROPRIA,STRAZINTCODICEFISCALE,STRAZINTPARTITAIVA,STRAZINTRAGIONESOCIALE,CODAZINTATECO,NUMAZINTDIPENDENTI, "
					+ " CODAZINTTIPOAZIENDA,STRUAINTINDIRIZZO,CODUAINTCOM,STRUAINTCAP,STRAZNUMALBOINTERINALI,STRNUMREGISTROCOMMITT, "
					+ " DATREGISTROCOMMITT,FLGRETRIBUZIONEMENCCNL,STRLUOGODILAVORO,CODCPILAV,DATVISITAMEDICA,STRAPPCODICEFISCALETUTORE, "
					+ " STRAPPCOGNOMETUTORE,STRAPPNOMETUTORE,NUMAPPANNIESPTUTORE,STRAPPLIVELLOTUTORE,CODAPPMANSIONETUTORE,CODAZTIPOAZIENDA, "
					+ " STRAZINTNUMCONTRATTO,DATAZINTINIZIOCONTRATTO,DATAZINTFINECONTRATTO,STRAZINTRAP,NUMAZINTSOGGETTI,NUMGGTRAMOVCOMUNICAZIONE, "
					+ " STRREFERENTE,STRNUMPRTPROVINCIA,NUMGGPREVISTIAGR,NUMGGEFFETTUATIAGR,PRGMOVIMENTOAPPCVE,FLGASSDACESS,FLGTITOLARETUTORE, "
					+ " NUMORESETT,CODCOMNASCDI,DATNASCDI,STRSESSODI,CODLAVORAZIONE,CODLIVELLOAGR,CODCATEGORIA,STRVERSIONETRACCIATO, "
					+ " CODQUALIFICASRQ,CODTIPOCOMUNIC,CODCOMUNICAZIONE,CODTIPODOCEX,STRNUMDOCEX,CODMOTIVOPERMSOGGEX,CODTIPOENTEPREV, "
					+ " STRCODICEENTEPREV,CODTIPOTRASF,CODTIPOCONTRATTO,STRCODICEFISCALEAZPREC,STRRAGIONESOCIALEAZPREC,CODCOMAZPREC,STRINDIRIZZOAZPREC, "
					+ " STRCAPAZPREC,CODATECOAZPREC,STRPATAZPREC,STRTELAZPREC,STRFAXAZPREC,STREMAILAZPREC, "
					+ " DATINIZIORAPLAV,DATFINERAPLAV,CODSOGGETTO, "
					+ " CODCOMUNICAZIONEPREC,DATFINEPRORAPLAV,DATCESSRAPLAV,CODTIPOSOMM, NUMPROTESTERNO, NUMANNOPROTESTERNO, NUMCONVENZIONE, DATCONVENZIONE, "
					+ "	CODTIPOMIS, FLGLAVOROAGR, FLGDISTPARZIALE, FLGDISTAZESTERA, FLGPA, FLGSISTEMAZIONEALLOGGIATIVA, FLGPAGAMENTORIMPATRIO, "
					+ " FLGAZUTILIZESTERA, DATFINEAFFITTORAMO, STRNUMAGSOMMINISTRAZIONE, "
					+ " CODQUESTURA, STRCOGNOMELEGRAPP, STRNOMELEGRAPP, CODCITTADINANZALEGRAPP, STRSESSOLEGRAPP, DATNASCLEGRAPP, "
					+ " CODCOMNASCLEGRAPP, DATSCADENZALEGRAPP, CODTIPODOCEXLEGRAPP, STRNUMDOCEXLEGRAPP, CODMOTIVOPERMSOGGEXLEGRAPP, CODQUESTURALEGRAPP, "
					+ " FLGAZESTERA, STRCFAZESTERA, STRRAGSOCAZESTERA, CODTIPOENTEPROMOTORE, STRDENOMINAZIONETIR, CODCATEGORIATIR, CODTIPOLOGIATIR, CODSOGGPROMOTOREMIN, "
					+ " FLGASSOBBL, CODCATASSOBBL) "
					+ " SELECT PRGMOVIMENTOAPP, STRAZCODICEFISCALE, STRAZPARTITAIVA,STRAZRAGIONESOCIALE,CODAZATECO, "
					+ " CODAZCCNL,NUMAZDIPENDENTI,STRPATINAIL,STRUAINDIRIZZO,CODUACOM,STRUACAP,STRUATEL,STRUAFAX,STRUAEMAIL, "
					+ " STRUALINDIRIZZO,CODUALCOM,STRCODICEFISCALE,STRCOGNOME,STRNOME,STRSESSO,DATNASC,CODCOMNASC,CODCITTADINANZA, "
					+ " CODCOMDOM,STRINDIRIZZODOM,STRCAPDOM,DATSCADENZA,CODTIPOTITOLO,CODCPI,DATCOMUNICAZ,DATINIZIOMOV,CODTIPOMOV, "
					+ " CODMANSIONE,STRDESATTIVITA,CODCONTRATTO,CODMONOTEMPO,FLGSOCIO,CODCCNL,DECRETRIBUZIONEMEN,NUMLIVELLO,FLGLEGGE68, "
					+ " FLGLAVDOMICILIO,CODAGEVOLAZIONE,CODORARIO,CODMVCESSAZIONE,DATFINEMOV,STRNOTE,CDNUTINS,DTMINS,CDNUTMOD,DTMMOD, "
					+ " STRMATRICOLA,CODTIPOASS,CODNORMATIVA,CODGRADO,FLGARTIGIANA,DATCFL,STRNUMCFL,STRTIPOCFL,NUMMESIAPPRENDISTATO, "
					+ " CODMONOPROV,STRPOSINPS,CODSTATOATTO,FLGASSPROPRIA,STRAZINTCODICEFISCALE,STRAZINTPARTITAIVA,STRAZINTRAGIONESOCIALE, "
					+ " CODAZINTATECO,NUMAZINTDIPENDENTI,CODAZINTTIPOAZIENDA,STRUAINTINDIRIZZO,CODUAINTCOM,STRUAINTCAP,STRAZNUMALBOINTERINALI, "
					+ " STRNUMREGISTROCOMMITT,DATREGISTROCOMMITT,FLGRETRIBUZIONEMENCCNL,STRLUOGODILAVORO,CODCPILAV,DATVISITAMEDICA,STRAPPCODICEFISCALETUTORE, "
					+ " STRAPPCOGNOMETUTORE,STRAPPNOMETUTORE,NUMAPPANNIESPTUTORE,STRAPPLIVELLOTUTORE,CODAPPMANSIONETUTORE,CODAZTIPOAZIENDA,STRAZINTNUMCONTRATTO,DATAZINTINIZIOCONTRATTO, "
					+ " DATAZINTFINECONTRATTO,STRAZINTRAP,NUMAZINTSOGGETTI,NUMGGTRAMOVCOMUNICAZIONE,STRREFERENTE,STRNUMPRTPROVINCIA,NUMGGPREVISTIAGR,NUMGGEFFETTUATIAGR,PRGMOVIMENTOAPPCVE, "
					+ " FLGASSDACESS,FLGTITOLARETUTORE,NUMORESETT,CODCOMNASCDI,DATNASCDI,STRSESSODI,CODLAVORAZIONE,CODLIVELLOAGR,CODCATEGORIA,STRVERSIONETRACCIATO,CODQUALIFICASRQ, "
					+ " CODTIPOCOMUNIC,CODCOMUNICAZIONE,CODTIPODOCEX,STRNUMDOCEX,CODMOTIVOPERMSOGGEX,CODTIPOENTEPREV,STRCODICEENTEPREV,CODTIPOTRASF,CODTIPOCONTRATTO,STRCODICEFISCALEAZPREC, "
					+ " STRRAGIONESOCIALEAZPREC,CODCOMAZPREC,STRINDIRIZZOAZPREC,STRCAPAZPREC,CODATECOAZPREC,STRPATAZPREC,STRTELAZPREC,STRFAXAZPREC,STREMAILAZPREC, "
					+ " DATINIZIORAPLAV,DATFINERAPLAV,CODSOGGETTO,CODCOMUNICAZIONEPREC,DATFINEPRORAPLAV,DATCESSRAPLAV,CODTIPOSOMM, "
					+ " NUMPROTESTERNO, NUMANNOPROTESTERNO, NUMCONVENZIONE, DATCONVENZIONE, CODTIPOMIS, FLGLAVOROAGR, FLGDISTPARZIALE, FLGDISTAZESTERA, FLGPA, "
					+ " FLGSISTEMAZIONEALLOGGIATIVA, FLGPAGAMENTORIMPATRIO, FLGAZUTILIZESTERA, DATFINEAFFITTORAMO, STRNUMAGSOMMINISTRAZIONE, "
					+ " CODQUESTURA, STRCOGNOMELEGRAPP, STRNOMELEGRAPP, CODCITTADINANZALEGRAPP, STRSESSOLEGRAPP, DATNASCLEGRAPP, "
					+ " CODCOMNASCLEGRAPP, DATSCADENZALEGRAPP, CODTIPODOCEXLEGRAPP, STRNUMDOCEXLEGRAPP, CODMOTIVOPERMSOGGEXLEGRAPP, CODQUESTURALEGRAPP, "
					+ " FLGAZESTERA, STRCFAZESTERA, STRRAGSOCAZESTERA, CODTIPOENTEPROMOTORE, STRDENOMINAZIONETIR, CODCATEGORIATIR, CODTIPOLOGIATIR, CODSOGGPROMOTOREMIN, "
					+ " FLGASSOBBL, CODCATASSOBBL " + " from AM_MOVIMENTO_APPOGGIO WHERE PRGMOVIMENTOAPP = "
					+ prgMovApp;
			// inserimento sulla tabella di archivio
			txExec.executeQueryByStringStatement(statementInsert, null, TransactionQueryExecutor.INSERT);

			// recupero cdnlavoratore per inserire evidenza
			cdnLav = StringUtils.getAttributeStrNotNull(request, "CDNLAVORATOREARCH");
			// cancellazione dalla tabella di appoggio
			String deleteQuery = "delete from AM_MOVIMENTO_APPOGGIO where PRGMOVIMENTOAPP = " + prgMovApp;
			txExec.executeQueryByStringStatement(deleteQuery, null, TransactionQueryExecutor.DELETE);
			if (prgMovAppCVE != null && !prgMovAppCVE.equals("")) {
				String deleteQueryCVE = "delete from AM_MOVIMENTO_APPOGGIO where PRGMOVIMENTOAPP = " + prgMovAppCVE;
				txExec.executeQueryByStringStatement(deleteQueryCVE, null, TransactionQueryExecutor.DELETE);
			}
			// inserimento evidenza
			if (!cdnLav.equals("")) {
				RequestContainer requestContainer = getRequestContainer();
				SessionContainer sessionContainer = (SessionContainer) requestContainer.getSessionContainer();
				User user = (User) sessionContainer.getAttribute(User.USERID);
				BigDecimal userid = new BigDecimal(user.getCodut());
				String statementInsertEv = "insert into AN_EVIDENZA (PRGEVIDENZA, CDNLAVORATORE, "
						+ " DATDATASCAD, STREVIDENZA, PRGTIPOEVIDENZA, CDNUTINS, DTMINS, CDNUTMOD, DTMMOD) "
						+ " values (S_AN_EVIDENZA.nextVal, " + cdnLav + ", to_date('01/01/2100','dd/mm/yyyy'), "
						+ " 'Esistono movimenti NON VALIDATI in archivio', 23," + userid + ", sysdate, " + userid
						+ ", sysdate)";
				txExec.executeQueryByStringStatement(statementInsertEv, null, TransactionQueryExecutor.INSERT);
			}
			txExec.commitTransaction();
		} catch (Exception e) {
			if (txExec != null) {
				txExec.rollBackTransaction();
			}
			it.eng.sil.util.TraceWrapper.debug(_logger, "Impossibile archiviare il movimento", e);
		}
	}

}