/*
 * Creato il 26-lug-07
 *
 * Per modificare il modello associato a questo file generato, aprire
 * Finestra&gt;Preferenze&gt;Java&gt;Generazione codice&gt;Codice e commenti
 */
package it.eng.sil.module.movimenti;

import com.engiweb.framework.base.RequestContainer;
import com.engiweb.framework.base.SourceBean;

import it.eng.afExt.dbaccess.sql.IDynamicStatementProvider;
import it.eng.afExt.utils.StringUtils;
import it.eng.sil.util.Utils;

/**
 * @author riccardi
 *
 *         Per modificare il modello associato al commento di questo tipo generato, aprire
 *         Finestra&gt;Preferenze&gt;Java&gt;Generazione codice&gt;Codice e commenti
 */
public class DynGetMovDettaglio implements IDynamicStatementProvider {

	static org.apache.log4j.Logger _logger = org.apache.log4j.Logger.getLogger(DynGetMovDettaglio.class.getName());

	private String SELECT_PROLOGO = "SELECT TO_CHAR(PRGMOVIMENTOAPP) PRGMOVIMENTOAPP, "
			+ "STRCODICEFISCALE strCodiceFiscaleLav, "
			+ "STRCOGNOME strCognomeLav, STRNOME strNomeLav, STRSESSO STRSESSOLAV, "
			+ "TO_CHAR(DATNASC, 'DD/MM/YYYY') datNascLav, CODCOMNASC codComNascLav, "
			+ "COMNASCLAV.STRDENOMINAZIONE strComNascLav, "
			+ "MOV.CODCITTADINANZA codCittadinanzaLav, CITT.STRDESCRIZIONE strCittadinanzaLav, "
			+ "CITT.STRNAZIONE strNazioneLav, " + "CODCOMDOM codComDomLav, COMDOMLAV.STRDENOMINAZIONE strComDomLav, "
			+ "PROVLAV.STRISTAT strProvDomLav, STRINDIRIZZODOM strIndirizzoDomLav, " + "STRCAPDOM strCapDomLav, "
			+ "TO_CHAR(DATSCADENZA, 'DD/MM/YYYY') DATSCADENZALav, CODTIPOTITOLO CODTIPOTITOLOLav, "
			+ "MOV.CODCPI CODCPI, MOV.CODCPILAV CODCPILAV, " + "CPILAV.STRDESCRIZIONE STRCPILAV, "
			+ "STRAZCODICEFISCALE strCodiceFiscaleAz, STRAZPARTITAIVA strPartitaIvaAz, "
			+ "STRAZRAGIONESOCIALE strRagioneSocialeAz, CODAZATECO codAtecoUAz, "
			+ "ATTUAZ.STRDESCRIZIONE descrAtecoUAz, CODAZCCNL codCCNLAz, COLL.STRDESCRIZIONE descrCCNLAz, "
			+ "TO_CHAR(NUMAZDIPENDENTI) NUMDIPENDENTIAz, "
			+ "STRUAINDIRIZZO strIndirizzoUAz, CODUACOM codComuneUAz, STRUACAP strCapUAz, STRUATEL strTelUAz, STRUAFAX strFaxUAz, "
			+ "STRUAEMAIL strEmailUAz, STRUALINDIRIZZO strIndirizzoSede, CODUALCOM codComSede, "
			+ "MOV.STRUALTEL STRUALTEL, MOV.STRUALFAX STRUALFAX, MOV.STRUALEMAIL STRUALEMAIL, "
			+ "TO_CHAR(DATCOMUNICAZ, 'DD/MM/YYYY') DATCOMUNICAZ, "
			+ "TO_CHAR(DATINIZIOMOV, 'DD/MM/YYYY') DATINIZIOMOV, "
			+ "CODTIPOMOV, CODTIPOMIS, MOV.CODMANSIONE, STRDESATTIVITA, MOV.CODCONTRATTO, " + "CODMONOTEMPO, "
			+ "FLGSOCIO, " + "MOV.CODCCNL, " + "	CASE " + " 	WHEN (MOV.CODCCNL is not null) THEN MOV.CODCCNL "
			+ " 	ELSE 'NT' " + " END " + " CODAZINTCCNL, " + "TO_CHAR(DECRETRIBUZIONEMEN) DECRETRIBUZIONEMEN, "
			+ "TO_CHAR(DECRETRIBUZIONEANN) DECRETRIBUZIONEANN, "
			+ "TO_CHAR(NUMLIVELLO) NUMLIVELLO, FLGLEGGE68, FLGLAVDOMICILIO, MOV.FLGASSOBBL, MOV.CODCATASSOBBL, "
			+ "CODAGEVOLAZIONE, CODORARIO, TO_CHAR(NUMORESETT) NUMORESETT, CODMVCESSAZIONE, "
			+ "decode(MOV.CODTIPOMOV,'CES','',TO_CHAR(DATFINEMOV, 'DD/MM/YYYY')) DATFINEMOV, "
			+ "MOV.STRNOTE, TO_CHAR(CDNUTINS) CDNUTINS, TO_CHAR(DTMINS, 'DD/MM/YYYY') DTMINS, "
			+ "TO_CHAR(CDNUTMOD) CDNUTMOD, TO_CHAR(DTMMOD, 'DD/MM/YYYY') DTMMOD, TO_CHAR(NUMKLOMOVAPP) NUMKLOMOVAPP, "
			+ "STRMATRICOLA, MOV.CODTIPOCONTRATTO CODTIPOASS, CODNORMATIVA, CODGRADO, FLGARTIGIANA, "
			+ "TO_CHAR(DATCFL, 'DD/MM/YYYY') DATCFL, "
			+ "STRNUMCFL, STRTIPOCFL, TO_CHAR(NUMMESIAPPRENDISTATO) NUMMESIAPPRENDISTATO, "
			+ "STRPOSINPS, STRPATINAIL, CODMONOPROV, CODSTATOATTO, FLGASSPROPRIA FLGINTERASSPROPRIA, "
			+ "STRAZINTCODICEFISCALE strCodiceFiscaleAzUtil, " + "STRAZRAGIONESOCIALE || " + "	CASE "
			+ "		WHEN ((STRAZRAGIONESOCIALE is not null) and (STRUAINDIRIZZO is not null)) " + "		THEN '-' "
			+ "	END " + " || STRUAINDIRIZZO strEnteRilascio, " + "STRAZINTPARTITAIVA strPartitaIvaAzUtil, "
			+ "MOV.STRAZINTNUMCONTRATTO STRAZINTNUMCONTRATTO, "
			+ "TO_CHAR(MOV.DATAZINTINIZIOCONTRATTO, 'DD/MM/YYYY') DATAZINTINIZIOCONTRATTO, "
			+ "TO_CHAR(MOV.DATAZINTFINECONTRATTO, 'DD/MM/YYYY') DATAZINTFINECONTRATTO, "
			+ "MOV.STRAZINTRAP, MOV.CODAZINTATECO CODAZINTATECO, " + "ATTUAZUTIL.STRDESCRIZIONE descrAtecoUAzUtil, "
			+ "TO_CHAR(MOV.NUMAZINTSOGGETTI) NUMAZINTSOGGETTI, "
			+ "TO_CHAR(MOV.NUMAZINTDIPENDENTI) NUMAZINTDIPENDENTI, "
			+ "STRAZINTRAGIONESOCIALE strRagioneSocialeAzUtil, " + "STRUAINTINDIRIZZO strIndirizzoUAzUtil, "
			+ "CODUAINTCOM, STRUAINTCAP, STRAZNUMALBOINTERINALI strNumAlboInterinali, "
			+ "COMUAZ.strDenominazione || '(' || RTRIM(PROV.strIstat) || ')' comProvUAz, "
			+ "COMUAZ.strDenominazione strComuneUAz, " + "COMUAZUTIL.strDenominazione strComuneUAzUtil, "
			+ "TIPOASS.STRDESCRIZIONE descrTipoAss, " + "MOV.STRNUMREGISTROCOMMITT, "
			+ "TO_CHAR(MOV.DATREGISTROCOMMITT, 'DD/MM/YYYY') DATREGISTROCOMMITT, " + "FLGRETRIBUZIONEMENCCNL, "
			+ "STRLUOGODILAVORO strLuogoDiLavoro, " + "TO_CHAR(DATVISITAMEDICA, 'DD/MM/YYYY') DATVISITAMEDICA, "
			+ "CODAZINTTIPOAZIENDA codTipoAziendaUtil, " + "MOV.STRAPPCODICEFISCALETUTORE, "
			+ "MOV.STRAPPCODICEFISCALETUTORE STRCODICEFISCALETUTORE, " + "MOV.STRAPPCOGNOMETUTORE, "
			+ "MOV.STRAPPCOGNOMETUTORE STRCOGNOMETUTORE, " + "MOV.STRAPPNOMETUTORE, "
			+ "MOV.STRAPPNOMETUTORE STRNOMETUTORE, " + "MOV.FLGTITOLARETUTORE, " + "MOV.NUMAPPANNIESPTUTORE, "
			+ "TO_CHAR(MOV.NUMAPPANNIESPTUTORE) NUMANNIESPTUTORE, " + "MOV.STRAPPLIVELLOTUTORE, "
			+ "MOV.STRAPPLIVELLOTUTORE STRLIVELLOTUTORE, " + "MOV.CODAPPMANSIONETUTORE, "
			+ "MOV.CODAPPMANSIONETUTORE CODMANSIONETUTORE, " + "CODAZTIPOAZIENDA codTipoAzienda, "
			+ "TIPOAZ.strDescrizione DESCRTIPOAZIENDA, "
			+ "MOV.STRREFERENTE STRREFERENTE, MOV.STREMAILREFERENTE STREMAILREFERENTE, "
			+ "DE_CCNL.strDescrizione strCCNL, "
			+ "MANS.STRDESCRIZIONE descrMansione, TIPOMANS.STRDESCRIZIONE descrTipoMansione, "
			+ "TIPOASS.CODMONOTIPO codmonotipo, NVL(TIPOASS.FLGTI, 'N') FLGCONTRATTOTI, "
			+ "NVL(TIPOASS.FLGSOSPENSIONE2014, 'N') FLGSOSPENSIONE2014, "
			+ "TO_CHAR(MOV.NUMGGPREVISTIAGR)  NUMGGPREVISTIAGR, "
			+ "TO_CHAR(MOV.NUMGGEFFETTUATIAGR)  NUMGGEFFETTUATIAGR, MOV.FLGLAVOROAGR, "
			+ "MOV.FLGDISTPARZIALE, MOV.FLGDISTAZESTERA, " + "MOV.CODLAVORAZIONE, MOV.CODLIVELLOAGR, MOV.CODCATEGORIA, "
			+ "MOV.STRVERSIONETRACCIATO, MOV.PRGMOVIMENTOAPPCVE, MOV.CODQUALIFICASRQ, "
			+ "MOV.CODTIPOCOMUNIC, MOV.CODCOMUNICAZIONE, "
			+ "MOV.CODTIPODOCEX, MOV.STRNUMDOCEX, MOV.CODMOTIVOPERMSOGGEX, "
			+ "MOV.CODTIPOENTEPREV CODENTE, ENTE.STRDESCRIZIONE STRENTE, MOV.STRCODICEENTEPREV, "
			+ "MOV.CODTIPOTRASF, DE_TIPO_TRASF.FLGTRASFER, MOV.CODTIPOCONTRATTO, "
			+ "TO_CHAR(MOV.DATINIZIORAPLAV, 'DD/MM/YYYY') DATINIZIORAPLAV, "
			+ "TO_CHAR(MOV.DATFINERAPLAV, 'DD/MM/YYYY') DATFINERAPLAV, " + "MOV.DATFINEPRORAPLAV, MOV.DATCESSRAPLAV, "
			+ "MOV.CODTIPOSOMM, MOV.CODSOGGETTO, " + "MOV.CODCOMUNICAZIONEPREC, "
			+ "MOV.STRCODICEFISCALEAZPREC, MOV.CODCOMAZPREC, COMUAZPREC.strDenominazione strComuneUAzPrec, "
			+ "MOV.STRINDIRIZZOAZPREC, MOV.STRRAGIONESOCIALEAZPREC, MOV.STRPATAZPREC, "
			+ "MOV.STRFAXAZPREC, MOV.STRTELAZPREC, MOV.STRCAPAZPREC, MOV.CODATECOAZPREC, "
			+ "ATTUAZPREC.STRDESCRIZIONE descrAtecoUAzPrec, MOV.STREMAILAZPREC, "
			+ "QUALSRQ.STRDESCRIZIONE DESCQUALIFICASRQ, " + "TO_CHAR(MOV.DATCONVENZIONE, 'DD/MM/YYYY') DATCONVENZIONE, "
			+ "TO_CHAR(MOV.NUMCONVENZIONE) NUMCONVENZIONE, MOV.FLGPA, "
			+ "MOV.FLGSISTEMAZIONEALLOGGIATIVA, MOV.FLGPAGAMENTORIMPATRIO, MOV.FLGAZUTILIZESTERA, "
			+ "TO_CHAR(MOV.DATFINEAFFITTORAMO, 'DD/MM/YYYY') DATFINEAFFITTORAMO, MOV.STRNUMAGSOMMINISTRAZIONE, "
			+ "MOV.CODQUESTURA QUESTURALAV, MOV.STRCOGNOMELEGRAPP COGNOMELEGRAPP, MOV.STRNOMELEGRAPP NOMELEGRAPP, "
			+ "MOV.CODCITTADINANZALEGRAPP, MOV.STRSESSOLEGRAPP SESSOLEGRAPP, to_char(MOV.DATNASCLEGRAPP, 'DD/MM/YYYY') DATANASCITALEGRAPP, "
			+ "MOV.CODCOMNASCLEGRAPP CODCOMNASCITALEGRAPP, to_char(MOV.DATSCADENZALEGRAPP, 'DD/MM/YYYY') DATASCADENZAPSLEGRAPP, "
			+ "MOV.CODTIPODOCEXLEGRAPP CODTIPODOCPSLEGRAPP, MOV.STRNUMDOCEXLEGRAPP STRNUMDOCPSLEGRAPP, MOV.CODMOTIVOPERMSOGGEXLEGRAPP CODMOTIVOPSLEGRAPP, "
			+ "MOV.CODQUESTURALEGRAPP QUESTURALEGRAPP, MOV.FLGAZESTERA, MOV.STRCFAZESTERA CODFISCAZESTERA, MOV.STRRAGSOCAZESTERA RAGSOCAZESTERA, MOV.CODTIPOENTEPROMOTORE, "
			+ "MOV.FLGSOGGINITALIA, TO_CHAR(MOV.DATFINEPERIODOFORMATIVO, 'DD/MM/YYYY') DATFINEPF, "
			+ "MOV.FLGLAVOROINMOBILITA, MOV.FLGLAVOROSTAGIONALE, MOV.STRCODFISCPROMOTORETIR, MOV.FLGPROSECUZIONE, MOV.CODVARIAZIONE, "
			+ "MOV.STRDENOMINAZIONETIR, MOV.CODCATEGORIATIR, MOV.CODTIPOLOGIATIR, MOV.CODSOGGPROMOTOREMIN, "
			+ "MOV.STRTRACCIATO ";

	private String SELECT_EPILOGO = "DE_CONTRATTO_COLLETTIVO COLL, " + "DE_CONTRATTO_COLLETTIVO DE_CCNL, "
			+ "DE_COMUNE COMUAZ, " + "DE_COMUNE COMUAZUTIL, " + "DE_COMUNE COMNASCLAV, " + "DE_COMUNE COMDOMLAV, "
			+ "DE_COMUNE COMUAZPREC, " + "DE_PROVINCIA PROV, " + "DE_PROVINCIA PROVLAV, "
			+ "DE_TIPO_CONTRATTO TIPOASS, " + "DE_CITTADINANZA CITT, " + "DE_CPI CPILAV, " + "DE_MANSIONE MANS, "
			+ "DE_MANSIONE TIPOMANS, " + "DE_TIPO_AZIENDA TIPOAZ, " + "DE_ATTIVITA ATTUAZ, "
			+ "DE_ATTIVITA ATTUAZUTIL, " + "DE_ATTIVITA ATTUAZPREC, " + "DE_QUALIFICA_SRQ QUALSRQ, " + "DE_TIPO_TRASF,"
			+ "DE_ENTE_PREVIDENZIALE ENTE " + "WHERE MOV.CODUACOM = COMUAZ.CODCOM (+) "
			+ "AND MOV.CODUAINTCOM = COMUAZUTIL.CODCOM (+) " + "AND MOV.CODCOMNASC = COMNASCLAV.CODCOM (+) "
			+ "AND MOV.CODCOMDOM = COMDOMLAV.CODCOM (+) " + "AND MOV.CODCOMAZPREC = COMUAZPREC.CODCOM (+) "
			+ "AND COMDOMLAV.codProvincia = PROVLAV.codProvincia (+) "
			+ "AND COMUAZ.codProvincia = PROV.codProvincia (+) "
			+ "AND MOV.CODTIPOCONTRATTO = TIPOASS.CODTIPOCONTRATTO (+) " + "AND MOV.CODAZCCNL = COLL.CODCCNL (+) "
			+ "AND MOV.codCcnl = DE_CCNL.CodCcnl(+) " + "AND MOV.CODCITTADINANZA = CITT.CODCITTADINANZA (+) "
			+ "AND MOV.CODCPILAV = CPILAV.CODCPI (+) " + "AND MOV.CODMANSIONE = MANS.CODMANSIONE (+) "
			+ "AND MOV.CODQUALIFICASRQ = QUALSRQ.CODQUALIFICASRQ (+) "
			+ "AND TIPOMANS.CODMANSIONE (+) = SUBSTR(MOV.CODMANSIONE, 0,5) || '00' "
			+ "AND MOV.CODAZTIPOAZIENDA = TIPOAZ.CODTIPOAZIENDA (+) " + "AND MOV.CODAZATECO = ATTUAZ.CODATECO (+) "
			+ "AND MOV.CODAZINTATECO = ATTUAZUTIL.CODATECO (+) " + "AND MOV.CODATECOAZPREC = ATTUAZPREC.CODATECO (+) "
			+ "AND MOV.CODTIPOTRASF = DE_TIPO_TRASF.CODTIPOTRASF (+)" + "AND MOV.CODTIPOENTEPREV = ENTE.CODENTE (+) ";

	public DynGetMovDettaglio() {
	}

	public String getStatement(RequestContainer requestContainer, SourceBean config) {
		SourceBean req = requestContainer.getServiceRequest();
		String prgMovimentoApp = Utils.notNull(req.getAttribute("prgMovimentoApp"));
		String context = "";

		if (req.containsAttribute("CONTEXT")) {
			context = StringUtils.getAttributeStrNotNull(req, "CONTEXT");
		}
		if (req.containsAttribute("CURRENTCONTEXT")) {
			context = StringUtils.getAttributeStrNotNull(req, "CURRENTCONTEXT");
		}

		// Creo la parte dinamica della query e la ritorno
		String query = SELECT_PROLOGO;

		if (context.equals("validaArchivio")) {
			query += " FROM AM_MOV_APP_ARCHIVIO MOV, ";
		} else {
			query += " FROM AM_MOVIMENTO_APPOGGIO MOV, ";
		}

		query += SELECT_EPILOGO;
		query += " AND prgMovimentoApp = " + prgMovimentoApp;

		if ("".equals(prgMovimentoApp)) {
			_logger.error("prgMovimentoApp vuoto");
			_logger.error(req.toXML());
		}

		return query;
	}
}
