//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 11:27:57 AM CET 
//


package it.eng.sil.util.batch.siaper.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AnagraficaCompleta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnagraficaCompleta">
 *   &lt;complexContent>
 *     &lt;extension base="{http://servizi.lavoro.gov.it}Anagrafica">
 *       &lt;sequence>
 *         &lt;element name="sesso" type="{http://servizi.lavoro.gov.it}Sesso"/>
 *         &lt;element name="nascita">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="comune" type="{http://servizi.lavoro.gov.it}Comune"/>
 *                   &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cittadinanza">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://servizi.lavoro.gov.it}Stringa">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnagraficaCompleta", propOrder = {
    "sesso",
    "nascita",
    "cittadinanza"
})
public class AnagraficaCompleta
    extends Anagrafica
{

    @XmlElement(required = true)
    protected Sesso sesso;
    @XmlElement(required = true)
    protected AnagraficaCompleta.Nascita nascita;
    @XmlElement(required = true)
    protected String cittadinanza;

    /**
     * Gets the value of the sesso property.
     * 
     * @return
     *     possible object is
     *     {@link Sesso }
     *     
     */
    public Sesso getSesso() {
        return sesso;
    }

    /**
     * Sets the value of the sesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sesso }
     *     
     */
    public void setSesso(Sesso value) {
        this.sesso = value;
    }

    /**
     * Gets the value of the nascita property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaCompleta.Nascita }
     *     
     */
    public AnagraficaCompleta.Nascita getNascita() {
        return nascita;
    }

    /**
     * Sets the value of the nascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaCompleta.Nascita }
     *     
     */
    public void setNascita(AnagraficaCompleta.Nascita value) {
        this.nascita = value;
    }

    /**
     * Gets the value of the cittadinanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCittadinanza() {
        return cittadinanza;
    }

    /**
     * Sets the value of the cittadinanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCittadinanza(String value) {
        this.cittadinanza = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="comune" type="{http://servizi.lavoro.gov.it}Comune"/>
     *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comune",
        "data"
    })
    public static class Nascita {

        @XmlElement(required = true)
        protected String comune;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar data;

        /**
         * Gets the value of the comune property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComune() {
            return comune;
        }

        /**
         * Sets the value of the comune property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComune(String value) {
            this.comune = value;
        }

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setData(XMLGregorianCalendar value) {
            this.data = value;
        }

    }

}
