//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 11:27:57 AM CET 
//


package it.eng.sil.util.batch.siaper.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Cessazione complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cessazione">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Contratto" type="{http://servizi.lavoro.gov.it}Contratto"/>
 *       &lt;/sequence>
 *       &lt;attribute name="codiceCausa" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[A-Z]{2}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cessazione", propOrder = {
    "contratto"
})
public class Cessazione {

    @XmlElement(name = "Contratto", required = true)
    protected Contratto contratto;
    @XmlAttribute(name = "codiceCausa", required = true)
    protected String codiceCausa;

    /**
     * Gets the value of the contratto property.
     * 
     * @return
     *     possible object is
     *     {@link Contratto }
     *     
     */
    public Contratto getContratto() {
        return contratto;
    }

    /**
     * Sets the value of the contratto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contratto }
     *     
     */
    public void setContratto(Contratto value) {
        this.contratto = value;
    }

    /**
     * Gets the value of the codiceCausa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceCausa() {
        return codiceCausa;
    }

    /**
     * Sets the value of the codiceCausa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceCausa(String value) {
        this.codiceCausa = value;
    }

}
