//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 11:27:57 AM CET 
//


package it.eng.sil.util.batch.siaper.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Missione complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Missione">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="qualificaProfessionale" type="{http://servizi.lavoro.gov.it}QualificaProfessionale"/>
 *         &lt;element name="tipoOrario" type="{http://servizi.lavoro.gov.it}TipoOrario"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dataInizioMissione" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="dataFineMissione" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Missione", propOrder = {
    "qualificaProfessionale",
    "tipoOrario"
})
public class Missione {

    @XmlElement(required = true)
    protected String qualificaProfessionale;
    @XmlElement(required = true)
    protected TipoOrario tipoOrario;
    @XmlAttribute(name = "dataInizioMissione", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataInizioMissione;
    @XmlAttribute(name = "dataFineMissione")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataFineMissione;

    /**
     * Gets the value of the qualificaProfessionale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualificaProfessionale() {
        return qualificaProfessionale;
    }

    /**
     * Sets the value of the qualificaProfessionale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualificaProfessionale(String value) {
        this.qualificaProfessionale = value;
    }

    /**
     * Gets the value of the tipoOrario property.
     * 
     * @return
     *     possible object is
     *     {@link TipoOrario }
     *     
     */
    public TipoOrario getTipoOrario() {
        return tipoOrario;
    }

    /**
     * Sets the value of the tipoOrario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoOrario }
     *     
     */
    public void setTipoOrario(TipoOrario value) {
        this.tipoOrario = value;
    }

    /**
     * Gets the value of the dataInizioMissione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataInizioMissione() {
        return dataInizioMissione;
    }

    /**
     * Sets the value of the dataInizioMissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataInizioMissione(XMLGregorianCalendar value) {
        this.dataInizioMissione = value;
    }

    /**
     * Gets the value of the dataFineMissione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataFineMissione() {
        return dataFineMissione;
    }

    /**
     * Sets the value of the dataFineMissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataFineMissione(XMLGregorianCalendar value) {
        this.dataFineMissione = value;
    }

}
