//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.04 at 02:47:55 PM CEST 
//


package it.eng.sil.module.ido.vacancy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}codcomune"/>
 *         &lt;element ref="{}codtipologiacontratto" minOccurs="0"/>
 *         &lt;element ref="{}retribuzioneannualorda" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codcomune",
    "codtipologiacontratto",
    "retribuzioneannualorda"
})
@XmlRootElement(name = "CondizioniOfferte")
public class CondizioniOfferte {

    @XmlElement(required = true)
    protected String codcomune;
    protected String codtipologiacontratto;
    protected String retribuzioneannualorda;

    /**
     * Gets the value of the codcomune property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodcomune() {
        return codcomune;
    }

    /**
     * Sets the value of the codcomune property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodcomune(String value) {
        this.codcomune = value;
    }

    /**
     * Gets the value of the codtipologiacontratto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodtipologiacontratto() {
        return codtipologiacontratto;
    }

    /**
     * Sets the value of the codtipologiacontratto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodtipologiacontratto(String value) {
        this.codtipologiacontratto = value;
    }

    /**
     * Gets the value of the retribuzioneannualorda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetribuzioneannualorda() {
        return retribuzioneannualorda;
    }

    /**
     * Sets the value of the retribuzioneannualorda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetribuzioneannualorda(String value) {
        this.retribuzioneannualorda = value;
    }

}
