//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.04 at 02:47:55 PM CEST 
//


package it.eng.sil.module.ido.vacancy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}codpatentino" minOccurs="0"/>
 *         &lt;element name="patentinoindisp" type="{}Y-N" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codpatentino",
    "patentinoindisp"
})
@XmlRootElement(name = "Patentini")
public class Patentini {

    protected String codpatentino;
    protected YN patentinoindisp;

    /**
     * Gets the value of the codpatentino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodpatentino() {
        return codpatentino;
    }

    /**
     * Sets the value of the codpatentino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodpatentino(String value) {
        this.codpatentino = value;
    }

    /**
     * Gets the value of the patentinoindisp property.
     * 
     * @return
     *     possible object is
     *     {@link YN }
     *     
     */
    public YN getPatentinoindisp() {
        return patentinoindisp;
    }

    /**
     * Sets the value of the patentinoindisp property.
     * 
     * @param value
     *     allowed object is
     *     {@link YN }
     *     
     */
    public void setPatentinoindisp(YN value) {
        this.patentinoindisp = value;
    }

}
