//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.04 at 02:47:55 PM CEST 
//


package it.eng.sil.module.ido.vacancy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DatoreLavoro"/>
 *         &lt;element ref="{}Richiesta"/>
 *         &lt;element ref="{}RegistrazioneAzienda" minOccurs="0"/>
 *         &lt;element ref="{}DatiSistema"/>
 *         &lt;element ref="{}DatiAggiuntivi" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datoreLavoro",
    "richiesta",
    "registrazioneAzienda",
    "datiSistema",
    "datiAggiuntivi"
})
@XmlRootElement(name = "Vacancy")
public class Vacancy {

    @XmlElement(name = "DatoreLavoro", required = true)
    protected DatoreLavoro datoreLavoro;
    @XmlElement(name = "Richiesta", required = true)
    protected Richiesta richiesta;
    @XmlElement(name = "RegistrazioneAzienda")
    protected RegistrazioneAzienda registrazioneAzienda;
    @XmlElement(name = "DatiSistema", required = true)
    protected DatiSistema datiSistema;
    @XmlElement(name = "DatiAggiuntivi")
    protected DatiAggiuntivi datiAggiuntivi;

    /**
     * Gets the value of the datoreLavoro property.
     * 
     * @return
     *     possible object is
     *     {@link DatoreLavoro }
     *     
     */
    public DatoreLavoro getDatoreLavoro() {
        return datoreLavoro;
    }

    /**
     * Sets the value of the datoreLavoro property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatoreLavoro }
     *     
     */
    public void setDatoreLavoro(DatoreLavoro value) {
        this.datoreLavoro = value;
    }

    /**
     * Gets the value of the richiesta property.
     * 
     * @return
     *     possible object is
     *     {@link Richiesta }
     *     
     */
    public Richiesta getRichiesta() {
        return richiesta;
    }

    /**
     * Sets the value of the richiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Richiesta }
     *     
     */
    public void setRichiesta(Richiesta value) {
        this.richiesta = value;
    }

    /**
     * Gets the value of the registrazioneAzienda property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrazioneAzienda }
     *     
     */
    public RegistrazioneAzienda getRegistrazioneAzienda() {
        return registrazioneAzienda;
    }

    /**
     * Sets the value of the registrazioneAzienda property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrazioneAzienda }
     *     
     */
    public void setRegistrazioneAzienda(RegistrazioneAzienda value) {
        this.registrazioneAzienda = value;
    }

    /**
     * Gets the value of the datiSistema property.
     * 
     * @return
     *     possible object is
     *     {@link DatiSistema }
     *     
     */
    public DatiSistema getDatiSistema() {
        return datiSistema;
    }

    /**
     * Sets the value of the datiSistema property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiSistema }
     *     
     */
    public void setDatiSistema(DatiSistema value) {
        this.datiSistema = value;
    }

    /**
     * Gets the value of the datiAggiuntivi property.
     * 
     * @return
     *     possible object is
     *     {@link DatiAggiuntivi }
     *     
     */
    public DatiAggiuntivi getDatiAggiuntivi() {
        return datiAggiuntivi;
    }

    /**
     * Sets the value of the datiAggiuntivi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiAggiuntivi }
     *     
     */
    public void setDatiAggiuntivi(DatiAggiuntivi value) {
        this.datiAggiuntivi = value;
    }

}
