//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 04:08:54 PM CEST 
//

package it.eng.sil.coop.webservices.mystage.patto.custom;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codice_esito" type="{}varchar_8_type"/>
 *         &lt;element name="desc_esito" type="{}varchar_500_type"/>
 *         &lt;element name="profiling_patto" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="patto_progressivo" type="{}int_type"/>
 *                   &lt;element name="indice_svantaggio" type="{}int_type"/>
 *                   &lt;element name="indice_data_riferimento" type="{}date_type"/>
 *                   &lt;element name="adesione_gg_data" type="{}date_type"/>
 *                   &lt;element name="patto_gg_data" type="{}date_type"/>
 *                   &lt;element name="patto_numero_protocollo" type="{}int_type"/>
 *                   &lt;element name="patto_cpi" type="{}cpi_type"/>
 *                   &lt;element name="provincia_provenienza" type="{}codice_provincia_type"/>
 *                   &lt;element name="descr_provincia_provenienza" type="{}varchar_100_type"/>
 *                   &lt;element name="data_chiusura_patto" type="{}date_type"/>
 *                   &lt;element name="motivo_chiusura_patto" type="{}varchar_500_type"/>
 *                   &lt;element name="data_scadenza_patto" type="{}date_type"/>
 *                   &lt;element name="tipo_codifica_patto" type="{}varchar_8_type"/>
 *                   &lt;element name="tipo_misura_patto" type="{}varchar_8_type"/>
 *                   &lt;element name="PoliticheAttive">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PoliticaAttiva" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="tipoAttivita" type="{}varchar_3_type"/>
 *                                       &lt;element name="sottoAttivita" type="{}varchar_8_type"/>
 *                                       &lt;element name="prgAzione" type="{}int_type"/>
 *                                       &lt;element name="misura" type="{}int_type"/>
 *                                       &lt;element name="prgPercorso" type="{}int_type"/>
 *                                       &lt;element name="prgColloquio" type="{}int_type"/>
 *                                       &lt;element name="flgGruppo" type="{}si_no_type"/>
 *                                       &lt;element name="numPartecipanti" type="{}int_type"/>
 *                                       &lt;element name="dataColloquio" type="{}date_type"/>
 *                                       &lt;element name="dataStimataFineAttivita" type="{}date_type"/>
 *                                       &lt;element name="dataAvvioAttivita" type="{}date_type"/>
 *                                       &lt;element name="dataFineAttivita" type="{}date_type"/>
 *                                       &lt;element name="durataEffettiva" type="{}int_type"/>
 *                                       &lt;element name="durataMinima" type="{}int_type"/>
 *                                       &lt;element name="durataMassima" type="{}int_type"/>
 *                                       &lt;element name="tipologiaDurata" type="{}varchar_1_type"/>
 *                                       &lt;element name="esito" type="{}varchar_8_type"/>
 *                                       &lt;element name="azione" type="{}varchar_200_type"/>
 *                                       &lt;element name="obiettivo" type="{}varchar_100_type"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "codiceEsito", "descEsito", "profilingPatto" })
@XmlRootElement(name = "PattiLavoratore")
public class PattiLavoratore {

	@XmlElement(name = "codice_esito", required = true)
	protected String codiceEsito;
	@XmlElement(name = "desc_esito", required = true)
	protected String descEsito;
	@XmlElement(name = "profiling_patto")
	protected List<PattiLavoratore.ProfilingPatto> profilingPatto;

	/**
	 * Gets the value of the codiceEsito property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodiceEsito() {
		return codiceEsito;
	}

	/**
	 * Sets the value of the codiceEsito property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodiceEsito(String value) {
		this.codiceEsito = value;
	}

	/**
	 * Gets the value of the descEsito property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescEsito() {
		return descEsito;
	}

	/**
	 * Sets the value of the descEsito property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescEsito(String value) {
		this.descEsito = value;
	}

	/**
	 * Gets the value of the profilingPatto property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the profilingPatto property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProfilingPatto().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link PattiLavoratore.ProfilingPatto }
	 * 
	 * 
	 */
	public List<PattiLavoratore.ProfilingPatto> getProfilingPatto() {
		if (profilingPatto == null) {
			profilingPatto = new ArrayList<PattiLavoratore.ProfilingPatto>();
		}
		return this.profilingPatto;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="patto_progressivo" type="{}int_type"/>
	 *         &lt;element name="indice_svantaggio" type="{}int_type"/>
	 *         &lt;element name="indice_data_riferimento" type="{}date_type"/>
	 *         &lt;element name="adesione_gg_data" type="{}date_type"/>
	 *         &lt;element name="patto_gg_data" type="{}date_type"/>
	 *         &lt;element name="patto_numero_protocollo" type="{}int_type"/>
	 *         &lt;element name="patto_cpi" type="{}cpi_type"/>
	 *         &lt;element name="provincia_provenienza" type="{}codice_provincia_type"/>
	 *         &lt;element name="descr_provincia_provenienza" type="{}varchar_100_type"/>
	 *         &lt;element name="data_chiusura_patto" type="{}date_type"/>
	 *         &lt;element name="motivo_chiusura_patto" type="{}varchar_500_type"/>
	 *         &lt;element name="data_scadenza_patto" type="{}date_type"/>
	 *         &lt;element name="tipo_codifica_patto" type="{}varchar_8_type"/>
	 *         &lt;element name="tipo_misura_patto" type="{}varchar_8_type"/>
	 *         &lt;element name="PoliticheAttive">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="PoliticaAttiva" maxOccurs="unbounded" minOccurs="0">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="tipoAttivita" type="{}varchar_3_type"/>
	 *                             &lt;element name="sottoAttivita" type="{}varchar_8_type"/>
	 *                             &lt;element name="prgAzione" type="{}int_type"/>
	 *                             &lt;element name="misura" type="{}int_type"/>
	 *                             &lt;element name="prgPercorso" type="{}int_type"/>
	 *                             &lt;element name="prgColloquio" type="{}int_type"/>
	 *                             &lt;element name="flgGruppo" type="{}si_no_type"/>
	 *                             &lt;element name="numPartecipanti" type="{}int_type"/>
	 *                             &lt;element name="dataColloquio" type="{}date_type"/>
	 *                             &lt;element name="dataStimataFineAttivita" type="{}date_type"/>
	 *                             &lt;element name="dataAvvioAttivita" type="{}date_type"/>
	 *                             &lt;element name="dataFineAttivita" type="{}date_type"/>
	 *                             &lt;element name="durataEffettiva" type="{}int_type"/>
	 *                             &lt;element name="durataMinima" type="{}int_type"/>
	 *                             &lt;element name="durataMassima" type="{}int_type"/>
	 *                             &lt;element name="tipologiaDurata" type="{}varchar_1_type"/>
	 *                             &lt;element name="esito" type="{}varchar_8_type"/>
	 *                             &lt;element name="azione" type="{}varchar_200_type"/>
	 *                             &lt;element name="obiettivo" type="{}varchar_100_type"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "pattoProgressivo", "indiceSvantaggio", "indiceDataRiferimento", "adesioneGgData",
			"pattoGgData", "pattoNumeroProtocollo", "pattoCpi", "provinciaProvenienza", "descrProvinciaProvenienza",
			"dataChiusuraPatto", "motivoChiusuraPatto", "dataScadenzaPatto", "tipoCodificaPatto", "tipoMisuraPatto",
			"politicheAttive" })
	public static class ProfilingPatto {

		@XmlElement(name = "patto_progressivo", required = true)
		protected BigInteger pattoProgressivo;
		@XmlElement(name = "indice_svantaggio", required = true, nillable = true)
		protected BigInteger indiceSvantaggio;
		@XmlElement(name = "indice_data_riferimento", required = true, nillable = true)
		protected XMLGregorianCalendar indiceDataRiferimento;
		@XmlElement(name = "adesione_gg_data", required = true, nillable = true)
		protected XMLGregorianCalendar adesioneGgData;
		@XmlElement(name = "patto_gg_data", required = true)
		protected XMLGregorianCalendar pattoGgData;
		@XmlElement(name = "patto_numero_protocollo", required = true)
		protected BigInteger pattoNumeroProtocollo;
		@XmlElement(name = "patto_cpi", required = true, nillable = true)
		protected String pattoCpi;
		@XmlElement(name = "provincia_provenienza", required = true)
		protected String provinciaProvenienza;
		@XmlElement(name = "descr_provincia_provenienza", required = true)
		protected String descrProvinciaProvenienza;
		@XmlElement(name = "data_chiusura_patto", required = true, nillable = true)
		protected XMLGregorianCalendar dataChiusuraPatto;
		@XmlElement(name = "motivo_chiusura_patto", required = true, nillable = true)
		protected String motivoChiusuraPatto;
		@XmlElement(name = "data_scadenza_patto", required = true, nillable = true)
		protected XMLGregorianCalendar dataScadenzaPatto;
		@XmlElement(name = "tipo_codifica_patto", required = true)
		protected String tipoCodificaPatto;
		@XmlElement(name = "tipo_misura_patto", required = true)
		protected String tipoMisuraPatto;
		@XmlElement(name = "PoliticheAttive", required = true)
		protected PattiLavoratore.ProfilingPatto.PoliticheAttive politicheAttive;

		/**
		 * Gets the value of the pattoProgressivo property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getPattoProgressivo() {
			return pattoProgressivo;
		}

		/**
		 * Sets the value of the pattoProgressivo property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setPattoProgressivo(BigInteger value) {
			this.pattoProgressivo = value;
		}

		/**
		 * Gets the value of the indiceSvantaggio property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getIndiceSvantaggio() {
			return indiceSvantaggio;
		}

		/**
		 * Sets the value of the indiceSvantaggio property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setIndiceSvantaggio(BigInteger value) {
			this.indiceSvantaggio = value;
		}

		/**
		 * Gets the value of the indiceDataRiferimento property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getIndiceDataRiferimento() {
			return indiceDataRiferimento;
		}

		/**
		 * Sets the value of the indiceDataRiferimento property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setIndiceDataRiferimento(XMLGregorianCalendar value) {
			this.indiceDataRiferimento = value;
		}

		/**
		 * Gets the value of the adesioneGgData property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getAdesioneGgData() {
			return adesioneGgData;
		}

		/**
		 * Sets the value of the adesioneGgData property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setAdesioneGgData(XMLGregorianCalendar value) {
			this.adesioneGgData = value;
		}

		/**
		 * Gets the value of the pattoGgData property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getPattoGgData() {
			return pattoGgData;
		}

		/**
		 * Sets the value of the pattoGgData property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setPattoGgData(XMLGregorianCalendar value) {
			this.pattoGgData = value;
		}

		/**
		 * Gets the value of the pattoNumeroProtocollo property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getPattoNumeroProtocollo() {
			return pattoNumeroProtocollo;
		}

		/**
		 * Sets the value of the pattoNumeroProtocollo property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setPattoNumeroProtocollo(BigInteger value) {
			this.pattoNumeroProtocollo = value;
		}

		/**
		 * Gets the value of the pattoCpi property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPattoCpi() {
			return pattoCpi;
		}

		/**
		 * Sets the value of the pattoCpi property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setPattoCpi(String value) {
			this.pattoCpi = value;
		}

		/**
		 * Gets the value of the provinciaProvenienza property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProvinciaProvenienza() {
			return provinciaProvenienza;
		}

		/**
		 * Sets the value of the provinciaProvenienza property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProvinciaProvenienza(String value) {
			this.provinciaProvenienza = value;
		}

		/**
		 * Gets the value of the descrProvinciaProvenienza property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescrProvinciaProvenienza() {
			return descrProvinciaProvenienza;
		}

		/**
		 * Sets the value of the descrProvinciaProvenienza property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDescrProvinciaProvenienza(String value) {
			this.descrProvinciaProvenienza = value;
		}

		/**
		 * Gets the value of the dataChiusuraPatto property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getDataChiusuraPatto() {
			return dataChiusuraPatto;
		}

		/**
		 * Sets the value of the dataChiusuraPatto property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDataChiusuraPatto(XMLGregorianCalendar value) {
			this.dataChiusuraPatto = value;
		}

		/**
		 * Gets the value of the motivoChiusuraPatto property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMotivoChiusuraPatto() {
			return motivoChiusuraPatto;
		}

		/**
		 * Sets the value of the motivoChiusuraPatto property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setMotivoChiusuraPatto(String value) {
			this.motivoChiusuraPatto = value;
		}

		/**
		 * Gets the value of the dataScadenzaPatto property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getDataScadenzaPatto() {
			return dataScadenzaPatto;
		}

		/**
		 * Sets the value of the dataScadenzaPatto property.
		 * 
		 * @param value
		 *            allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setDataScadenzaPatto(XMLGregorianCalendar value) {
			this.dataScadenzaPatto = value;
		}

		/**
		 * Gets the value of the tipoCodificaPatto property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTipoCodificaPatto() {
			return tipoCodificaPatto;
		}

		/**
		 * Sets the value of the tipoCodificaPatto property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTipoCodificaPatto(String value) {
			this.tipoCodificaPatto = value;
		}

		/**
		 * Gets the value of the tipoMisuraPatto property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTipoMisuraPatto() {
			return tipoMisuraPatto;
		}

		/**
		 * Sets the value of the tipoMisuraPatto property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTipoMisuraPatto(String value) {
			this.tipoMisuraPatto = value;
		}

		/**
		 * Gets the value of the politicheAttive property.
		 * 
		 * @return possible object is {@link PattiLavoratore.ProfilingPatto.PoliticheAttive }
		 * 
		 */
		public PattiLavoratore.ProfilingPatto.PoliticheAttive getPoliticheAttive() {
			return politicheAttive;
		}

		/**
		 * Sets the value of the politicheAttive property.
		 * 
		 * @param value
		 *            allowed object is {@link PattiLavoratore.ProfilingPatto.PoliticheAttive }
		 * 
		 */
		public void setPoliticheAttive(PattiLavoratore.ProfilingPatto.PoliticheAttive value) {
			this.politicheAttive = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="PoliticaAttiva" maxOccurs="unbounded" minOccurs="0">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="tipoAttivita" type="{}varchar_3_type"/>
		 *                   &lt;element name="sottoAttivita" type="{}varchar_8_type"/>
		 *                   &lt;element name="prgAzione" type="{}int_type"/>
		 *                   &lt;element name="misura" type="{}int_type"/>
		 *                   &lt;element name="prgPercorso" type="{}int_type"/>
		 *                   &lt;element name="prgColloquio" type="{}int_type"/>
		 *                   &lt;element name="flgGruppo" type="{}si_no_type"/>
		 *                   &lt;element name="numPartecipanti" type="{}int_type"/>
		 *                   &lt;element name="dataColloquio" type="{}date_type"/>
		 *                   &lt;element name="dataStimataFineAttivita" type="{}date_type"/>
		 *                   &lt;element name="dataAvvioAttivita" type="{}date_type"/>
		 *                   &lt;element name="dataFineAttivita" type="{}date_type"/>
		 *                   &lt;element name="durataEffettiva" type="{}int_type"/>
		 *                   &lt;element name="durataMinima" type="{}int_type"/>
		 *                   &lt;element name="durataMassima" type="{}int_type"/>
		 *                   &lt;element name="tipologiaDurata" type="{}varchar_1_type"/>
		 *                   &lt;element name="esito" type="{}varchar_8_type"/>
		 *                   &lt;element name="azione" type="{}varchar_200_type"/>
		 *                   &lt;element name="obiettivo" type="{}varchar_100_type"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "politicaAttiva" })
		public static class PoliticheAttive {

			@XmlElement(name = "PoliticaAttiva")
			protected List<PattiLavoratore.ProfilingPatto.PoliticheAttive.PoliticaAttiva> politicaAttiva;

			/**
			 * Gets the value of the politicaAttiva property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
			 * make to the returned list will be present inside the JAXB object. This is why there is not a
			 * <CODE>set</CODE> method for the politicaAttiva property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getPoliticaAttiva().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link PattiLavoratore.ProfilingPatto.PoliticheAttive.PoliticaAttiva }
			 * 
			 * 
			 */
			public List<PattiLavoratore.ProfilingPatto.PoliticheAttive.PoliticaAttiva> getPoliticaAttiva() {
				if (politicaAttiva == null) {
					politicaAttiva = new ArrayList<PattiLavoratore.ProfilingPatto.PoliticheAttive.PoliticaAttiva>();
				}
				return this.politicaAttiva;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="tipoAttivita" type="{}varchar_3_type"/>
			 *         &lt;element name="sottoAttivita" type="{}varchar_8_type"/>
			 *         &lt;element name="prgAzione" type="{}int_type"/>
			 *         &lt;element name="misura" type="{}int_type"/>
			 *         &lt;element name="prgPercorso" type="{}int_type"/>
			 *         &lt;element name="prgColloquio" type="{}int_type"/>
			 *         &lt;element name="flgGruppo" type="{}si_no_type"/>
			 *         &lt;element name="numPartecipanti" type="{}int_type"/>
			 *         &lt;element name="dataColloquio" type="{}date_type"/>
			 *         &lt;element name="dataStimataFineAttivita" type="{}date_type"/>
			 *         &lt;element name="dataAvvioAttivita" type="{}date_type"/>
			 *         &lt;element name="dataFineAttivita" type="{}date_type"/>
			 *         &lt;element name="durataEffettiva" type="{}int_type"/>
			 *         &lt;element name="durataMinima" type="{}int_type"/>
			 *         &lt;element name="durataMassima" type="{}int_type"/>
			 *         &lt;element name="tipologiaDurata" type="{}varchar_1_type"/>
			 *         &lt;element name="esito" type="{}varchar_8_type"/>
			 *         &lt;element name="azione" type="{}varchar_200_type"/>
			 *         &lt;element name="obiettivo" type="{}varchar_100_type"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "tipoAttivita", "sottoAttivita", "prgAzione", "misura", "prgPercorso",
					"prgColloquio", "flgGruppo", "numPartecipanti", "dataColloquio", "dataStimataFineAttivita",
					"dataAvvioAttivita", "dataFineAttivita", "durataEffettiva", "durataMinima", "durataMassima",
					"tipologiaDurata", "esito", "azione", "obiettivo" })
			public static class PoliticaAttiva {

				@XmlElement(required = true, nillable = true)
				protected String tipoAttivita;
				@XmlElement(required = true, nillable = true)
				protected String sottoAttivita;
				@XmlElement(required = true)
				protected BigInteger prgAzione;
				@XmlElement(required = true)
				protected BigInteger misura;
				@XmlElement(required = true)
				protected BigInteger prgPercorso;
				@XmlElement(required = true, nillable = true)
				protected BigInteger prgColloquio;
				@XmlElement(required = true, nillable = true)
				protected String flgGruppo;
				@XmlElement(required = true, nillable = true)
				protected BigInteger numPartecipanti;
				@XmlElement(required = true, nillable = true)
				protected XMLGregorianCalendar dataColloquio;
				@XmlElement(required = true, nillable = true)
				protected XMLGregorianCalendar dataStimataFineAttivita;
				@XmlElement(required = true, nillable = true)
				protected XMLGregorianCalendar dataAvvioAttivita;
				@XmlElement(required = true, nillable = true)
				protected XMLGregorianCalendar dataFineAttivita;
				@XmlElement(required = true, nillable = true)
				protected BigInteger durataEffettiva;
				@XmlElement(required = true, nillable = true)
				protected BigInteger durataMinima;
				@XmlElement(required = true, nillable = true)
				protected BigInteger durataMassima;
				@XmlElement(required = true, nillable = true)
				protected String tipologiaDurata;
				@XmlElement(required = true, nillable = true)
				protected String esito;
				@XmlElement(required = true, nillable = true)
				protected String azione;
				@XmlElement(required = true, nillable = true)
				protected String obiettivo;

				/**
				 * Gets the value of the tipoAttivita property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getTipoAttivita() {
					return tipoAttivita;
				}

				/**
				 * Sets the value of the tipoAttivita property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setTipoAttivita(String value) {
					this.tipoAttivita = value;
				}

				/**
				 * Gets the value of the sottoAttivita property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getSottoAttivita() {
					return sottoAttivita;
				}

				/**
				 * Sets the value of the sottoAttivita property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setSottoAttivita(String value) {
					this.sottoAttivita = value;
				}

				/**
				 * Gets the value of the prgAzione property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getPrgAzione() {
					return prgAzione;
				}

				/**
				 * Sets the value of the prgAzione property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setPrgAzione(BigInteger value) {
					this.prgAzione = value;
				}

				/**
				 * Gets the value of the misura property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getMisura() {
					return misura;
				}

				/**
				 * Sets the value of the misura property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setMisura(BigInteger value) {
					this.misura = value;
				}

				/**
				 * Gets the value of the prgPercorso property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getPrgPercorso() {
					return prgPercorso;
				}

				/**
				 * Sets the value of the prgPercorso property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setPrgPercorso(BigInteger value) {
					this.prgPercorso = value;
				}

				/**
				 * Gets the value of the prgColloquio property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getPrgColloquio() {
					return prgColloquio;
				}

				/**
				 * Sets the value of the prgColloquio property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setPrgColloquio(BigInteger value) {
					this.prgColloquio = value;
				}

				/**
				 * Gets the value of the flgGruppo property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getFlgGruppo() {
					return flgGruppo;
				}

				/**
				 * Sets the value of the flgGruppo property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setFlgGruppo(String value) {
					this.flgGruppo = value;
				}

				/**
				 * Gets the value of the numPartecipanti property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getNumPartecipanti() {
					return numPartecipanti;
				}

				/**
				 * Sets the value of the numPartecipanti property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setNumPartecipanti(BigInteger value) {
					this.numPartecipanti = value;
				}

				/**
				 * Gets the value of the dataColloquio property.
				 * 
				 * @return possible object is {@link XMLGregorianCalendar }
				 * 
				 */
				public XMLGregorianCalendar getDataColloquio() {
					return dataColloquio;
				}

				/**
				 * Sets the value of the dataColloquio property.
				 * 
				 * @param value
				 *            allowed object is {@link XMLGregorianCalendar }
				 * 
				 */
				public void setDataColloquio(XMLGregorianCalendar value) {
					this.dataColloquio = value;
				}

				/**
				 * Gets the value of the dataStimataFineAttivita property.
				 * 
				 * @return possible object is {@link XMLGregorianCalendar }
				 * 
				 */
				public XMLGregorianCalendar getDataStimataFineAttivita() {
					return dataStimataFineAttivita;
				}

				/**
				 * Sets the value of the dataStimataFineAttivita property.
				 * 
				 * @param value
				 *            allowed object is {@link XMLGregorianCalendar }
				 * 
				 */
				public void setDataStimataFineAttivita(XMLGregorianCalendar value) {
					this.dataStimataFineAttivita = value;
				}

				/**
				 * Gets the value of the dataAvvioAttivita property.
				 * 
				 * @return possible object is {@link XMLGregorianCalendar }
				 * 
				 */
				public XMLGregorianCalendar getDataAvvioAttivita() {
					return dataAvvioAttivita;
				}

				/**
				 * Sets the value of the dataAvvioAttivita property.
				 * 
				 * @param value
				 *            allowed object is {@link XMLGregorianCalendar }
				 * 
				 */
				public void setDataAvvioAttivita(XMLGregorianCalendar value) {
					this.dataAvvioAttivita = value;
				}

				/**
				 * Gets the value of the dataFineAttivita property.
				 * 
				 * @return possible object is {@link XMLGregorianCalendar }
				 * 
				 */
				public XMLGregorianCalendar getDataFineAttivita() {
					return dataFineAttivita;
				}

				/**
				 * Sets the value of the dataFineAttivita property.
				 * 
				 * @param value
				 *            allowed object is {@link XMLGregorianCalendar }
				 * 
				 */
				public void setDataFineAttivita(XMLGregorianCalendar value) {
					this.dataFineAttivita = value;
				}

				/**
				 * Gets the value of the durataEffettiva property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getDurataEffettiva() {
					return durataEffettiva;
				}

				/**
				 * Sets the value of the durataEffettiva property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setDurataEffettiva(BigInteger value) {
					this.durataEffettiva = value;
				}

				/**
				 * Gets the value of the durataMinima property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getDurataMinima() {
					return durataMinima;
				}

				/**
				 * Sets the value of the durataMinima property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setDurataMinima(BigInteger value) {
					this.durataMinima = value;
				}

				/**
				 * Gets the value of the durataMassima property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getDurataMassima() {
					return durataMassima;
				}

				/**
				 * Sets the value of the durataMassima property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setDurataMassima(BigInteger value) {
					this.durataMassima = value;
				}

				/**
				 * Gets the value of the tipologiaDurata property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getTipologiaDurata() {
					return tipologiaDurata;
				}

				/**
				 * Sets the value of the tipologiaDurata property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setTipologiaDurata(String value) {
					this.tipologiaDurata = value;
				}

				/**
				 * Gets the value of the esito property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getEsito() {
					return esito;
				}

				/**
				 * Sets the value of the esito property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setEsito(String value) {
					this.esito = value;
				}

				/**
				 * Gets the value of the azione property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getAzione() {
					return azione;
				}

				/**
				 * Sets the value of the azione property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setAzione(String value) {
					this.azione = value;
				}

				/**
				 * Gets the value of the obiettivo property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getObiettivo() {
					return obiettivo;
				}

				/**
				 * Sets the value of the obiettivo property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setObiettivo(String value) {
					this.obiettivo = value;
				}

			}

		}

	}

}
