<%--
	LOOKUP AZIENDA
	NB: qui non sono inclusi i campi chiave "prgAzienda" e "prgUnita" che vanno messi in dei campi NASCOSTI!
	    non c'è neppure il bottone per la LOOKUP.
--%>
<tr valign="top">
	<td class="etichetta">Ragione Sociale</td>
	<td class="campo">
		<input type="text" name="aziRagione" class="inputView" readonly="true" value="" size="75" maxlength="120"/>
	</td>
</tr>
<tr valign="top">
	<td class="etichetta">Indirizzo</td>
	<td class="campo">
		<input type="text" name="aziIndirizzo" class="inputView" readonly="true" value="" size="75" maxlength="120"/>
	</td>
</tr>
<tr valign="top">
	<td class="etichetta">Comune</td>
	<td class="campo">
		<input type="text" name="aziComune" class="inputView" readonly="true" value="" size="75" maxlength="100"/>
	</td>
</tr>
<tr valign="top">
	<td class="etichetta">Partita IVA</td>
	<td class="campo">
		<input type="text" name="aziPIva" class="inputView" readonly="true" value="" size="30" maxlength="30"/>
	</td>
</tr>
<tr valign="top">
	<td class="etichetta">Telefono</td>
	<td class="campo">
		<input type="text" name="aziStrTel" class="inputView" readonly="true" value="" size="30" maxlength="30"/>
	</td>
</tr>
