//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 02:59:33 PM CEST 
//


package it.eng.myportal.cliclavoro.candidatura;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}tipoesperienza" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}qualificasvolta" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}descrqualificasvolta" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}principalimansioni" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}nomedatore" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}datainizio" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}datafine" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}indirizzodatore" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}tiporapporto" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}areaesperienza" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}codateco" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}codmvcessazione" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}altrocessazione" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}pivadatorelavoro" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}cfdatorelavoro" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}codcomunedatore" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}codmansione" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipoesperienza",
    "qualificasvolta",
    "descrqualificasvolta",
    "principalimansioni",
    "nomedatore",
    "datainizio",
    "datafine",
    "indirizzodatore",
    "tiporapporto",
    "areaesperienza",
    "codateco",
    "codmvcessazione",
    "altrocessazione",
    "pivadatorelavoro",
    "cfdatorelavoro",
    "codcomunedatore",
    "codmansione"
})
@XmlRootElement(name = "EsperienzeLavorative")
public class EsperienzeLavorative {

    protected String tipoesperienza;
    protected String qualificasvolta;
    protected String descrqualificasvolta;
    protected String principalimansioni;
    protected String nomedatore;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datainizio;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datafine;
    protected String indirizzodatore;
    protected String tiporapporto;
    protected String areaesperienza;
    protected String codateco;
    protected String codmvcessazione;
    protected String altrocessazione;
    protected String pivadatorelavoro;
    protected String cfdatorelavoro;
    protected String codcomunedatore;
    protected String codmansione;

    /**
     * Gets the value of the tipoesperienza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoesperienza() {
        return tipoesperienza;
    }

    /**
     * Sets the value of the tipoesperienza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoesperienza(String value) {
        this.tipoesperienza = value;
    }

    /**
     * Gets the value of the qualificasvolta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualificasvolta() {
        return qualificasvolta;
    }

    /**
     * Sets the value of the qualificasvolta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualificasvolta(String value) {
        this.qualificasvolta = value;
    }

    /**
     * Gets the value of the descrqualificasvolta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrqualificasvolta() {
        return descrqualificasvolta;
    }

    /**
     * Sets the value of the descrqualificasvolta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrqualificasvolta(String value) {
        this.descrqualificasvolta = value;
    }

    /**
     * Gets the value of the principalimansioni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipalimansioni() {
        return principalimansioni;
    }

    /**
     * Sets the value of the principalimansioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipalimansioni(String value) {
        this.principalimansioni = value;
    }

    /**
     * Gets the value of the nomedatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomedatore() {
        return nomedatore;
    }

    /**
     * Sets the value of the nomedatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomedatore(String value) {
        this.nomedatore = value;
    }

    /**
     * Gets the value of the datainizio property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatainizio() {
        return datainizio;
    }

    /**
     * Sets the value of the datainizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatainizio(XMLGregorianCalendar value) {
        this.datainizio = value;
    }

    /**
     * Gets the value of the datafine property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatafine() {
        return datafine;
    }

    /**
     * Sets the value of the datafine property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatafine(XMLGregorianCalendar value) {
        this.datafine = value;
    }

    /**
     * Gets the value of the indirizzodatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzodatore() {
        return indirizzodatore;
    }

    /**
     * Sets the value of the indirizzodatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzodatore(String value) {
        this.indirizzodatore = value;
    }

    /**
     * Gets the value of the tiporapporto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTiporapporto() {
        return tiporapporto;
    }

    /**
     * Sets the value of the tiporapporto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTiporapporto(String value) {
        this.tiporapporto = value;
    }

    /**
     * Gets the value of the areaesperienza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaesperienza() {
        return areaesperienza;
    }

    /**
     * Sets the value of the areaesperienza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaesperienza(String value) {
        this.areaesperienza = value;
    }

    /**
     * Gets the value of the codateco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodateco() {
        return codateco;
    }

    /**
     * Sets the value of the codateco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodateco(String value) {
        this.codateco = value;
    }

    /**
     * Gets the value of the codmvcessazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodmvcessazione() {
        return codmvcessazione;
    }

    /**
     * Sets the value of the codmvcessazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodmvcessazione(String value) {
        this.codmvcessazione = value;
    }

    /**
     * Gets the value of the altrocessazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltrocessazione() {
        return altrocessazione;
    }

    /**
     * Sets the value of the altrocessazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltrocessazione(String value) {
        this.altrocessazione = value;
    }

    /**
     * Gets the value of the pivadatorelavoro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPivadatorelavoro() {
        return pivadatorelavoro;
    }

    /**
     * Sets the value of the pivadatorelavoro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPivadatorelavoro(String value) {
        this.pivadatorelavoro = value;
    }

    /**
     * Gets the value of the cfdatorelavoro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfdatorelavoro() {
        return cfdatorelavoro;
    }

    /**
     * Sets the value of the cfdatorelavoro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfdatorelavoro(String value) {
        this.cfdatorelavoro = value;
    }

    /**
     * Gets the value of the codcomunedatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodcomunedatore() {
        return codcomunedatore;
    }

    /**
     * Sets the value of the codcomunedatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodcomunedatore(String value) {
        this.codcomunedatore = value;
    }

    /**
     * Gets the value of the codmansione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodmansione() {
        return codmansione;
    }

    /**
     * Sets the value of the codmansione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodmansione(String value) {
        this.codmansione = value;
    }

}
