//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 02:59:33 PM CEST 
//


package it.eng.myportal.cliclavoro.candidatura;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}dispauto" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}dispmoto" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}dispmezzipubblici" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}pendolare" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}percorrenza" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}mobsettimanale" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}tipotrasferta" minOccurs="0"/>
 *         &lt;element ref="{http://servizi.lavoro.gov.it/candidatura}notedisponibilita" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dispauto",
    "dispmoto",
    "dispmezzipubblici",
    "pendolare",
    "percorrenza",
    "mobsettimanale",
    "tipotrasferta",
    "notedisponibilita"
})
@XmlRootElement(name = "Mobilita")
public class Mobilita {

    protected SiNo dispauto;
    protected SiNo dispmoto;
    protected SiNo dispmezzipubblici;
    protected SiNo pendolare;
    protected BigInteger percorrenza;
    protected SiNo mobsettimanale;
    protected String tipotrasferta;
    protected String notedisponibilita;

    /**
     * Gets the value of the dispauto property.
     * 
     * @return
     *     possible object is
     *     {@link SiNo }
     *     
     */
    public SiNo getDispauto() {
        return dispauto;
    }

    /**
     * Sets the value of the dispauto property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNo }
     *     
     */
    public void setDispauto(SiNo value) {
        this.dispauto = value;
    }

    /**
     * Gets the value of the dispmoto property.
     * 
     * @return
     *     possible object is
     *     {@link SiNo }
     *     
     */
    public SiNo getDispmoto() {
        return dispmoto;
    }

    /**
     * Sets the value of the dispmoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNo }
     *     
     */
    public void setDispmoto(SiNo value) {
        this.dispmoto = value;
    }

    /**
     * Gets the value of the dispmezzipubblici property.
     * 
     * @return
     *     possible object is
     *     {@link SiNo }
     *     
     */
    public SiNo getDispmezzipubblici() {
        return dispmezzipubblici;
    }

    /**
     * Sets the value of the dispmezzipubblici property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNo }
     *     
     */
    public void setDispmezzipubblici(SiNo value) {
        this.dispmezzipubblici = value;
    }

    /**
     * Gets the value of the pendolare property.
     * 
     * @return
     *     possible object is
     *     {@link SiNo }
     *     
     */
    public SiNo getPendolare() {
        return pendolare;
    }

    /**
     * Sets the value of the pendolare property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNo }
     *     
     */
    public void setPendolare(SiNo value) {
        this.pendolare = value;
    }

    /**
     * Gets the value of the percorrenza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPercorrenza() {
        return percorrenza;
    }

    /**
     * Sets the value of the percorrenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPercorrenza(BigInteger value) {
        this.percorrenza = value;
    }

    /**
     * Gets the value of the mobsettimanale property.
     * 
     * @return
     *     possible object is
     *     {@link SiNo }
     *     
     */
    public SiNo getMobsettimanale() {
        return mobsettimanale;
    }

    /**
     * Sets the value of the mobsettimanale property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNo }
     *     
     */
    public void setMobsettimanale(SiNo value) {
        this.mobsettimanale = value;
    }

    /**
     * Gets the value of the tipotrasferta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipotrasferta() {
        return tipotrasferta;
    }

    /**
     * Sets the value of the tipotrasferta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipotrasferta(String value) {
        this.tipotrasferta = value;
    }

    /**
     * Gets the value of the notedisponibilita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotedisponibilita() {
        return notedisponibilita;
    }

    /**
     * Sets the value of the notedisponibilita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotedisponibilita(String value) {
        this.notedisponibilita = value;
    }

}
