package it.eng.myportal.entity.ts;

public enum TsOpzioneEnum {	
	TIMER_NUMGG_VAC_SCADENZA,
	TIMER_NUMGG_VAC_IN_LAV,
	TIMER_NUMGG_CV_SCADENZA,
	DT_AGGIORNAMENTO_MONIT,
	FLG_AGGIORNAMENTO,
	DT_AVVIO_YG,
	DT_BATCH_YG,
	DT_BATCH_CONF_MASSIVO_YG,
	FLG_REG_UTENTE_ABILITATO_YG,
	DT_AVVIO_CLIC,
	DT_FINE_CONFERMA_DID,
	DT_FINE_DISABIL_DID_APP;
}
