<table  class="main" border="0">
<tr>
	<td class="colonna1">Codice Fiscale</td>
	<td class="colonna2">
    	<af:textBox classNameBase="input"  title="Codice fiscale" type="text" name="strCodiceFiscale1" value="<%=strCodiceFiscale1%>" size="21" maxlength="16" readonly="true" />&nbsp;    
    	&nbsp;&nbsp;&nbsp;
   	</td>
    <td class="colonna2">
    	<af:textBox classNameBase="input"  title="Codice fiscale" type="text" name="strCodiceFiscale2" value="<%=strCodiceFiscale2%>" size="21" maxlength="16"  readonly="true" />&nbsp;    
    	&nbsp;&nbsp;&nbsp;
    </td>
</tr>
<tr>
    <td class="colonna1">Ragione Sociale</td>
    <td class="colonna2">
    	<af:textBox classNameBase="input"  title="Ragione Sociale" type="text" name="strragionesociale1" value="<%=strragionesociale1%>" size="40" maxlength="40" readonly="true" />
    </td>
    <td class="colonna2">
    	<af:textBox classNameBase="input"  title="Ragione Sociale" type="text" name="strragionesociale2" value="<%=strragionesociale2%>" size="40" maxlength="40" readonly="true" />    
    </td>
</tr>
<tr>
	<td class="colonna1">Data Inizio</td>
    <td class="colonna2">
    	<af:textBox classNameBase="input"  title="Data Inizio" type="text" name="datInizio1" value="<%=datInizio1%>" size="12" maxlength="10" readonly="true" />
    </td>
    <td class="colonna2">
    	<af:textBox classNameBase="input"  title="Data Inizio" type="text" name="datInizio2" value="<%=datInizio2%>" size="12" maxlength="10" readonly="true" />
    </td>
</tr>
<tr>
	<td class="colonna1">Data Fine</td>
    <td class="colonna2">
    	<af:textBox classNameBase="input"  title="Data Fine" type="text" name="datFine1" value="<%=datFine1%>" size="12" maxlength="10" readonly="true" />
    </td>
    <td class="colonna2">
    	<af:textBox classNameBase="input"  title="Data Fine" type="text" name="datFine2" value="<%=datFine2%>" size="12" maxlength="10" readonly="true" />
    </td>
</tr>
<tr>
    <td class="colonna1">Tipo Iscrizione</td>
    <td class="colonna2">
    	<af:textBox classNameBase="input" type="text" name="tipoIscr1" readonly="true" value="<%=tipoIscr1%>" size="30" maxlength="30"/>
    </td>
    <td class="colonna2">
    	<af:textBox classNameBase="input" type="text" name="tipoIscr2" readonly="true" value="<%=tipoIscr2%>" size="30" maxlength="30"/>
    </td>
</tr>

<tr>
    <td class="colonna1">Stato</td>
    <td class="colonna2">
    	<af:textBox classNameBase="input" type="text" name="codStato1" readonly="true" value="<%=codStato1%>" size="30" maxlength="30"/>
    </td>
    <td class="colonna2">
    	<af:textBox classNameBase="input" type="text" name="codStato2" readonly="true" value="<%=codStato2%>" size="30" maxlength="30"/>
    </td>
</tr>


<tr>
    <td class="colonna1">Codice Domanda</td>
    <td class="colonna2">
    	<af:textBox classNameBase="input" type="text" name="codAccordo1" readonly="true" value="<%=codAccordo1%>" size="30" maxlength="30"/>
    </td>
    <td class="colonna2">
    	<af:textBox classNameBase="input" type="text" name="codAccordo2" readonly="true" value="<%=codAccordo2%>" size="30" maxlength="30"/>
    </td>
</tr>

</table>