//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 03:31:10 PM CEST 
//

package it.eng.sil.coop.webservices.ricezioneDomandeRA.inpsToPat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for altreComunicazioniType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="altreComunicazioniType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoEvento" type="{http://www.inps.it/comunicazioniAsdiNraCommon/0.0.1}tipologiaEventoType"/>
 *         &lt;element name="motivoEvento" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="descrizioneEvento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notaEvento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *		   &lt;element name="dataEvento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "altreComunicazioniType", propOrder = { "tipoEvento", "motivoEvento", "descrizioneEvento", "notaEvento",
		"dataEvento" })
public class AltreComunicazioniType {

	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1", required = true)
	protected TipologiaEventoType tipoEvento;
	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1")
	protected int motivoEvento;
	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1", required = true)
	protected String descrizioneEvento;
	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1")
	protected String notaEvento;
	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1")
	protected XMLGregorianCalendar dataEvento;

	/**
	 * Gets the value of the tipoEvento property.
	 * 
	 * @return possible object is {@link TipologiaEventoType }
	 * 
	 */
	public TipologiaEventoType getTipoEvento() {
		return tipoEvento;
	}

	/**
	 * Sets the value of the tipoEvento property.
	 * 
	 * @param value
	 *            allowed object is {@link TipologiaEventoType }
	 * 
	 */
	public void setTipoEvento(TipologiaEventoType value) {
		this.tipoEvento = value;
	}

	/**
	 * Gets the value of the motivoEvento property.
	 * 
	 */
	public int getMotivoEvento() {
		return motivoEvento;
	}

	/**
	 * Sets the value of the motivoEvento property.
	 * 
	 */
	public void setMotivoEvento(int value) {
		this.motivoEvento = value;
	}

	/**
	 * Gets the value of the descrizioneEvento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescrizioneEvento() {
		return descrizioneEvento;
	}

	/**
	 * Sets the value of the descrizioneEvento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescrizioneEvento(String value) {
		this.descrizioneEvento = value;
	}

	/**
	 * Gets the value of the notaEvento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNotaEvento() {
		return notaEvento;
	}

	/**
	 * Sets the value of the notaEvento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNotaEvento(String value) {
		this.notaEvento = value;
	}

	/**
	 * Gets the value of the dataEvento property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDataEvento() {
		return dataEvento;
	}

	/**
	 * Sets the value of the dataEvento property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDataEvento(XMLGregorianCalendar value) {
		this.dataEvento = value;
	}

}
