//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 03:31:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1")
package it.eng.sil.coop.webservices.ricezioneDomandeRA.inpsToPat;
