//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 03:31:10 PM CEST 
//

package it.eng.sil.coop.webservices.ricezioneDomandeRA.inpsToPat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for sottoscrizioneProgettoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sottoscrizioneProgettoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idComunicazioneMinisteroLavoro" type="{http://www.inps.it/comunicazioniAsdiNraCommon/0.0.1}identificativoComunicazioneType"/>
 *         &lt;element name="codiceIntermediario" type="{http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1}codiceIntermediarioType"/>
 *         &lt;element name="dataComunicazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sottoscrizioneProgettoType", propOrder = { "idComunicazioneMinisteroLavoro", "codiceIntermediario",
		"dataComunicazione" })
public class SottoscrizioneProgettoType {

	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1", required = true)
	protected String idComunicazioneMinisteroLavoro;
	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1", required = true)
	protected String codiceIntermediario;
	@XmlElement(namespace = "http://www.inps.it/comunicazioniAsdiNraRequest/0.0.1", required = true)
	protected XMLGregorianCalendar dataComunicazione;

	/**
	 * Gets the value of the idComunicazioneMinisteroLavoro property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdComunicazioneMinisteroLavoro() {
		return idComunicazioneMinisteroLavoro;
	}

	/**
	 * Sets the value of the idComunicazioneMinisteroLavoro property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdComunicazioneMinisteroLavoro(String value) {
		this.idComunicazioneMinisteroLavoro = value;
	}

	/**
	 * Gets the value of the codiceIntermediario property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodiceIntermediario() {
		return codiceIntermediario;
	}

	/**
	 * Sets the value of the codiceIntermediario property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodiceIntermediario(String value) {
		this.codiceIntermediario = value;
	}

	/**
	 * Gets the value of the dataComunicazione property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDataComunicazione() {
		return dataComunicazione;
	}

	/**
	 * Sets the value of the dataComunicazione property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDataComunicazione(XMLGregorianCalendar value) {
		this.dataComunicazione = value;
	}

}
